<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>RestaurantDeskApp</RootNamespace>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <EnableDefaultCssItems>false</EnableDefaultCssItems>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="..\..\..\RestaurantDeskApp\Components\**\*.razor" LinkBase="Components" />
    <Compile Include="..\..\..\RestaurantDeskApp\Models\**\*.cs" LinkBase="Models" />
    <Compile Include="..\..\..\RestaurantDeskApp\Options\**\*.cs" LinkBase="Options" />
    <Compile Include="..\..\..\RestaurantDeskApp\Services\**\*.cs" LinkBase="Services" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Ssalddel.Contracts\Ssalddel.Contracts.csproj" />
    <ProjectReference Include="..\..\..\Ssalddel.BackOffice.Client\Ssalddel.BackOffice.Client.csproj" />
    <ProjectReference Include="..\..\..\Ssalddel.Ui.Common\Ssalddel.Ui.Common.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Http" />
    <PackageReference Include="MudBlazor" />
    <PackageReference Include="System.Windows.Extensions" />
  </ItemGroup>
</Project>
