// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using 홍달.Data;

#nullable disable

namespace Hongdal.Migrations
{
    [DbContext(typeof(HongdalContext))]
    [Migration("20260623135852_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("홍달.도메인.기사.배달기사", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("NotionPageId")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("notion_page_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<string>("기사Id")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("기사Id");

                    b.Property<string>("기사명")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("기사명");

                    b.Property<DateTime?>("등록일")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("등록일");

                    b.Property<string>("메모")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("메모");

                    b.Property<string>("상태")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("상태");

                    b.Property<string>("연락처")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("연락처");

                    b.Property<string>("운행상태")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("운행상태");

                    b.Property<string>("주_활동지역")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("주_활동지역");

                    b.Property<string>("차량")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("차량");

                    b.HasKey("Id");

                    b.ToTable("배달기사");
                });

            modelBuilder.Entity("홍달.도메인.배차.기사배차", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("NotionPageId")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("notion_page_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<long?>("거리추가_요금")
                        .HasColumnType("bigint")
                        .HasColumnName("거리추가_요금");

                    b.Property<long?>("기본요금")
                        .HasColumnType("bigint")
                        .HasColumnName("기본요금");

                    b.Property<long?>("기사Id")
                        .HasColumnType("bigint")
                        .HasColumnName("기사Id");

                    b.Property<string>("메모")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("메모");

                    b.Property<long?>("배달기사_id")
                        .HasColumnType("bigint")
                        .HasColumnName("배달기사_id");

                    b.Property<string>("배송지")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("배송지");

                    b.Property<long?>("배차Id")
                        .HasColumnType("bigint")
                        .HasColumnName("배차Id");

                    b.Property<string>("배차명")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("배차명");

                    b.Property<DateTime?>("배차생성시각")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("배차생성시각");

                    b.Property<DateTime?>("배차완료시각")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("배차완료시각");

                    b.Property<DateTime?>("배차일")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("배차일");

                    b.Property<decimal?>("배차점수")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("배차점수");

                    b.Property<string>("상태")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("상태");

                    b.Property<int?>("시도횟수")
                        .HasColumnType("int")
                        .HasColumnName("시도횟수");

                    b.Property<string>("실패사유")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("실패사유");

                    b.Property<DateTime?>("잠금시각")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("잠금시각");

                    b.Property<bool>("잠금여부")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("잠금여부");

                    b.Property<long?>("주문Id")
                        .HasColumnType("bigint")
                        .HasColumnName("주문Id");

                    b.Property<int?>("픽업거리_m")
                        .HasColumnType("int")
                        .HasColumnName("픽업거리_m");

                    b.Property<int?>("픽업예상시간_sec")
                        .HasColumnType("int")
                        .HasColumnName("픽업예상시간_sec");

                    b.Property<string>("픽업지")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("픽업지");

                    b.HasKey("Id");

                    b.ToTable("기사배차");
                });

            modelBuilder.Entity("홍달.도메인.배차.배차_최소", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("NotionPageId")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("notion_page_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<string>("기사Id")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("기사Id");

                    b.Property<DateTime?>("등록일")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("등록일");

                    b.Property<long?>("배차Id")
                        .HasColumnType("bigint")
                        .HasColumnName("배차Id");

                    b.Property<string>("배차명")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("배차명");

                    b.Property<string>("음식점_주소")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("음식점_주소");

                    b.Property<string>("주문자_주소")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("주문자_주소");

                    b.HasKey("Id");

                    b.ToTable("배차_최소");
                });

            modelBuilder.Entity("홍달.도메인.업체.업체", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("NotionPageId")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("notion_page_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<string>("담당자")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("담당자");

                    b.Property<string>("대표_연락처")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("대표_연락처");

                    b.Property<DateTime?>("등록일")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("등록일");

                    b.Property<string>("메모")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("메모");

                    b.Property<string>("상태")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("상태");

                    b.Property<string>("업체명")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("업체명");

                    b.Property<string>("이메일")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("이메일");

                    b.Property<string>("정산_결제_조건")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("정산_결제_조건");

                    b.Property<string>("주소")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("주소");

                    b.Property<string>("첨부_json")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("첨부_json");

                    b.HasKey("Id");

                    b.ToTable("업체");
                });

            modelBuilder.Entity("홍달.도메인.운송.배송_운송", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("NotionPageId")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("notion_page_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<string>("기사_운송자")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("기사_운송자");

                    b.Property<DateTime?>("도착")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("도착");

                    b.Property<string>("도착지")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("도착지");

                    b.Property<string>("메모")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("메모");

                    b.Property<string>("상태")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("상태");

                    b.Property<string>("운송번호")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("운송번호");

                    b.Property<decimal?>("운임")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("운임");

                    b.Property<string>("첨부_json")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("첨부_json");

                    b.Property<DateTime?>("출발_픽업")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("출발_픽업");

                    b.Property<string>("출발지")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("출발지");

                    b.HasKey("Id");

                    b.ToTable("배송_운송");
                });
#pragma warning restore 612, 618
        }
    }
}
