// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using 홍달.Data;

#nullable disable

namespace Hongdal.Migrations
{
    [DbContext(typeof(HongdalContext))]
    [Migration("20260630002406_AddOrdererProfileAndOrdererUser")]
    partial class AddOrdererProfileAndOrdererUser
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RoleId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("홍달.Data.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("BusinessRegistrationNumber")
                        .HasColumnType("longtext");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("홍달.도메인.결제.결제", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("OrderId")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("order_id");

                    b.Property<string>("PG사")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("pg_provider");

                    b.Property<string>("PaymentKey")
                        .HasColumnType("longtext")
                        .HasColumnName("payment_key");

                    b.Property<string>("Toss응답Json")
                        .HasColumnType("longtext")
                        .HasColumnName("toss_response_json");

                    b.Property<string>("결제Id")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("payment_id");

                    b.Property<int>("결제금액")
                        .HasColumnType("int")
                        .HasColumnName("amount");

                    b.Property<string>("결제상태")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("payment_status");

                    b.Property<string>("결제수단")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("payment_method");

                    b.Property<DateTime?>("승인일시")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("approved_at");

                    b.Property<string>("의뢰Id")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("request_id");

                    b.Property<string>("화주Id")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("shipper_id");

                    b.HasKey("Id");

                    b.ToTable("결제");
                });

            modelBuilder.Entity("홍달.도메인.기사.기사근무", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<string>("기사Id")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("driver_id");

                    b.Property<string>("복귀지")
                        .HasColumnType("longtext")
                        .HasColumnName("return_destination");

                    b.Property<string>("시작모드")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("start_mode");

                    b.Property<DateTime?>("시작시각")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("started_at");

                    b.Property<string>("시작위치")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("start_location");

                    b.HasKey("Id");

                    b.ToTable("driver_shifts");
                });

            modelBuilder.Entity("홍달.도메인.기사.기사월정산", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<bool>("결제완료")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_paid");

                    b.Property<string>("기사Id")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("driver_id");

                    b.Property<int>("년도")
                        .HasColumnType("int")
                        .HasColumnName("year");

                    b.Property<int>("배차건수")
                        .HasColumnType("int")
                        .HasColumnName("dispatch_count");

                    b.Property<int>("월")
                        .HasColumnType("int")
                        .HasColumnName("month");

                    b.Property<decimal>("이용료")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("usage_fee");

                    b.HasKey("Id");

                    b.ToTable("기사월정산");
                });

            modelBuilder.Entity("홍달.도메인.기사.기사위치기록", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<decimal>("경도")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("longitude");

                    b.Property<DateTime>("기록시각")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("recorded_at");

                    b.Property<string>("기사Id")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("driver_id");

                    b.Property<decimal>("위도")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("latitude");

                    b.Property<decimal?>("정확도_m")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("accuracy_m");

                    b.HasKey("Id");

                    b.ToTable("driver_location_history");
                });

            modelBuilder.Entity("홍달.도메인.기사.배달기사", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("NotionPageId")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("notion_page_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<string>("기사Id")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("기사Id");

                    b.Property<string>("기사명")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("기사명");

                    b.Property<DateTime?>("등록일")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("등록일");

                    b.Property<string>("메모")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("메모");

                    b.Property<string>("상태")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("상태");

                    b.Property<string>("연락처")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("연락처");

                    b.Property<string>("운행상태")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("운행상태");

                    b.Property<string>("주_활동지역")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("주_활동지역");

                    b.Property<string>("차량")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("차량");

                    b.HasKey("Id");

                    b.ToTable("배달기사");
                });

            modelBuilder.Entity("홍달.도메인.기사.배차계획신청", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<string>("기사Id")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("기사Id");

                    b.Property<string>("메모")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("메모");

                    b.Property<DateTime?>("배차가능시각")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("배차가능시각");

                    b.Property<string>("복귀지")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("복귀지");

                    b.Property<string>("상태")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("상태");

                    b.Property<DateTime>("신청일시")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("신청일시");

                    b.Property<string>("출발지")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("출발지");

                    b.Property<DateTime?>("희망복귀시각")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("희망복귀시각");

                    b.HasKey("Id");

                    b.ToTable("배차계획신청");
                });

            modelBuilder.Entity("홍달.도메인.기사.용달기사", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("NotionPageId")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("notion_page_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<string>("기사Id")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("기사Id");

                    b.Property<string>("기사명")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("기사명");

                    b.Property<DateTime?>("등록일")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("등록일");

                    b.Property<string>("메모")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("메모");

                    b.Property<string>("상태")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("상태");

                    b.Property<string>("연락처")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("연락처");

                    b.Property<string>("운행상태")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("운행상태");

                    b.Property<string>("주_활동지역")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("주_활동지역");

                    b.Property<string>("차량")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("차량");

                    b.HasKey("Id");

                    b.ToTable("용달기사");
                });

            modelBuilder.Entity("홍달.도메인.배차.기사배차", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("NotionPageId")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("notion_page_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<long?>("거리추가_요금")
                        .HasColumnType("bigint")
                        .HasColumnName("거리추가_요금");

                    b.Property<long?>("기본요금")
                        .HasColumnType("bigint")
                        .HasColumnName("기본요금");

                    b.Property<long?>("기사Id")
                        .HasColumnType("bigint")
                        .HasColumnName("기사Id");

                    b.Property<string>("메모")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("메모");

                    b.Property<string>("배송지")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("배송지");

                    b.Property<long?>("배차Id")
                        .HasColumnType("bigint")
                        .HasColumnName("배차Id");

                    b.Property<string>("배차명")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("배차명");

                    b.Property<DateTime?>("배차생성시각")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("배차생성시각");

                    b.Property<DateTime?>("배차완료시각")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("배차완료시각");

                    b.Property<DateTime?>("배차일")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("배차일");

                    b.Property<decimal?>("배차점수")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("배차점수");

                    b.Property<string>("상태")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("상태");

                    b.Property<int?>("시도횟수")
                        .HasColumnType("int")
                        .HasColumnName("시도횟수");

                    b.Property<string>("실패사유")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("실패사유");

                    b.Property<long?>("용달기사_id")
                        .HasColumnType("bigint")
                        .HasColumnName("배달기사_id");

                    b.Property<DateTime?>("잠금시각")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("잠금시각");

                    b.Property<bool>("잠금여부")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("잠금여부");

                    b.Property<long?>("주문Id")
                        .HasColumnType("bigint")
                        .HasColumnName("주문Id");

                    b.Property<int?>("픽업거리_m")
                        .HasColumnType("int")
                        .HasColumnName("픽업거리_m");

                    b.Property<int?>("픽업예상시간_sec")
                        .HasColumnType("int")
                        .HasColumnName("픽업예상시간_sec");

                    b.Property<string>("픽업지")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("픽업지");

                    b.HasKey("Id");

                    b.ToTable("기사배차");
                });

            modelBuilder.Entity("홍달.도메인.배차.배차대기", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<string>("상태")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("status");

                    b.Property<string>("의뢰Id")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("request_id");

                    b.Property<decimal?>("픽업_경도")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("pickup_longitude");

                    b.Property<string>("픽업_도로명주소")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("pickup_address");

                    b.Property<string>("픽업_상세주소")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("pickup_address_detail");

                    b.Property<decimal?>("픽업_위도")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("pickup_latitude");

                    b.Property<decimal?>("하차_경도")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("dropoff_longitude");

                    b.Property<string>("하차_도로명주소")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("dropoff_address");

                    b.Property<string>("하차_상세주소")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("dropoff_address_detail");

                    b.Property<decimal?>("하차_위도")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("dropoff_latitude");

                    b.Property<string>("화주Id")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("shipper_id");

                    b.HasKey("Id");

                    b.ToTable("배차_대기");
                });

            modelBuilder.Entity("홍달.도메인.설정.Command알림Outbox", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("CommandName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("command_name");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("EventName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("event_name");

                    b.Property<string>("FeatureName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("feature_name");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("payload_json");

                    b.Property<int>("RetryCount")
                        .HasColumnType("int")
                        .HasColumnName("retry_count");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("status");

                    b.Property<string>("Target")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("target");

                    b.Property<string>("TraceId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("trace_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Status", "CreatedAt");

                    b.ToTable("Command_알림_Outbox");
                });

            modelBuilder.Entity("홍달.도메인.설정.사용자Command기능설정", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("CommandName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("command_name");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("FeatureName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("feature_name");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_enabled");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<string>("사용자Id")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("varchar(450)")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("사용자Id", "CommandName", "FeatureName")
                        .IsUnique();

                    b.ToTable("사용자_Command_기능설정");
                });

            modelBuilder.Entity("홍달.도메인.설정.사용자View설정", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AppKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("app_key");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_visible");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("varchar(450)")
                        .HasColumnName("user_id");

                    b.Property<string>("ViewKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("view_key");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "AppKey", "ViewKey")
                        .IsUnique();

                    b.ToTable("사용자_View_설정");
                });

            modelBuilder.Entity("홍달.도메인.설정.플랫폼View정책", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AppKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("app_key");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("display_name");

                    b.Property<string>("IconKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("icon_key");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_required");

                    b.Property<bool>("PolicyEnabled")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("policy_enabled");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("role_name");

                    b.Property<string>("Route")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("route");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int")
                        .HasColumnName("sort_order");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<string>("ViewKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("view_key");

                    b.HasKey("Id");

                    b.HasIndex("AppKey", "ViewKey", "RoleName")
                        .IsUnique();

                    b.ToTable("플랫폼_View_정책");
                });

            modelBuilder.Entity("홍달.도메인.업체.업체", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("NotionPageId")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("notion_page_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<string>("담당자")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("담당자");

                    b.Property<string>("대표_연락처")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("대표_연락처");

                    b.Property<DateTime?>("등록일")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("등록일");

                    b.Property<string>("메모")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("메모");

                    b.Property<string>("상태")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("상태");

                    b.Property<string>("업체명")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("업체명");

                    b.Property<string>("이메일")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("이메일");

                    b.Property<string>("정산_결제_조건")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("정산_결제_조건");

                    b.Property<string>("주소")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("주소");

                    b.Property<string>("첨부_json")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("첨부_json");

                    b.HasKey("Id");

                    b.ToTable("업체");
                });

            modelBuilder.Entity("홍달.도메인.운송.배송_운송", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<string>("기사_운송자")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("기사_운송자");

                    b.Property<DateTime?>("도착")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("도착");

                    b.Property<string>("도착지")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("도착지");

                    b.Property<string>("메모")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("메모");

                    b.Property<string>("상태")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("상태");

                    b.Property<string>("운송번호")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("운송번호");

                    b.Property<decimal?>("운임")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("운임");

                    b.Property<string>("첨부_json")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("첨부_json");

                    b.Property<DateTime?>("출발_픽업")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("출발_픽업");

                    b.Property<string>("출발지")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("출발지");

                    b.HasKey("Id");

                    b.ToTable("배송_운송");
                });

            modelBuilder.Entity("홍달.도메인.운송.운송이벤트", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("메타데이터")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("metadata");

                    b.Property<string>("의뢰Id")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("request_id");

                    b.Property<DateTime>("이벤트시각")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("event_time");

                    b.Property<string>("이벤트타입")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("event_type");

                    b.HasKey("Id");

                    b.ToTable("운송이벤트");
                });

            modelBuilder.Entity("홍달.도메인.운송.운임구성", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<decimal>("거리운임")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("거리운임");

                    b.Property<decimal>("기본운임")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("기본운임");

                    b.Property<decimal>("대기료")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("대기료");

                    b.Property<decimal>("수작업비")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("수작업비");

                    b.Property<string>("의뢰Id")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("request_id");

                    b.Property<decimal>("최종운임")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("최종운임");

                    b.Property<decimal>("할증")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("할증");

                    b.HasKey("Id");

                    b.ToTable("운임구성");
                });

            modelBuilder.Entity("홍달.도메인.운송.차량단가", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<decimal>("Km당단가")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("Km당단가");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<decimal>("기본운임")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("기본운임");

                    b.Property<decimal>("야간할증")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("야간할증");

                    b.Property<decimal>("우천할증")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("우천할증");

                    b.Property<string>("차량종류")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("차량종류");

                    b.Property<decimal>("최소운임")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("최소운임");

                    b.HasKey("Id");

                    b.ToTable("차량단가");
                });

            modelBuilder.Entity("홍달.도메인.차량.차량제원", b =>
                {
                    b.Property<string>("차량코드")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("차량코드");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<decimal?>("기준연비KmPerLiter")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("기준연비KmPerLiter");

                    b.Property<bool>("냉동가능")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("냉동가능");

                    b.Property<bool>("냉장가능")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("냉장가능");

                    b.Property<string>("단점메모")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("단점메모");

                    b.Property<bool>("리프트가능")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("리프트가능");

                    b.Property<string>("모델명")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("모델명");

                    b.Property<int?>("바닥높이Mm")
                        .HasColumnType("int")
                        .HasColumnName("바닥높이Mm");

                    b.Property<bool>("비눈보호가능")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("비눈보호가능");

                    b.Property<int?>("운영권장중량Kg")
                        .HasColumnType("int")
                        .HasColumnName("운영권장중량Kg");

                    b.Property<bool>("장재물유리")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("장재물유리");

                    b.Property<string>("장점메모")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("장점메모");

                    b.Property<int>("적재함길이Mm")
                        .HasColumnType("int")
                        .HasColumnName("적재함길이Mm");

                    b.Property<int?>("적재함높이Mm")
                        .HasColumnType("int")
                        .HasColumnName("적재함높이Mm");

                    b.Property<int>("적재함폭Mm")
                        .HasColumnType("int")
                        .HasColumnName("적재함폭Mm");

                    b.Property<string>("제조사")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("제조사");

                    b.Property<string>("차급")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("차급");

                    b.Property<string>("차량명")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("차량명");

                    b.Property<int?>("차량전체높이Mm")
                        .HasColumnType("int")
                        .HasColumnName("차량전체높이Mm");

                    b.Property<string>("차체형태")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("차체형태");

                    b.Property<int>("최대적재중량Kg")
                        .HasColumnType("int")
                        .HasColumnName("최대적재중량Kg");

                    b.Property<bool>("측면상하차가능")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("측면상하차가능");

                    b.Property<int?>("팔레트적재개수")
                        .HasColumnType("int")
                        .HasColumnName("팔레트적재개수");

                    b.HasKey("차량코드");

                    b.ToTable("차량제원");
                });

            modelBuilder.Entity("홍달.도메인.화물.화물요구조건", b =>
                {
                    b.Property<string>("의뢰Id")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("의뢰Id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<bool>("냉동필요")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("냉동필요");

                    b.Property<bool>("냉장필요")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("냉장필요");

                    b.Property<bool>("독차필수")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("독차필수");

                    b.Property<bool>("리프트필요")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("리프트필요");

                    b.Property<bool>("비맞으면안됨")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("비맞으면안됨");

                    b.Property<bool>("장재물")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("장재물");

                    b.Property<string>("주의사항")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("주의사항");

                    b.Property<bool>("측면상하차필요")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("측면상하차필요");

                    b.Property<int?>("팔레트개수")
                        .HasColumnType("int")
                        .HasColumnName("팔레트개수");

                    b.Property<bool>("혼적허용")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("혼적허용");

                    b.Property<int?>("화물길이Mm")
                        .HasColumnType("int")
                        .HasColumnName("화물길이Mm");

                    b.Property<int?>("화물높이Mm")
                        .HasColumnType("int")
                        .HasColumnName("화물높이Mm");

                    b.Property<int?>("화물무게Kg")
                        .HasColumnType("int")
                        .HasColumnName("화물무게Kg");

                    b.Property<int?>("화물폭Mm")
                        .HasColumnType("int")
                        .HasColumnName("화물폭Mm");

                    b.HasKey("의뢰Id");

                    b.ToTable("화물요구조건");
                });

            modelBuilder.Entity("홍달.도메인.화주.화주운송의뢰", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<string>("결제상태")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("payment_status");

                    b.Property<string>("결제수단")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("payment_method");

                    b.Property<int?>("결제예정금액")
                        .HasColumnType("int")
                        .HasColumnName("estimated_payment_amount");

                    b.Property<decimal?>("대기료")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("waiting_fee");

                    b.Property<string>("배차상태")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("dispatch_status");

                    b.Property<string>("상태")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("status");

                    b.Property<string>("서비스레벨")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("service_level");

                    b.Property<bool>("세금계산서필요")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("tax_invoice_required");

                    b.Property<string>("수납주체")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("collector");

                    b.Property<decimal?>("수작업비")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("manual_fee");

                    b.Property<string>("요청사항")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("request_text");

                    b.Property<string>("운송방식")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("transport_type");

                    b.Property<long?>("운임구성Id")
                        .HasColumnType("bigint")
                        .HasColumnName("pricing_config_id");

                    b.Property<string>("의뢰Id")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("request_id");

                    b.Property<DateTime?>("인수증등록일시")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("receipt_issued_at");

                    b.Property<string>("인수증번호")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("receipt_number");

                    b.Property<string>("정산메모")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("settlement_memo");

                    b.Property<string>("정산상태")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("settlement_status");

                    b.Property<string>("정산시점")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("settlement_time");

                    b.Property<string>("주문자UserId")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("orderer_user_id");

                    b.Property<string>("증빙방식")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("evidence_method");

                    b.Property<string>("차량종류")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("vehicle_type");

                    b.Property<decimal?>("최종운임")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("final_fare");

                    b.Property<string>("클라이언트요청Id")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("client_request_id");

                    b.Property<decimal?>("픽업_경도")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("pickup_longitude");

                    b.Property<string>("픽업_도로명주소")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("pickup_address");

                    b.Property<string>("픽업_상세주소")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("pickup_address_detail");

                    b.Property<DateTime>("픽업_시간창_시작일시")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("pickup_window_start");

                    b.Property<DateTime>("픽업_시간창_종료일시")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("pickup_window_end");

                    b.Property<string>("픽업_연락처_이름")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("pickup_contact_name");

                    b.Property<string>("픽업_연락처_전화번호")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("pickup_contact_phone");

                    b.Property<decimal?>("픽업_위도")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("pickup_latitude");

                    b.Property<decimal?>("하차_경도")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("dropoff_longitude");

                    b.Property<string>("하차_도로명주소")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("dropoff_address");

                    b.Property<string>("하차_상세주소")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("dropoff_address_detail");

                    b.Property<DateTime?>("하차_시간창_시작일시")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("dropoff_window_start");

                    b.Property<DateTime?>("하차_시간창_종료일시")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("dropoff_window_end");

                    b.Property<string>("하차_연락처_이름")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("dropoff_contact_name");

                    b.Property<string>("하차_연락처_전화번호")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("dropoff_contact_phone");

                    b.Property<decimal?>("하차_위도")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("dropoff_latitude");

                    b.Property<decimal?>("할증")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("surcharge");

                    b.Property<bool>("현금영수증필요")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("cash_receipt_required");

                    b.Property<DateTime?>("현장수금확인일시")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("cash_settled_at");

                    b.Property<string>("현장지급메모")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("cash_settlement_memo");

                    b.Property<int?>("화물길이Mm")
                        .HasColumnType("int")
                        .HasColumnName("cargo_length_mm");

                    b.Property<int?>("화물높이Mm")
                        .HasColumnType("int")
                        .HasColumnName("cargo_height_mm");

                    b.Property<decimal?>("화물부피Cbm")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("cargo_volume_cbm");

                    b.Property<string>("화물설명")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("cargo_description");

                    b.Property<int?>("화물수량")
                        .HasColumnType("int")
                        .HasColumnName("cargo_quantity");

                    b.Property<string>("화물온도조건")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("cargo_temperature");

                    b.Property<string>("화물종류")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("cargo_type");

                    b.Property<decimal?>("화물중량Kg")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("cargo_weight_kg");

                    b.Property<bool>("화물파손주의여부")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("cargo_fragile");

                    b.Property<int?>("화물팔레트개수")
                        .HasColumnType("int")
                        .HasColumnName("cargo_pallet_count");

                    b.Property<int?>("화물폭Mm")
                        .HasColumnType("int")
                        .HasColumnName("cargo_width_mm");

                    b.Property<string>("화주Id")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("shipper_id");

                    b.HasKey("Id");

                    b.ToTable("shipper_requests");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("홍달.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("홍달.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("홍달.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("홍달.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
