<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-android</TargetFramework>
    <SupportedOSPlatformVersion>24</SupportedOSPlatformVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <NoWarn>$(NoWarn);BG8401;BG8403;BG8501;BG8605;BG8606;BG8800;CS0114</NoWarn>
    <!--
      Enable trim analyzers for Android class libraries.
      To learn more, see: https://learn.microsoft.com/dotnet/core/deploying/trimming/prepare-libraries-for-trimming
    -->
    <IsTrimmable>true</IsTrimmable>
    <!--
      NOTE: you can simply add .aar or .jar files in this directory to be included in the project.
      To learn more, see: https://learn.microsoft.com/dotnet/maui/migration/android-binding-projects
    -->
  </PropertyGroup>

  <ItemGroup>
    <AndroidMavenLibrary Include="com.naver.maps:map-sdk"
                         Version="3.23.2"
                         Repository="https://repository.map.naver.com/archive/maven"
                         VerifyDependencies="false" />
    <AndroidMavenLibrary Include="com.naver.maps:geometry"
                         Version="1.3.0"
                         Repository="https://repository.map.naver.com/archive/maven"
                         VerifyDependencies="false" />
    <AndroidMavenLibrary Include="com.getkeepsafe.relinker:relinker"
                         Version="1.4.4"
                         Bind="false"
                         VerifyDependencies="false" />
    <AndroidMavenLibrary Include="com.squareup.okhttp3:okhttp"
                         Version="4.10.0"
                         Bind="false"
                         VerifyDependencies="false" />
    <AndroidMavenLibrary Include="com.squareup.okhttp3:okhttp-brotli"
                         Version="4.10.0"
                         Bind="false"
                         VerifyDependencies="false" />
    <AndroidMavenLibrary Include="com.squareup.okio:okio-jvm"
                         Version="3.0.0"
                         Bind="false"
                         VerifyDependencies="false" />
    <AndroidMavenLibrary Include="org.brotli:dec"
                         Version="0.1.2"
                         Bind="false"
                         VerifyDependencies="false" />
  </ItemGroup>
</Project>
