services:
  app:
    environment:
      SsalddelExecution__Mode: Operational
      VersionFeatureFlags__FoodDeliveryWorkflow: "true"
      VersionFeatureFlags__SsalddelMartWorkflow: "true"
      SalesChannelOrderSync__Enabled: "true"
