namespace Ssalddel.Contracts.Common.Content;

public static class YouTube음식채널분류코드
{
    public const string 상품리뷰 = "ProductReview";
    public const string 요리재료 = "CookingIngredient";
    public const string 음식여행 = "FoodTravel";
    public const string 길거리음식 = "StreetFood";
    public const string 먹방 = "Mukbang";
    public const string 육류수산 = "MeatSeafood";
    public const string 세계음식 = "GlobalCuisine";
    public const string 식품산업 = "FoodIndustry";

    public static IReadOnlySet<string> 전체 { get; } = new HashSet<string>(StringComparer.Ordinal)
    {
        상품리뷰,
        요리재료,
        음식여행,
        길거리음식,
        먹방,
        육류수산,
        세계음식,
        식품산업
    };
}

public sealed record YouTube음식채널조사항목(
    string ChannelId,
    string Handle,
    string 채널명,
    string 국가코드,
    string 기본언어코드,
    IReadOnlyList<string> 분류코드목록,
    int 구매발견점수,
    int 수입발견점수,
    string 조사메모,
    string 공식채널Url,
    DateTime 조사확인일시Utc);

/// <summary>
/// 음식 상품 발견 가능성을 기준으로 1차 선별한 운영 시작용 카탈로그입니다.
/// 전체 YouTube 채널의 완전한 목록이 아니며, API 검색과 관리자 검수로 계속 확장합니다.
/// 구독자 수처럼 자주 변하는 수치는 의도적으로 저장하지 않습니다.
/// </summary>
public static class YouTube음식채널조사Catalog
{
    private static readonly DateTime 확인일시Utc =
        new(2026, 7, 17, 0, 0, 0, DateTimeKind.Utc);

    private static readonly DateTime 일본지역음식확인일시Utc =
        new(2026, 7, 24, 0, 0, 0, DateTimeKind.Utc);

    private static readonly DateTime 한미일음식전수조사확인일시Utc =
        new(2026, 7, 24, 0, 0, 0, DateTimeKind.Utc);

    public static IReadOnlyList<YouTube음식채널조사항목> 항목 { get; } =
    [
        C("UCfpaSruWW3S4dibonKXENjA", "@tzuyang6145", "tzuyang쯔양", YouTube채널수집국가코드.한국, "ko",
            [YouTube음식채널분류코드.먹방, YouTube음식채널분류코드.상품리뷰], 88, 45,
            "대용량 먹방과 식당·메뉴 탐방에서 국내 구매 수요를 발견하기 좋은 채널"),
        C("UCyn-K7rZLXjGl7VXGweIlcA", "@paik_jongwon", "백종원 PAIK JONG WON", "KR", "ko",
            [YouTube음식채널분류코드.요리재료, YouTube음식채널분류코드.식품산업], 92, 68,
            "조리법, 식재료, 외식업 정보를 함께 다뤄 상품화 후보를 찾기 좋은 채널"),
        C("UCl23-Cci_SMqyGXE1T_LYUg", "@sungsikyung", "성시경 SUNG SI KYUNG", "KR", "ko",
            [YouTube음식채널분류코드.음식여행, YouTube음식채널분류코드.요리재료], 82, 48,
            "국내외 식당과 조리 콘텐츠에서 메뉴·재료 수요를 관찰할 수 있는 채널"),
        C("UC0VR2v4TZeGcOrZHnmwbU_Q", "@yooxicman", "육식맨 YOOXICMAN", "KR", "ko",
            [YouTube음식채널분류코드.육류수산, YouTube음식채널분류코드.요리재료], 94, 88,
            "해외 육류·조리도구·소스 소개가 많아 구매와 수입 검토 연결성이 높은 채널"),
        C("UC1oXmhvYHVI2bApphh3IzuQ", "@meatcreator", "정육왕 MeatCreator", "KR", "ko",
            [YouTube음식채널분류코드.육류수산, YouTube음식채널분류코드.식품산업], 91, 82,
            "정육·육류 산지와 유통 정보를 다뤄 공급처 및 수입 후보 조사에 적합한 채널"),
        C("UCg-p3lQIqmhh7gHpyaOmOiQ", "@koreanenglishman", "영국남자 Korean Englishman", "KR", "ko",
            [YouTube음식채널분류코드.세계음식, YouTube음식채널분류코드.상품리뷰], 86, 70,
            "한국과 해외 식품의 교차 체험을 통해 역직구·수입 관심을 확인하기 좋은 채널"),
        C("UC8gFadPgK2r1ndqLI04Xvvw", "@maangchi", "Maangchi", "US", "en",
            [YouTube음식채널분류코드.요리재료, YouTube음식채널분류코드.세계음식], 90, 84,
            "영어권 한국 식재료 수요와 해외 유통 가능성을 살펴보기 좋은 채널"),
        C("UC5qRAYQmCLx8hFGIiTWSQvA", "@aaronandclaire", "Aaron and Claire", "US", "en",
            [YouTube음식채널분류코드.요리재료, YouTube음식채널분류코드.세계음식], 88, 82,
            "쉽게 구하는 한국 식재료와 대체재를 설명해 해외 구매 수요 탐색에 적합한 채널"),
        C("UCh8gHdtzO2tXd593_bjErWg", "@doobydobap", "Doobydobap", "US", "en",
            [YouTube음식채널분류코드.세계음식, YouTube음식채널분류코드.음식여행], 82, 72,
            "한식과 세계 음식 스토리에서 재료·식문화 기반 상품 후보를 찾을 수 있는 채널"),
        C("UCIvA9ZGeoR6CH2e0DZtvxzw", "@seonkyounglongest", "Seonkyoung Longest", "US", "en",
            [YouTube음식채널분류코드.요리재료, YouTube음식채널분류코드.세계음식], 87, 82,
            "아시아 조리법과 식재료 비중이 높아 해외 상품·소스 수요 탐색에 적합한 채널"),
        C("UC-SmuIHMG2HPDFUOBRu5LnA", "@futureneighbor", "Future Neighbor", "KR", "en",
            [YouTube음식채널분류코드.요리재료, YouTube음식채널분류코드.세계음식], 84, 78,
            "영어권 시청자를 위한 한국 장보기·조리 정보에서 수출입 후보를 찾기 좋은 채널"),
        C("UCdn6TcAo99RtH-FwIgKBXUA", "@thekoreanvegan", "The Korean Vegan", "US", "en",
            [YouTube음식채널분류코드.요리재료, YouTube음식채널분류코드.세계음식], 80, 75,
            "비건 한식 재료와 대체 식품의 틈새 구매 수요를 조사하기 좋은 채널"),
        C("UCe1ZsGtbRx2pgajGzwB9L0A", "@foodieboykr", "FoodieBoy 푸디보이", "KR", "ko",
            [YouTube음식채널분류코드.길거리음식, YouTube음식채널분류코드.식품산업], 83, 46,
            "조리 현장과 길거리 음식 영상에서 완제품·장비·공급자 후보를 찾기 좋은 채널"),
        C("UCiiV8stcewhoCNyiErr7GtA", "@yummyboys", "야미보이 Yummyboy", "KR", "ko",
            [YouTube음식채널분류코드.길거리음식, YouTube음식채널분류코드.식품산업], 82, 45,
            "대량 조리와 시장 음식 현장을 통해 식품·장비 구매 후보를 찾을 수 있는 채널"),
        C("UC1r112Pr9Ngcg2NtcE946HQ", "@matsangmu", "맛상무", "KR", "ko",
            [YouTube음식채널분류코드.상품리뷰, YouTube음식채널분류코드.먹방], 90, 66,
            "신제품과 간편식 비교·리뷰가 많아 구매 의향 수집에 직접 연결하기 좋은 채널"),
        C("UC-Bsa2ivAGWq7bsSPrPGFVA", "@short_mouth_sun", "입짧은햇님", "KR", "ko",
            [YouTube음식채널분류코드.먹방, YouTube음식채널분류코드.상품리뷰], 84, 43,
            "배달·간편식·외식 메뉴 반응을 통해 국내 공동구매 관심을 관찰하기 좋은 채널"),
        C("UCdz7HcTQOaHCoAEJBs-MlNQ", "@jjinfood", "찐푸드 JJin Food", "KR", "ko",
            [YouTube음식채널분류코드.길거리음식, YouTube음식채널분류코드.식품산업], 82, 45,
            "지역 음식점의 대량 조리와 생산 현장을 기록해 식품·장비·공급자 후보를 찾기 좋은 채널",
            한미일음식전수조사확인일시Utc),
        C("UCa0aTySoJBHXpHigv5tsxbQ", "@seagullfood", "끼룩푸드 seagull food", "KR", "ko",
            [YouTube음식채널분류코드.길거리음식, YouTube음식채널분류코드.식품산업], 81, 44,
            "전국 길거리 음식과 조리 현장을 다뤄 지역별 완제품·외식 재료 후보를 보완하기 좋은 채널",
            한미일음식전수조사확인일시Utc),
        C("UCtaBL35pjhdJyCbA7tECN8g", "@travelfood2981", "트래블 푸드Travel Food", "KR", "ko",
            [YouTube음식채널분류코드.음식여행, YouTube음식채널분류코드.길거리음식], 83, 49,
            "전통시장과 지역 식당의 조리 과정을 기록해 국내 지역 음식 후보를 찾기 좋은 채널",
            한미일음식전수조사확인일시Utc),
        C("UC5oft5dVf43M2cFmhpJLVGQ", "@참", "애주가TV참PD", "KR", "ko",
            [YouTube음식채널분류코드.상품리뷰, YouTube음식채널분류코드.먹방], 91, 72,
            "가공식품·주류 안주·신제품 비교가 많아 구매 수요와 수입 완제품 후보를 찾기 좋은 채널",
            한미일음식전수조사확인일시Utc),
        C("UCL01un1rw1MU3wj7-oEELQQ", "@50food", "[윤이련]50년 요리비결", "KR", "ko",
            [YouTube음식채널분류코드.요리재료, YouTube음식채널분류코드.세계음식], 87, 60,
            "전통 한식과 저장 음식 조리법에서 국내 재료와 해외 대체재 후보를 확인하기 좋은 채널",
            한미일음식전수조사확인일시Utc),
        C("UC5T4b53jVkm07JbYoyYiu7A", "@흑백리뷰", "흑백리뷰", "KR", "ko",
            [YouTube음식채널분류코드.상품리뷰, YouTube음식채널분류코드.먹방], 92, 74,
            "국내외 가공식품과 외식 신제품을 짧게 비교해 공동구매 관심 후보를 빠르게 찾기 좋은 채널",
            한미일음식전수조사확인일시Utc),
        C("UCy2WX3w5UyYFHBDHyWFKNUQ", "@cook5162", "이 남자의 cook", "KR", "ko",
            [YouTube음식채널분류코드.요리재료, YouTube음식채널분류코드.상품리뷰], 88, 58,
            "가정식과 계절 음식 조리법을 꾸준히 다뤄 반복 구매 식재료 후보를 찾기 좋은 채널",
            한미일음식전수조사확인일시Utc),
        C("UC1Wq-BQZblFGbGgDAoCwrmA", "@koreanfood99", "한식푸우 Korean food", "KR", "ko",
            [YouTube음식채널분류코드.먹방, YouTube음식채널분류코드.상품리뷰], 79, 42,
            "한식·배달음식·외식 메뉴 반응을 통해 국내 소비 관심을 보조 관찰하기 좋은 채널",
            한미일음식전수조사확인일시Utc),
        C("UCVYWNpj0WskPy5rLL8uzHBg", "@subuhae", "수부해TV subuhae", "KR", "ko",
            [YouTube음식채널분류코드.육류수산, YouTube음식채널분류코드.요리재료], 88, 68,
            "제철 수산물 손질·조리와 구매 정보를 다뤄 수산 식재료 후보를 찾기 좋은 채널",
            한미일음식전수조사확인일시Utc),
        C("UC2dDb6up1sIc-5geTvNtgHA", "@ebs_best.cooking.secrets", "EBS 최고의 요리비결", "KR", "ko",
            [YouTube음식채널분류코드.요리재료, YouTube음식채널분류코드.식품산업], 83, 55,
            "전문가 조리법과 재료 활용을 제공해 독립 제작자 후보를 교차검증하기 좋은 공식 방송 채널",
            한미일음식전수조사확인일시Utc),
        C("UCyEd6QBSgat5kkC6svyjudA", "@markwiens", "Mark Wiens", "US", "en",
            [YouTube음식채널분류코드.음식여행, YouTube음식채널분류코드.세계음식], 85, 91,
            "세계 각지 음식과 현지 식재료 노출이 많아 수입 조사 후보가 풍부한 채널"),
        C("UCcAd5Np7fO8SeejB1FVKcYw", "@besteverfoodreviewshow", "Best Ever Food Review Show", "US", "en",
            [YouTube음식채널분류코드.음식여행, YouTube음식채널분류코드.세계음식], 84, 92,
            "여러 국가의 희소 식품과 생산 문화를 다뤄 수입 가능성 조사에 적합한 채널"),
        C("UCXOKEdfOFxsHO_-Su3K8SHg", "@strictlydumpling", "Strictly Dumpling", "US", "en",
            [YouTube음식채널분류코드.음식여행, YouTube음식채널분류코드.상품리뷰], 86, 86,
            "여행 음식과 식품 구매 리뷰를 함께 다뤄 제품 단위 후보 발굴에 적합한 채널"),
        C("UCRFj4Yj1nKhgrT-_8AUsaDg", "@dancingbacons", "DancingBacons", "SG", "en",
            [YouTube음식채널분류코드.길거리음식, YouTube음식채널분류코드.상품리뷰], 84, 88,
            "아시아 편의점·자판기·시장 식품 노출이 많아 수입 완제품 후보가 풍부한 채널"),
        C("UCiAq_SU0ED1C6vWFMnw8Ekg", "@thefoodranger", "The Food Ranger", "AE", "en",
            [YouTube음식채널분류코드.음식여행, YouTube음식채널분류코드.길거리음식], 82, 89,
            "지역별 시장 음식과 식재료를 폭넓게 다뤄 해외 공급 후보 조사에 적합한 채널"),
        C("UCbPHHOiOY_tA9BSytK0jDYw", "@berylshereshewsky", "Beryl Shereshewsky", "US", "en",
            [YouTube음식채널분류코드.세계음식, YouTube음식채널분류코드.요리재료], 88, 94,
            "각국 시청자와 음식을 교류해 국가별 식품·재료 수요를 발견하기 좋은 채널"),
        C("UCzqbfYjQmf9nLQPMxVgPhiA", "@emmymade", "emmymade", "US", "en",
            [YouTube음식채널분류코드.상품리뷰, YouTube음식채널분류코드.세계음식], 90, 90,
            "세계 간식·특이 식품 리뷰가 많아 완제품 구매와 수입 후보 발굴에 적합한 채널"),
        C("UC54SLBnD5k5U3Q6N__UjbAw", "@chinesecookingdemystified", "Chinese Cooking Demystified", "CN", "en",
            [YouTube음식채널분류코드.요리재료, YouTube음식채널분류코드.세계음식], 86, 91,
            "중국 조리법과 전문 식재료를 자세히 설명해 식재료 수입 검토에 적합한 채널"),
        C("UCWj_rUMGYCP0DjffybE2nbg", "@middleeats", "Middle Eats", "GB", "en",
            [YouTube음식채널분류코드.요리재료, YouTube음식채널분류코드.세계음식], 84, 89,
            "중동 조리법과 향신료·가공품 정보를 통해 틈새 수입 후보를 찾기 좋은 채널"),
        C("UCfyehHM_eo4g5JUyWmms2LA", "@sortedfood", "Sorted Food", "GB", "en",
            [YouTube음식채널분류코드.상품리뷰, YouTube음식채널분류코드.요리재료], 90, 80,
            "식품·주방용품 비교와 조리 실험이 많아 구매 전환 후보를 찾기 좋은 채널"),
        C("UCwiTOchWeKjrJZw7S1H__1g", "@insiderfood", "Insider Food", "US", "en",
            [YouTube음식채널분류코드.식품산업, YouTube음식채널분류코드.음식여행], 82, 84,
            "식품 생산·가격·산업 배경을 다뤄 공급망과 상품성 검토에 도움이 되는 채널"),
        C("UCRzPUBhXUZHclB7B5bURFXw", "@eater", "Eater", "US", "en",
            [YouTube음식채널분류코드.식품산업, YouTube음식채널분류코드.음식여행], 80, 82,
            "외식 산업과 생산 현장을 다뤄 식품·공급자 후보 발굴에 도움이 되는 채널"),
        C("UCMyOj6fhvKFMjxUCp3b_3gA", "@nickdigiovanni", "Nick DiGiovanni", "US", "en",
            [YouTube음식채널분류코드.요리재료, YouTube음식채널분류코드.세계음식], 90, 75,
            "세계 음식 조리와 식재료 비교를 대중적으로 다뤄 구매 후보를 넓히기 좋은 채널",
            한미일음식전수조사확인일시Utc),
        C("UCJFp8uSYCjXOMnkUyb3CQ3Q", "@buzzfeedtasty", "Tasty", "US", "en",
            [YouTube음식채널분류코드.요리재료, YouTube음식채널분류코드.세계음식], 86, 75,
            "여러 문화권의 조리법과 가공식품 활용을 폭넓게 다뤄 재료 후보를 찾기 좋은 채널",
            한미일음식전수조사확인일시Utc),
        C("UCfE5Cz44GlZVyoaYTHJbuZw", "@gugafoods", "Guga Foods", "US", "en",
            [YouTube음식채널분류코드.육류수산, YouTube음식채널분류코드.요리재료], 94, 86,
            "육류 부위·숙성·조리 실험 비중이 높아 고기와 조리도구 수입 후보를 찾기 좋은 채널",
            한미일음식전수조사확인일시Utc),
        C("UCsaGKqPZnGp_7N80hcHySGQ", "@tastinghistory", "Tasting History with Max Miller", "US", "en",
            [YouTube음식채널분류코드.세계음식, YouTube음식채널분류코드.요리재료], 80, 82,
            "역사적 조리법과 식재료의 문화 배경을 다뤄 지역 음식 후보의 맥락을 검증하기 좋은 채널",
            한미일음식전수조사확인일시Utc),
        C("UClrMJRlvoyoWsVlB-7c61PQ", "@cowboykentrollins", "Cowboy Kent Rollins", "US", "en",
            [YouTube음식채널분류코드.요리재료, YouTube음식채널분류코드.육류수산], 89, 76,
            "미국 남서부·카우보이 조리와 BBQ를 다뤄 지역 식재료와 장비 후보를 찾기 좋은 채널",
            한미일음식전수조사확인일시Utc),
        C("UCxr2d4As312LulcajAkKJYw", "@townsends", "Townsends", "US", "en",
            [YouTube음식채널분류코드.세계음식, YouTube음식채널분류코드.식품산업], 76, 78,
            "미국 초기 식문화와 보존·조리 방식을 재현해 전통 재료와 식품문화 맥락을 확인하기 좋은 채널",
            한미일음식전수조사확인일시Utc),
        C("UC8hI77bH0VraIw6p2PHwivQ", "@missminaoh", "Miss Mina", "US", "en",
            [YouTube음식채널분류코드.음식여행, YouTube음식채널분류코드.상품리뷰], 82, 80,
            "미국 도시와 해외 지역 음식 여행을 다루며 협찬 표기를 함께 검토해 상품 후보를 찾기 좋은 채널",
            한미일음식전수조사확인일시Utc),
        C("UCDq5v10l4wkV5-ZBIJJFbzQ", "@ethanchlebowski", "Ethan Chlebowski", "US", "en",
            [YouTube음식채널분류코드.요리재료, YouTube음식채널분류코드.식품산업], 90, 80,
            "맛·가격·조리과학을 비교해 식재료의 상품성과 대체 가능성을 검토하기 좋은 채널",
            한미일음식전수조사확인일시Utc),
        C("UCPjkdaqksNWgA63aZfQ2bAQ", "@meatchurchbbq", "Meat Church BBQ", "US", "en",
            [YouTube음식채널분류코드.육류수산, YouTube음식채널분류코드.요리재료], 93, 78,
            "미국 BBQ 육류·시즈닝·그릴 활용을 다뤄 식재료와 장비 구매 후보를 찾기 좋은 채널",
            한미일음식전수조사확인일시Utc),
        C("UCtXJc0pAZRPnmsgrHkgietQ", "@americasbestrestaurants", "America's Best Restaurants Roadshow", "US", "en",
            [YouTube음식채널분류코드.음식여행, YouTube음식채널분류코드.식품산업], 78, 60,
            "미국 각지의 독립 식당과 지역 메뉴를 폭넓게 기록해 주별 음식 후보를 찾기 좋은 채널",
            한미일음식전수조사확인일시Utc),
        C("UC6Je3-ZV_x38NqQAxKiCCyQ", "@tabieats", "TabiEats", "JP", "en",
            [YouTube음식채널분류코드.상품리뷰, YouTube음식채널분류코드.음식여행], 88, 92,
            "일본 편의점·지역 식품 리뷰가 많아 국내 구매대행·수입 후보 발굴에 적합한 채널"),
        C("UCW01sMEVYQdhcvkrhbxdBpw", "@ryuji825", "料理研究家リュウジのバズレシピ", "JP", "ja",
            [YouTube음식채널분류코드.상품리뷰, YouTube음식채널분류코드.요리재료], 92, 78,
            "일본 가공식품 리뷰와 일상 조리법을 함께 다뤄 제품·조미료 후보를 찾기 좋은 채널",
            한미일음식전수조사확인일시Utc),
        C("UC3p5OTQsMEnmZktWUkw_Y0A", "@kohkentetsukitchen", "Koh Kentetsu Kitchen", "JP", "ja",
            [YouTube음식채널분류코드.요리재료, YouTube음식채널분류코드.세계음식], 90, 66,
            "일본 가정식과 계절 재료 조리법을 꾸준히 다뤄 반복 구매 식재료 후보를 찾기 좋은 채널",
            한미일음식전수조사확인일시Utc),
        C("UC7LT6gRahCIBd5AO5MUl8dQ", "@yukariskitchen3689", "料理研究家ゆかりのおうちで簡単レシピ", "JP", "ja",
            [YouTube음식채널분류코드.요리재료, YouTube음식채널분류코드.세계음식], 89, 62,
            "오키나와 음식 등 지역·계절 조리법을 포함해 일본 가정식 재료 후보를 찾기 좋은 채널",
            한미일음식전수조사확인일시Utc),
        C("UCLcqrpFhRlJnm6etuLQblWg", "@sanpiryoron", "【賛否両論】笠原将弘の料理のほそ道", "JP", "ja",
            [YouTube음식채널분류코드.요리재료, YouTube음식채널분류코드.식품산업], 87, 64,
            "전문 요리사의 일본식 조리법과 제철 재료 활용을 교차검증하기 좋은 채널",
            한미일음식전수조사확인일시Utc),
        C("UC8QheEuZR6-D_FG2ElItg4A", "@sabakeru", "YouTube「さばけるチャンネル」", "JP", "ja",
            [YouTube음식채널분류코드.육류수산, YouTube음식채널분류코드.식품산업], 86, 75,
            "일본 어종별 손질법을 축적해 수산물 명칭·유통·가공 후보를 확인하기 좋은 채널",
            한미일음식전수조사확인일시Utc),
        C("UCIYEAW57AFqhkmKTbZgNvBg", "@fisherman_japan", "漁師ちゃんねる Japanese Fisherman", "JP", "ja",
            [YouTube음식채널분류코드.육류수산, YouTube음식채널분류코드.식품산업], 84, 72,
            "어업 현장과 선상 식사를 기록해 일본 수산 생산·식재료 후보를 찾기 좋은 채널",
            한미일음식전수조사확인일시Utc),
        C("UCEZmRQKOgb30U0C44bn02UQ", "@japaneseculinaryacademy91", "【公式】日本料理アカデミー", "JP", "ja",
            [YouTube음식채널분류코드.요리재료, YouTube음식채널분류코드.식품산업], 74, 70,
            "일본요리 전문기관의 공개 자료로 독립 채널의 조리법·용어를 교차검증하기 좋은 채널",
            한미일음식전수조사확인일시Utc),
        C("UCz7LrNt_1IwEA56mga66zRg", "@sugoumajapanfood", "SugoUma Japan - Japanese Food", "JP", "ja",
            [YouTube음식채널분류코드.식품산업, YouTube음식채널분류코드.음식여행], 83, 86,
            "가쓰오부시·참치 해체 등 일본 식품 생산자와 전문 공정을 기록해 공급 후보를 찾기 좋은 채널",
            한미일음식전수조사확인일시Utc),
        C("UCeuwh_a6nJtpwdFGorLw8iw", "@solo_eats", "休日ひとりグルメ旅", "JP", "ja",
            [YouTube음식채널분류코드.음식여행, YouTube음식채널분류코드.상품리뷰], 78, 70,
            "후쿠이·요코하마·하코네 등 지역별 혼자 식도락 여행으로 현지 음식 후보를 보완하기 좋은 채널",
            한미일음식전수조사확인일시Utc),
        C("UCHSLXbWZq-aU2CZ3_1aBdYQ", "@meshitabi-hokkaido", "メシ時々旅〜北海道〜", "JP", "ja",
            [YouTube음식채널분류코드.음식여행, YouTube음식채널분류코드.상품리뷰], 78, 68,
            "홋카이도 도시·마을의 음식점과 지역 여행을 꾸준히 기록해 북부 지역 후보를 보완하기 좋은 채널",
            한미일음식전수조사확인일시Utc),
        C("UCr51sMBkp4u94sZaPEwKr3g", "@kyushufood", "たか / 九州グルメ旅", "JP", "ja",
            [YouTube음식채널분류코드.음식여행, YouTube음식채널분류코드.상품리뷰], 78, 68,
            "사가·구마모토 등 규슈 지역 음식과 숙박 식사를 기록해 남부 지역 후보를 보완하기 좋은 채널",
            한미일음식전수조사확인일시Utc),
        C("UCbqmY-Ng-Pg8JXOnNl37TZg", "@machikosolotrip", "孤独のまちこ・ひとり旅", "JP", "ja",
            [YouTube음식채널분류코드.음식여행, YouTube음식채널분류코드.상품리뷰], 77, 67,
            "나가사키·나고야 등 지역별 혼자 여행과 현지 음식을 기록해 도도부현 후보를 보완하기 좋은 채널",
            한미일음식전수조사확인일시Utc),
        C("UCL_ZYXcb07HM4wobK58PcEA", "@shiyago", "しやごちゃんねる＠グルメ旅", "JP", "ja",
            [YouTube음식채널분류코드.음식여행, YouTube음식채널분류코드.길거리음식], 84, 74,
            "일본 각지의 향토 음식과 식당을 실제 방문해 먹고 마시는 기록이 많아 도도부현별 음식 후보를 찾기 좋은 채널",
            일본지역음식확인일시Utc),
        C("UCXxYVUTiVq-_RDNt5VPGGug", "@marutto_tabi", "日本列島まるっと旅", "JP", "ja",
            [YouTube음식채널분류코드.음식여행, YouTube음식채널분류코드.요리재료], 82, 76,
            "유명 관광지뿐 아니라 지방도시를 방문해 현지 추천 음식과 식재료를 소개하므로 지역 특산물 근거 후보가 풍부한 채널",
            일본지역음식확인일시Utc),
        C("UCYuVuLCtgrkQ6znA_ShdvXA", "@boutacchan", "たっちゃんねる", "JP", "ja",
            [YouTube음식채널분류코드.음식여행, YouTube음식채널분류코드.먹방], 78, 64,
            "히로시마·다카마쓰·나가사키·홋카이도 등 지역별 혼자 여행과 음식점 방문 기록을 도도부현 음식 탐색에 활용할 수 있는 채널",
            일본지역음식확인일시Utc),
        C("UCfNVLQ0xYJyjHVEdlOyuHcQ", "@morrytravel", "もーりーチャンネル【大人の穴場旅行】", "JP", "ja",
            [YouTube음식채널분류코드.음식여행, YouTube음식채널분류코드.세계음식], 72, 58,
            "47개 도도부현과 여러 섬을 실제 여행하며 지역 음식도 다루어 대도시 밖의 지역 후보를 보완하기 좋은 채널",
            일본지역음식확인일시Utc),
        C("UCHL9bfHTxCMi-7vfxQ-AYtg", "@AbroadinJapan", "Abroad in Japan", "JP", "en",
            [YouTube음식채널분류코드.음식여행, YouTube음식채널분류코드.세계음식], 80, 78,
            "도호쿠를 비롯한 일본 여러 지역의 음식·문화·여행을 영어로 소개해 해외 관심과 지역 문맥을 함께 관찰하기 좋은 채널",
            일본지역음식확인일시Utc)
    ];

    public static YouTube음식채널조사항목? 찾기(string channelId)
        => 항목.FirstOrDefault(item => string.Equals(item.ChannelId, channelId, StringComparison.Ordinal));

    private static YouTube음식채널조사항목 C(
        string channelId,
        string handle,
        string 채널명,
        string 국가코드,
        string 기본언어코드,
        IReadOnlyList<string> 분류코드목록,
        int 구매발견점수,
        int 수입발견점수,
        string 조사메모,
        DateTime? 조사확인일시Utc = null)
        => new(
            channelId,
            handle,
            채널명,
            YouTube채널수집국가코드.정규화(국가코드),
            기본언어코드,
            분류코드목록,
            구매발견점수,
            수입발견점수,
            조사메모,
            $"https://www.youtube.com/{handle}",
            조사확인일시Utc ?? 확인일시Utc);
}
