// <auto-generated />
#nullable enable
using System;
using System.Collections.Generic;

namespace Ssalddel.Simulation.Contracts
{
    public sealed class SimulationWI실행우선순위Definition
    {
        public SimulationWI실행우선순위Definition(string worldInteractionId,
            string 실행파동Code, int 파동내순서, string 완결역할Code,
            string 개발작업상태Code, string npcE8정책Code,
            string synty활용TrackCode, string[] 폐루프StableIds)
        {
            WorldInteractionId = worldInteractionId;
            this.실행파동Code = 실행파동Code;
            this.파동내순서 = 파동내순서;
            this.완결역할Code = 완결역할Code;
            this.개발작업상태Code = 개발작업상태Code;
            this.NpcE8정책Code = npcE8정책Code;
            this.Synty활용TrackCode = synty활용TrackCode;
            this.폐루프StableIds = 폐루프StableIds;
        }
        public string WorldInteractionId { get; }
        public string 실행파동Code { get; }
        public int 파동내순서 { get; }
        public string 완결역할Code { get; }
        public string 개발작업상태Code { get; }
        public string NpcE8정책Code { get; }
        public string Synty활용TrackCode { get; }
        public string[] 폐루프StableIds { get; }
        public string 목표EvidenceStage => "E7";
    }

    public static class SimulationWI실행우선순위Catalog
    {
        public const string Revision = "world-interaction-delivery-priorities.r40";
        [Obsolete("대표 표시 호환 값입니다. 실행 판단은 ActiveWorldInteractionIds를 사용하세요.")]
        public const string ActiveWorldInteractionId = "WI-WORLD-RESOURCE-REGENERATE";
        public const string ActiveEvidenceStage = "E1";
        [Obsolete("구형 호환 값이며 실행 제한이 아닙니다. MaximumConcurrentWorkItems를 사용하세요.")]
        public const int WorkInProgressLimit = 1;
        public static int? MaximumConcurrentWorkItems => null;
        public const string ConcurrencyModeCode = "DependencyAndOwnership";
        public static IReadOnlyList<string> ActiveWorldInteractionIds { get; } = Array.AsReadOnly(new string[] { "WI-ACTOR-03", "WI-COMMUNITY-VISITOR-STAY", "WI-FARM-01", "WI-WORLD-RESOURCE-REGENERATE" });
        public static bool IsActiveWorldInteraction(string worldInteractionId)
        {
            foreach (var id in ActiveWorldInteractionIds)
                if (string.Equals(id, worldInteractionId, StringComparison.Ordinal)) return true;
            return false;
        }
        private static readonly SimulationWI실행우선순위Definition[] 항목들 =
        {
            new SimulationWI실행우선순위Definition("WI-ACTOR-01", "D1", 1, "Core", "Queued", "Conditional", "Shared", new[] { "playable-loop:nature-shelter-foundation.v1" }),
            new SimulationWI실행우선순위Definition("WI-ACTOR-02", "D1", 2, "Core", "Queued", "Conditional", "Shared", new[] { "playable-loop:nature-shelter-foundation.v1" }),
            new SimulationWI실행우선순위Definition("WI-NATURE-05", "D1", 3, "Core", "E7Closed", "NotApplicable", "Nature", new[] { "playable-loop:nature-shelter-foundation.v1", "playable-loop:nature-tactical-self-navigation.v1" }),
            new SimulationWI실행우선순위Definition("WI-NATURE-06", "D1", 4, "Core", "Queued", "NotApplicable", "Nature", new[] { "playable-loop:nature-shelter-foundation.v1" }),
            new SimulationWI실행우선순위Definition("WI-NATURE-07", "D1", 5, "Core", "Queued", "NotApplicable", "Construction", new[] { "playable-loop:nature-shelter-foundation.v1" }),
            new SimulationWI실행우선순위Definition("WI-NATURE-08", "D1", 6, "Core", "Queued", "NotApplicable", "Construction", new[] { "playable-loop:nature-shelter-foundation.v1" }),
            new SimulationWI실행우선순위Definition("WI-NATURE-12", "D1", 7, "Core", "Queued", "NotApplicable", "Construction", new[] { "playable-loop:nature-shelter-foundation.v1" }),
            new SimulationWI실행우선순위Definition("WI-NATURE-09", "D1", 8, "Core", "Queued", "NotApplicable", "Nature", new[] { "playable-loop:nature-shelter-foundation.v1" }),
            new SimulationWI실행우선순위Definition("WI-NATURE-10", "D1", 9, "Core", "Queued", "NotApplicable", "Nature", new[] { "playable-loop:nature-shelter-foundation.v1" }),
            new SimulationWI실행우선순위Definition("WI-NATURE-01", "D1", 10, "Core", "E7Closed", "NotApplicable", "Nature", new[] { "playable-loop:nature-twilight-return.v1" }),
            new SimulationWI실행우선순위Definition("WI-NATURE-11", "D1", 11, "Core", "E7Closed", "NotApplicable", "Nature", new[] { "playable-loop:nature-twilight-return.v1" }),
            new SimulationWI실행우선순위Definition("WI-NATURE-02", "D1", 12, "Extension", "Queued", "NotApplicable", "Nature", new[] { "playable-loop:nature-regional-threat-recovery.v1" }),
            new SimulationWI실행우선순위Definition("WI-NATURE-03", "D1", 13, "Extension", "Queued", "NotApplicable", "Nature", new[] { "playable-loop:nature-regional-threat-recovery.v1" }),
            new SimulationWI실행우선순위Definition("WI-NATURE-04", "D1", 14, "Extension", "Queued", "NotApplicable", "Nature", new[] { "playable-loop:nature-regional-threat-recovery.v1" }),
            new SimulationWI실행우선순위Definition("WI-NATURE-13", "D1", 15, "Core", "E7Closed", "NotApplicable", "Nature", new[] { "playable-loop:nature-night-day2.v1" }),
            new SimulationWI실행우선순위Definition("WI-NATURE-14", "D1", 16, "Core", "Queued", "NotApplicable", "Nature", new[] { "playable-loop:nature-night-day2.v1" }),
            new SimulationWI실행우선순위Definition("WI-NATURE-15", "D1", 17, "Core", "Queued", "NotApplicable", "Nature", new[] { "playable-loop:nature-night-day2.v1" }),
            new SimulationWI실행우선순위Definition("WI-CON-01", "D1", 18, "Shared", "E7Closed", "NotApplicable", "Construction", new[] { "playable-loop:nature-workbench-foundation.v1", "playable-loop:nature-building-learning.v1", "playable-loop:farm-player-placement.v1" }),
            new SimulationWI실행우선순위Definition("WI-NATURE-16", "D1", 19, "Core", "Queued", "NotApplicable", "Nature", new[] { "playable-loop:nature-field-supply-return.v1" }),
            new SimulationWI실행우선순위Definition("WI-NATURE-17", "D1", 20, "Core", "Queued", "Required", "Nature", new[] { "playable-loop:nature-field-supply-return.v1" }),
            new SimulationWI실행우선순위Definition("WI-REFLECT-01", "D1", 21, "Extension", "Queued", "NotApplicable", "Nature", new[] { "playable-loop:nature-base-reflection.v1" }),
            new SimulationWI실행우선순위Definition("WI-NATURE-18", "D1", 22, "Core", "E7Closed", "NotApplicable", "Nature", new[] { "playable-loop:nature-shelter-foundation.v1" }),
            new SimulationWI실행우선순위Definition("WI-ACTOR-03", "D1", 23, "Core", "Active", "NotApplicable", "Shared", new[] { "playable-loop:nature-basic-herbal-recovery.v1" }),
            new SimulationWI실행우선순위Definition("WI-COMMUNITY-VISITOR-STAY", "D1", 24, "Core", "Active", "NotApplicable", "Nature", new[] { "playable-loop:nature-camp-visitor-stay.v1" }),
            new SimulationWI실행우선순위Definition("WI-FARM-01", "D2", 1, "Core", "Active", "Conditional", "Farm", new[] { "playable-loop:farm-crop-cycle.v1" }),
            new SimulationWI실행우선순위Definition("WI-FARM-02", "D2", 2, "Core", "Queued", "Conditional", "Farm", new[] { "playable-loop:farm-crop-cycle.v1" }),
            new SimulationWI실행우선순위Definition("WI-FARM-03", "D2", 3, "Core", "Queued", "Conditional", "Farm", new[] { "playable-loop:farm-crop-cycle.v1" }),
            new SimulationWI실행우선순위Definition("WI-FARM-04", "D2", 4, "Core", "Queued", "Conditional", "Farm", new[] { "playable-loop:farm-crop-cycle.v1" }),
            new SimulationWI실행우선순위Definition("WI-FARM-05", "D2", 5, "Core", "Queued", "Conditional", "Farm", new[] { "playable-loop:farm-pack-store-return.v1" }),
            new SimulationWI실행우선순위Definition("WI-FARM-06", "D2", 6, "Core", "Queued", "Conditional", "Farm", new[] { "playable-loop:farm-pack-store-return.v1" }),
            new SimulationWI실행우선순위Definition("WI-FARM-DEFENSE-MOBILIZE", "D2", 7, "Core", "Queued", "NotApplicable", "Farm", new[] { "playable-loop:farm-barracks-defense.v1" }),
            new SimulationWI실행우선순위Definition("WI-SQUAD-ASSIGN", "D2", 8, "Core", "Queued", "NotApplicable", "Farm", new[] { "playable-loop:farm-barracks-defense.v1" }),
            new SimulationWI실행우선순위Definition("WI-SQUAD-SUPPLY", "D2", 9, "Core", "Queued", "NotApplicable", "Farm", new[] { "playable-loop:farm-barracks-defense.v1" }),
            new SimulationWI실행우선순위Definition("WI-FARM-DEFENSE-RESOLVE", "D2", 10, "Core", "Queued", "NotApplicable", "Farm", new[] { "playable-loop:farm-barracks-defense.v1" }),
            new SimulationWI실행우선순위Definition("WI-FARM-DEFENSE-RETURN", "D2", 11, "Core", "Queued", "NotApplicable", "Farm", new[] { "playable-loop:farm-barracks-defense.v1" }),
            new SimulationWI실행우선순위Definition("WI-001", "D3", 1, "Core", "Queued", "Required", "Hub", new[] { "playable-loop:hub-inbound-putaway.v1" }),
            new SimulationWI실행우선순위Definition("WI-002", "D3", 2, "Core", "Queued", "Required", "Hub", new[] { "playable-loop:hub-inbound-putaway.v1" }),
            new SimulationWI실행우선순위Definition("WI-HUB-03", "D3", 3, "Core", "Queued", "Required", "Hub", new[] { "playable-loop:hub-outbound-ready-return.v1" }),
            new SimulationWI실행우선순위Definition("WI-HUB-04", "D3", 4, "Core", "Queued", "Required", "Hub", new[] { "playable-loop:hub-outbound-ready-return.v1" }),
            new SimulationWI실행우선순위Definition("WI-HUB-05", "D3", 5, "Core", "Queued", "Required", "Hub", new[] { "playable-loop:hub-outbound-ready-return.v1" }),
            new SimulationWI실행우선순위Definition("WI-ORDER-01", "D4", 1, "Core", "Queued", "Required", "Town", new[] { "playable-loop:town-order-consume-return.v1" }),
            new SimulationWI실행우선순위Definition("WI-ORDER-02", "D4", 2, "Core", "Queued", "NotApplicable", "Town", new[] { "playable-loop:town-order-consume-return.v1" }),
            new SimulationWI실행우선순위Definition("WI-ORDER-03", "D4", 3, "Core", "Queued", "Required", "Town", new[] { "playable-loop:town-order-consume-return.v1" }),
            new SimulationWI실행우선순위Definition("WI-ORDER-04", "D4", 4, "Core", "Queued", "Required", "Town", new[] { "playable-loop:town-order-consume-return.v1" }),
            new SimulationWI실행우선순위Definition("WI-ORDER-05", "D4", 5, "Core", "Queued", "NotApplicable", "Town", new[] { "playable-loop:town-order-consume-return.v1" }),
            new SimulationWI실행우선순위Definition("WI-ORDER-06", "D4", 6, "Core", "Queued", "Required", "Town", new[] { "playable-loop:town-order-consume-return.v1" }),
            new SimulationWI실행우선순위Definition("WI-ORDER-07", "D4", 7, "Core", "Queued", "Required", "Town", new[] { "playable-loop:town-order-consume-return.v1" }),
            new SimulationWI실행우선순위Definition("WI-CARD-01", "D4", 8, "Extension", "Queued", "NotApplicable", "Town", new[] { "playable-loop:town-arcana-context.v1" }),
            new SimulationWI실행우선순위Definition("WI-CITY-01", "D5", 1, "Core", "Queued", "Required", "City", new[] { "playable-loop:city-demand-service-return.v1" }),
            new SimulationWI실행우선순위Definition("WI-CITY-02", "D5", 2, "Core", "Queued", "NotApplicable", "City", new[] { "playable-loop:city-demand-service-return.v1" }),
            new SimulationWI실행우선순위Definition("WI-CITY-03", "D5", 3, "Core", "Queued", "Required", "City", new[] { "playable-loop:city-demand-service-return.v1" }),
            new SimulationWI실행우선순위Definition("WI-CITY-04", "D5", 4, "Core", "Queued", "Required", "City", new[] { "playable-loop:city-demand-service-return.v1" }),
            new SimulationWI실행우선순위Definition("WI-HUB-06", "D6", 1, "DeferredIntegration", "Deferred", "Required", "Hub", Array.Empty<string>()),
            new SimulationWI실행우선순위Definition("WI-LOG-01", "D6", 2, "DeferredIntegration", "Deferred", "Required", "Integration", Array.Empty<string>()),
            new SimulationWI실행우선순위Definition("WI-LOG-02", "D6", 3, "DeferredIntegration", "Deferred", "NotApplicable", "Integration", Array.Empty<string>()),
            new SimulationWI실행우선순위Definition("WI-LOG-03", "D6", 4, "DeferredIntegration", "Deferred", "NotApplicable", "Integration", Array.Empty<string>()),
            new SimulationWI실행우선순위Definition("WI-LOG-04", "D6", 5, "DeferredIntegration", "Deferred", "NotApplicable", "Integration", Array.Empty<string>()),
            new SimulationWI실행우선순위Definition("WI-LOG-05", "D6", 6, "DeferredIntegration", "Deferred", "NotApplicable", "Integration", Array.Empty<string>()),
            new SimulationWI실행우선순위Definition("WI-MARKET-01", "D6", 7, "DeferredIntegration", "Deferred", "Required", "Town", Array.Empty<string>()),
            new SimulationWI실행우선순위Definition("WI-MARKET-02", "D6", 8, "DeferredIntegration", "Deferred", "Required", "Town", Array.Empty<string>()),
            new SimulationWI실행우선순위Definition("WI-MARKET-03", "D6", 9, "DeferredIntegration", "Deferred", "Required", "Town", Array.Empty<string>()),
            new SimulationWI실행우선순위Definition("WI-MARKET-04", "D6", 10, "DeferredIntegration", "Deferred", "Required", "Town", Array.Empty<string>()),
            new SimulationWI실행우선순위Definition("WI-MARKET-05", "D6", 11, "DeferredIntegration", "Deferred", "Required", "Town", Array.Empty<string>()),
            new SimulationWI실행우선순위Definition("WI-WORLD-01", "D6", 12, "DeferredIntegration", "Deferred", "NotApplicable", "None", Array.Empty<string>()),
            new SimulationWI실행우선순위Definition("WI-WORLD-02", "D6", 13, "DeferredIntegration", "Deferred", "Required", "None", Array.Empty<string>()),
            new SimulationWI실행우선순위Definition("WI-WORLD-03", "D6", 14, "DeferredIntegration", "Deferred", "NotApplicable", "Construction", new[] { "playable-loop:farm-player-placement.v1" }),
            new SimulationWI실행우선순위Definition("WI-WORLD-04", "D6", 15, "DeferredIntegration", "Deferred", "Conditional", "Construction", Array.Empty<string>()),
            new SimulationWI실행우선순위Definition("WI-WORLD-05", "D6", 16, "DeferredIntegration", "Deferred", "NotApplicable", "Integration", Array.Empty<string>()),
            new SimulationWI실행우선순위Definition("WI-WORLD-06", "D6", 17, "DeferredIntegration", "Deferred", "NotApplicable", "None", Array.Empty<string>()),
            new SimulationWI실행우선순위Definition("WI-WORLD-07", "D6", 18, "DeferredIntegration", "Deferred", "NotApplicable", "None", Array.Empty<string>()),
            new SimulationWI실행우선순위Definition("WI-WORLD-08", "D6", 19, "DeferredIntegration", "Deferred", "NotApplicable", "None", new[] { "playable-loop:solo-world-day.v1" }),
            new SimulationWI실행우선순위Definition("WI-REVIEW-01", "D6", 20, "DeferredIntegration", "Deferred", "NotApplicable", "None", Array.Empty<string>()),
            new SimulationWI실행우선순위Definition("WI-ACTOR-CONSUME", "D7", 1, "DeferredRegistration", "Deferred", "NotApplicable", "None", Array.Empty<string>()),
            new SimulationWI실행우선순위Definition("WI-ACTOR-PLAN-SET", "D7", 2, "Extension", "Queued", "NotApplicable", "None", new[] { "playable-loop:nature-night-day2.v1" }),
            new SimulationWI실행우선순위Definition("WI-COMBAT-DIRECT-CONTROL-SET", "D7", 3, "DeferredRegistration", "Deferred", "NotApplicable", "None", Array.Empty<string>()),
            new SimulationWI실행우선순위Definition("WI-COMBAT-TACTICAL-COMMAND", "D7", 4, "DeferredRegistration", "Deferred", "NotApplicable", "None", Array.Empty<string>()),
            new SimulationWI실행우선순위Definition("WI-COMMUNITY-COOPERATION-PROPOSE", "D7", 5, "DeferredRegistration", "Deferred", "NotApplicable", "None", Array.Empty<string>()),
            new SimulationWI실행우선순위Definition("WI-COMMUNITY-ENTRANCE-POLICY-SET", "D7", 6, "DeferredRegistration", "Deferred", "NotApplicable", "None", Array.Empty<string>()),
            new SimulationWI실행우선순위Definition("WI-COMMUNITY-HIRE", "D7", 7, "DeferredRegistration", "Deferred", "NotApplicable", "None", Array.Empty<string>()),
            new SimulationWI실행우선순위Definition("WI-COMMUNITY-MEMBERSHIP-CONFIRM", "D7", 8, "DeferredRegistration", "Deferred", "NotApplicable", "None", Array.Empty<string>()),
            new SimulationWI실행우선순위Definition("WI-COMMUNITY-REMOTE-RESPONSE", "D7", 9, "DeferredRegistration", "Deferred", "NotApplicable", "None", Array.Empty<string>()),
            new SimulationWI실행우선순위Definition("WI-COMMUNITY-SUPPORT-MISSION-JOIN", "D7", 10, "DeferredRegistration", "Deferred", "NotApplicable", "None", Array.Empty<string>()),
            new SimulationWI실행우선순위Definition("WI-CON-BLUEPRINT-PLACE", "D7", 11, "DeferredRegistration", "Deferred", "Conditional", "None", Array.Empty<string>()),
            new SimulationWI실행우선순위Definition("WI-CON-DEMOLISH", "D7", 12, "DeferredRegistration", "Deferred", "Conditional", "None", Array.Empty<string>()),
            new SimulationWI실행우선순위Definition("WI-CON-MATERIAL-DEPOSIT", "D7", 13, "DeferredRegistration", "Deferred", "Conditional", "None", Array.Empty<string>()),
            new SimulationWI실행우선순위Definition("WI-CON-WORK-CONTRIBUTE", "D7", 14, "DeferredRegistration", "Deferred", "Conditional", "None", Array.Empty<string>()),
            new SimulationWI실행우선순위Definition("WI-CRAFT-BREW", "D7", 15, "DeferredRegistration", "Deferred", "Conditional", "None", Array.Empty<string>()),
            new SimulationWI실행우선순위Definition("WI-EXPEDITION-DISPATCH", "D7", 16, "DeferredRegistration", "Deferred", "Conditional", "None", Array.Empty<string>()),
            new SimulationWI실행우선순위Definition("WI-FARM-FIELD-BOUNDARY-CONFIRM", "D7", 17, "DeferredRegistration", "Deferred", "NotApplicable", "None", Array.Empty<string>()),
            new SimulationWI실행우선순위Definition("WI-FARM-SOIL-AMEND", "D7", 18, "DeferredRegistration", "Deferred", "Conditional", "None", Array.Empty<string>()),
            new SimulationWI실행우선순위Definition("WI-FARM-WATER-TRANSFER", "D7", 19, "DeferredRegistration", "Deferred", "Conditional", "None", Array.Empty<string>()),
            new SimulationWI실행우선순위Definition("WI-GUEST-PERMISSION-SET", "D7", 20, "DeferredRegistration", "Deferred", "NotApplicable", "None", Array.Empty<string>()),
            new SimulationWI실행우선순위Definition("WI-HEAT-SOURCE-STATE-CHANGE", "D7", 21, "Extension", "Queued", "Conditional", "None", new[] { "playable-loop:nature-night-day2.v1" }),
            new SimulationWI실행우선순위Definition("WI-HUB-DEMAND-ALLOCATE", "D7", 22, "DeferredRegistration", "Deferred", "NotApplicable", "None", Array.Empty<string>()),
            new SimulationWI실행우선순위Definition("WI-HUB-SUPPLY-TASK-ACCEPT", "D7", 23, "DeferredRegistration", "Deferred", "NotApplicable", "None", Array.Empty<string>()),
            new SimulationWI실행우선순위Definition("WI-INVENTORY-BELOW-RESERVE-SALE-CONFIRM", "D7", 24, "DeferredRegistration", "Deferred", "NotApplicable", "None", Array.Empty<string>()),
            new SimulationWI실행우선순위Definition("WI-NATURE-HERB-GATHER", "D7", 25, "DeferredRegistration", "Deferred", "Conditional", "None", Array.Empty<string>()),
            new SimulationWI실행우선순위Definition("WI-NATURE-TRACE-INVESTIGATE", "D7", 26, "DeferredRegistration", "Deferred", "Conditional", "None", Array.Empty<string>()),
            new SimulationWI실행우선순위Definition("WI-SURVIVAL-RATION-POLICY-SET", "D7", 27, "DeferredRegistration", "Deferred", "NotApplicable", "None", Array.Empty<string>()),
            new SimulationWI실행우선순위Definition("WI-TOWN-DELIVERY-INSPECT", "D7", 28, "DeferredRegistration", "Deferred", "Conditional", "None", Array.Empty<string>()),
            new SimulationWI실행우선순위Definition("WI-TOWN-DELIVERY-RECEIVE", "D7", 29, "DeferredRegistration", "Deferred", "Conditional", "None", Array.Empty<string>()),
            new SimulationWI실행우선순위Definition("WI-TOWN-STOCK-PUTAWAY", "D7", 30, "DeferredRegistration", "Deferred", "Conditional", "None", Array.Empty<string>()),
            new SimulationWI실행우선순위Definition("WI-TOWN-STOCK-REPLENISH", "D7", 31, "DeferredRegistration", "Deferred", "NotApplicable", "None", Array.Empty<string>()),
            new SimulationWI실행우선순위Definition("WI-TOWN-SUPPLY-DISPATCH", "D7", 32, "DeferredRegistration", "Deferred", "Conditional", "None", Array.Empty<string>()),
            new SimulationWI실행우선순위Definition("WI-WORLD-RESOURCE-REGENERATE", "D7", 33, "Extension", "Active", "NotApplicable", "None", new[] { "playable-loop:nature-night-day2.v1" }),
        };
        public static IReadOnlyList<SimulationWI실행우선순위Definition> All => 항목들;
        public static SimulationWI실행우선순위Definition? Find(string worldInteractionId)
        {
            if (string.IsNullOrWhiteSpace(worldInteractionId)) return null;
            foreach (var 항목 in 항목들)
                if (string.Equals(항목.WorldInteractionId, worldInteractionId, StringComparison.Ordinal)) return 항목;
            return null;
        }
    }
}
