// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Ssalddel.Infrastructure.Persistence.PublicData;

#nullable disable

namespace Ssalddel.Infrastructure.Persistence.PublicData.Migrations
{
    [DbContext(typeof(PublicDataIngestionDbContext))]
    [Migration("20260808134522_AddExternalDataTemporalPrecision")]
    partial class AddExternalDataTemporalPrecision
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Ssalddel.Domain.PublicData.외부데이터RawSnapshot", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CollectedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ContentHashSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<long>("ContentLength")
                        .HasColumnType("bigint");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)");

                    b.Property<string>("DatasetId")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)");

                    b.Property<DateTimeOffset?>("EvidenceAsOfUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("FirstCollectionRunId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("FirstSeenAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTimeOffset>("LastSeenAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("SourceId")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)");

                    b.Property<string>("SourceVersion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("StorageContainer")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("StorageLocation")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("varchar(2048)");

                    b.Property<string>("StorageObjectName")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("varchar(1024)");

                    b.HasKey("Id");

                    b.HasIndex("FirstCollectionRunId");

                    b.HasIndex("SourceId", "DatasetId", "ContentHashSha256")
                        .IsUnique();

                    b.ToTable("public_data_raw_snapshots", (string)null);
                });

            modelBuilder.Entity("Ssalddel.Domain.PublicData.외부데이터수집Run", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("AttemptCount")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DataRevision")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("DatasetId")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)");

                    b.Property<string>("ErrorCode")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<string>("ErrorSummary")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("ExistingCount")
                        .HasColumnType("int");

                    b.Property<int>("FetchedCount")
                        .HasColumnType("int");

                    b.Property<int>("InsertedCount")
                        .HasColumnType("int");

                    b.Property<int>("NormalizedCount")
                        .HasColumnType("int");

                    b.Property<int>("RejectedCount")
                        .HasColumnType("int");

                    b.Property<string>("RunKey")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<string>("SourceId")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)");

                    b.Property<string>("SourceVersion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTimeOffset>("StartedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("StatusCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<int>("UpdatedCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RunKey")
                        .IsUnique();

                    b.HasIndex("SourceId", "DatasetId", "StartedAtUtc");

                    b.ToTable("public_data_ingestion_runs", (string)null);
                });

            modelBuilder.Entity("Ssalddel.Domain.PublicData.외부데이터정규화Record", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CollectedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DataRevision")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("DatasetId")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)");

                    b.Property<string>("DimensionKey")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTimeOffset>("EvidenceAsOfUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTimeOffset>("FirstSeenAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTimeOffset>("LastSeenAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LimitationCode")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("varchar(240)");

                    b.Property<string>("MetricCode")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)");

                    b.Property<decimal?>("NumericValue")
                        .HasPrecision(28, 10)
                        .HasColumnType("decimal(28,10)");

                    b.Property<string>("QualityCode")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<long>("RawSnapshotId")
                        .HasColumnType("bigint");

                    b.Property<string>("RecordKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("RegionStableId")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("varchar(240)");

                    b.Property<string>("SourceId")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)");

                    b.Property<string>("SourceVersion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("SpatialPrecisionCode")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<string>("StableId")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("varchar(240)");

                    b.Property<string>("TemporalPrecisionCode")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<string>("TextValue")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<string>("UnitCode")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.HasKey("Id");

                    b.HasIndex("RawSnapshotId");

                    b.HasIndex("RecordKey")
                        .IsUnique();

                    b.HasIndex("RegionStableId", "MetricCode", "EvidenceAsOfUtc");

                    b.ToTable("public_data_normalized_records", (string)null);
                });

            modelBuilder.Entity("Ssalddel.Domain.PublicData.외부지역CodeMapping", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ExternalRegionCode")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("varchar(240)");

                    b.Property<string>("MappingRevision")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("RegionStableId")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("varchar(240)");

                    b.Property<string>("SourceId")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)");

                    b.Property<string>("SpatialPrecisionCode")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<DateTimeOffset?>("ValidFromUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTimeOffset?>("ValidToUtc")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("SourceId", "ExternalRegionCode")
                        .IsUnique();

                    b.ToTable("public_data_region_mappings", (string)null);
                });

            modelBuilder.Entity("Ssalddel.Domain.PublicData.외부데이터RawSnapshot", b =>
                {
                    b.HasOne("Ssalddel.Domain.PublicData.외부데이터수집Run", "FirstCollectionRun")
                        .WithMany()
                        .HasForeignKey("FirstCollectionRunId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FirstCollectionRun");
                });

            modelBuilder.Entity("Ssalddel.Domain.PublicData.외부데이터정규화Record", b =>
                {
                    b.HasOne("Ssalddel.Domain.PublicData.외부데이터RawSnapshot", "RawSnapshot")
                        .WithMany()
                        .HasForeignKey("RawSnapshotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("RawSnapshot");
                });
#pragma warning restore 612, 618
        }
    }
}
