using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Ssalddel.Simulation.Application;
using Ssalddel.Simulation.Domain;

namespace Ssalddel.Simulation.Persistence;

public sealed class SimulationWorldUI기획CatalogEntity { public long Id { get; set; } public int SchemaVersion { get; set; } public string CatalogRevision { get; set; } = ""; public string BusinessRuleCatalogRevision { get; set; } = ""; public string BusinessRuleCatalogHashSha256 { get; set; } = ""; public string CatalogHashSha256 { get; set; } = ""; public DateTimeOffset CreatedAtUtc { get; set; } public DateTimeOffset StoredAtUtc { get; set; } }
public sealed class SimulationWorldUI설계근거Entity { public long Id { get; set; } public long CatalogId { get; set; } public string StableId { get; set; } = ""; public string ProviderCode { get; set; } = ""; public string FileKey { get; set; } = ""; public string NodeId { get; set; } = ""; public string KoreanTitle { get; set; } = ""; public string ObservedStructureCode { get; set; } = ""; public DateTimeOffset ObservedAtUtc { get; set; } }
public sealed class SimulationWorldUI화면영역Entity { public long Id { get; set; } public long CatalogId { get; set; } public string StableId { get; set; } = ""; public string FacilityStableId { get; set; } = ""; public string SurfaceKindCode { get; set; } = ""; public string PerspectiveCode { get; set; } = ""; public string RoleCode { get; set; } = ""; public string WorkflowStageCode { get; set; } = ""; public string KoreanTitle { get; set; } = ""; public string AnchorSemanticCode { get; set; } = ""; public int DisplayOrder { get; set; } public bool DefaultVisible { get; set; } public string DesignEvidenceStableId { get; set; } = ""; }
public sealed class SimulationWorldUI정보항목Entity { public long Id { get; set; } public long CatalogId { get; set; } public string StableId { get; set; } = ""; public string SurfaceStableId { get; set; } = ""; public string InformationKindCode { get; set; } = ""; public string KoreanLabel { get; set; } = ""; public string ValueSemanticCode { get; set; } = ""; public string SourceContractKey { get; set; } = ""; public string FormatCode { get; set; } = ""; public string? UnitCode { get; set; } public int Priority { get; set; } public bool ProvenanceRequired { get; set; } }
public sealed class SimulationWorldUI상태표현Entity { public long Id { get; set; } public long CatalogId { get; set; } public string StableId { get; set; } = ""; public string SurfaceStableId { get; set; } = ""; public string StateCode { get; set; } = ""; public string KoreanLabel { get; set; } = ""; public string SeverityCode { get; set; } = ""; public string PresentationIntentCode { get; set; } = ""; public bool BlocksMutationActions { get; set; } public int DisplayOrder { get; set; } }
public sealed class SimulationWorldUI행동후보Entity { public long Id { get; set; } public long CatalogId { get; set; } public string StableId { get; set; } = ""; public string SurfaceStableId { get; set; } = ""; public string ActionKindCode { get; set; } = ""; public string KoreanLabel { get; set; } = ""; public string CapabilityKey { get; set; } = ""; public string? ServerCommandKey { get; set; } public bool RequiresPreview { get; set; } public bool RequiresExplicitConfirmation { get; set; } public bool RequiresExpectedRevision { get; set; } public bool SimulationOnly { get; set; } public int DisplayOrder { get; set; } }
public sealed class SimulationWorldUI업무규칙연결Entity { public long Id { get; set; } public long CatalogId { get; set; } public string StableId { get; set; } = ""; public string BusinessRuleBindingStableId { get; set; } = ""; public string FacilityCapabilityCode { get; set; } = ""; public string RuleStableId { get; set; } = ""; public string RuleRevision { get; set; } = ""; public string SurfaceStableId { get; set; } = ""; public string PurposeCode { get; set; } = ""; public int Priority { get; set; } }

public sealed class SimulationWorld업무규칙집결Reader(SimulationWorld파생DbContext db) : ISimulationWorld업무규칙집결Reader
{
    public async Task<SimulationWorld업무규칙집결원장?> 조회Async(string revision, CancellationToken cancellationToken)
    {
        var root = await db.BusinessRuleCatalogs.AsNoTracking().SingleOrDefaultAsync(x => x.CatalogRevision == revision, cancellationToken);
        if (root == null) return null;
        var facilities = await db.FacilitySemantics.AsNoTracking().Where(x => x.CatalogId == root.Id).OrderBy(x => x.StableId).ToArrayAsync(cancellationToken);
        var capabilities = await db.FacilityCapabilities.AsNoTracking().Where(x => x.CatalogId == root.Id).OrderBy(x => x.StableId).ToArrayAsync(cancellationToken);
        var rules = await db.BusinessSimulationRules.AsNoTracking().Where(x => x.CatalogId == root.Id).OrderBy(x => x.StableId).ToArrayAsync(cancellationToken);
        var parameters = await db.BusinessSimulationRuleParameters.AsNoTracking().Where(x => x.CatalogId == root.Id).OrderBy(x => x.RuleStableId).ThenBy(x => x.ParameterCode).ToArrayAsync(cancellationToken);
        var bindings = await db.ObjectBusinessRuleBindings.AsNoTracking().Where(x => x.CatalogId == root.Id).OrderBy(x => x.StableId).ToArrayAsync(cancellationToken);
        var sets = await db.ScenarioRuleSets.AsNoTracking().Where(x => x.CatalogId == root.Id).OrderBy(x => x.StableId).ToArrayAsync(cancellationToken);
        var items = await db.ScenarioRuleItems.AsNoTracking().Where(x => x.CatalogId == root.Id).OrderBy(x => x.ApplyOrder).ToArrayAsync(cancellationToken);
        return new SimulationWorld업무규칙집결원장
        {
            SchemaVersion = root.SchemaVersion, CatalogRevision = root.CatalogRevision,
            SpatialBuildStableId = root.SpatialBuildStableId, SpatialOutputHashSha256 = root.SpatialOutputHashSha256,
            CreatedAtUtc = root.CreatedAtUtc,
            Facilities = facilities.Select(x => new SimulationWorld시설의미 { StableId=x.StableId, SpatialNodeStableId=x.SpatialNodeStableId, FacilityTypeCode=x.FacilityTypeCode, EvidenceKindCode=x.EvidenceKindCode, EvidenceSourceStableId=x.EvidenceSourceStableId, ConfidenceCode=x.ConfidenceCode, ScenarioAssigned=x.ScenarioAssigned }).ToArray(),
            Capabilities = capabilities.Select(x => new SimulationWorld시설기능 { StableId=x.StableId, FacilityStableId=x.FacilityStableId, CapabilityCode=x.CapabilityCode, EvidenceKindCode=x.EvidenceKindCode }).ToArray(),
            Rules = rules.Select(x => new SimulationWorld업무Simulation규칙 { StableId=x.StableId, Revision=x.Revision, DomainCode=x.DomainCode, RuleTypeCode=x.RuleTypeCode, StatusCode=x.StatusCode, EngineKey=x.EngineKey, InputContractKey=x.InputContractKey, OutputContractKey=x.OutputContractKey, Deterministic=x.Deterministic, SimulationOnly=x.SimulationOnly, Description=x.Description }).ToArray(),
            Parameters = parameters.Select(x => new SimulationWorld업무Simulation규칙Parameter { RuleStableId=x.RuleStableId, RuleRevision=x.RuleRevision, ParameterCode=x.ParameterCode, ValueTypeCode=x.ValueTypeCode, Value=x.Value, UnitCode=x.UnitCode, EvidenceKindCode=x.EvidenceKindCode }).ToArray(),
            Bindings = bindings.Select(x => new SimulationWorld객체업무규칙연결 { StableId=x.StableId, FacilityStableId=x.FacilityStableId, CapabilityCode=x.CapabilityCode, RuleStableId=x.RuleStableId, RuleRevision=x.RuleRevision, ScopeCode=x.ScopeCode, Priority=x.Priority, EvidenceKindCode=x.EvidenceKindCode, Active=x.Active }).ToArray(),
            ScenarioRuleSets = sets.Select(set => new SimulationWorldScenario규칙묶음 { StableId=set.StableId, Revision=set.Revision, AreaSetStableId=set.AreaSetStableId, Items=items.Where(x => x.RuleSetStableId==set.StableId && x.RuleSetRevision==set.Revision).Select(x => new SimulationWorldScenario규칙항목 { RuleStableId=x.RuleStableId, RuleRevision=x.RuleRevision, ApplyOrder=x.ApplyOrder, Required=x.Required }).ToArray() }).ToArray(),
        };
    }
}

public sealed class SimulationWorldUI기획Store(SimulationWorld파생DbContext db) : ISimulationWorldUI기획Store
{
    public async Task<SimulationWorldUI기획저장결과> 저장Async(SimulationWorldUI기획원장 plan, SimulationWorld업무규칙집결원장 rules, CancellationToken cancellationToken)
    {
        var hash = SimulationWorldUI기획Validator.ComputeHash(plan, rules);
        var existing = await db.UiPlanningCatalogs.AsNoTracking().SingleOrDefaultAsync(x => x.CatalogRevision == plan.CatalogRevision, cancellationToken);
        if (existing != null)
        {
            if (!string.Equals(existing.CatalogHashSha256, hash, StringComparison.OrdinalIgnoreCase)) throw new InvalidOperationException("SimulationWorldUiPlanningCatalogRevisionConflict");
            return Result(false, plan, hash);
        }
        await using var transaction = await db.Database.BeginTransactionAsync(cancellationToken);
        var root = new SimulationWorldUI기획CatalogEntity { SchemaVersion=plan.SchemaVersion, CatalogRevision=plan.CatalogRevision, BusinessRuleCatalogRevision=plan.BusinessRuleCatalogRevision, BusinessRuleCatalogHashSha256=plan.BusinessRuleCatalogHashSha256, CatalogHashSha256=hash, CreatedAtUtc=plan.CreatedAtUtc, StoredAtUtc=DateTimeOffset.UtcNow };
        db.UiPlanningCatalogs.Add(root); await db.SaveChangesAsync(cancellationToken);
        db.UiDesignEvidence.AddRange(plan.DesignEvidence.Select(x => new SimulationWorldUI설계근거Entity { CatalogId=root.Id, StableId=x.StableId, ProviderCode=x.ProviderCode, FileKey=x.FileKey, NodeId=x.NodeId, KoreanTitle=x.KoreanTitle, ObservedStructureCode=x.ObservedStructureCode, ObservedAtUtc=x.ObservedAtUtc }));
        db.UiSurfaces.AddRange(plan.Surfaces.Select(x => new SimulationWorldUI화면영역Entity { CatalogId=root.Id, StableId=x.StableId, FacilityStableId=x.FacilityStableId, SurfaceKindCode=x.SurfaceKindCode, PerspectiveCode=x.PerspectiveCode, RoleCode=x.RoleCode, WorkflowStageCode=x.WorkflowStageCode, KoreanTitle=x.KoreanTitle, AnchorSemanticCode=x.AnchorSemanticCode, DisplayOrder=x.DisplayOrder, DefaultVisible=x.DefaultVisible, DesignEvidenceStableId=x.DesignEvidenceStableId }));
        db.UiInformationItems.AddRange(plan.InformationItems.Select(x => new SimulationWorldUI정보항목Entity { CatalogId=root.Id, StableId=x.StableId, SurfaceStableId=x.SurfaceStableId, InformationKindCode=x.InformationKindCode, KoreanLabel=x.KoreanLabel, ValueSemanticCode=x.ValueSemanticCode, SourceContractKey=x.SourceContractKey, FormatCode=x.FormatCode, UnitCode=x.UnitCode, Priority=x.Priority, ProvenanceRequired=x.ProvenanceRequired }));
        db.UiStatePresentations.AddRange(plan.StatePresentations.Select(x => new SimulationWorldUI상태표현Entity { CatalogId=root.Id, StableId=x.StableId, SurfaceStableId=x.SurfaceStableId, StateCode=x.StateCode, KoreanLabel=x.KoreanLabel, SeverityCode=x.SeverityCode, PresentationIntentCode=x.PresentationIntentCode, BlocksMutationActions=x.BlocksMutationActions, DisplayOrder=x.DisplayOrder }));
        db.UiActionCandidates.AddRange(plan.ActionCandidates.Select(x => new SimulationWorldUI행동후보Entity { CatalogId=root.Id, StableId=x.StableId, SurfaceStableId=x.SurfaceStableId, ActionKindCode=x.ActionKindCode, KoreanLabel=x.KoreanLabel, CapabilityKey=x.CapabilityKey, ServerCommandKey=x.ServerCommandKey, RequiresPreview=x.RequiresPreview, RequiresExplicitConfirmation=x.RequiresExplicitConfirmation, RequiresExpectedRevision=x.RequiresExpectedRevision, SimulationOnly=x.SimulationOnly, DisplayOrder=x.DisplayOrder }));
        db.UiBusinessRuleBindings.AddRange(plan.RuleBindings.Select(x => new SimulationWorldUI업무규칙연결Entity { CatalogId=root.Id, StableId=x.StableId, BusinessRuleBindingStableId=x.BusinessRuleBindingStableId, FacilityCapabilityCode=x.FacilityCapabilityCode, RuleStableId=x.RuleStableId, RuleRevision=x.RuleRevision, SurfaceStableId=x.SurfaceStableId, PurposeCode=x.PurposeCode, Priority=x.Priority }));
        await db.SaveChangesAsync(cancellationToken); await transaction.CommitAsync(cancellationToken); return Result(true, plan, hash);
    }
    private static SimulationWorldUI기획저장결과 Result(bool inserted, SimulationWorldUI기획원장 plan, string hash) => new() { Inserted=inserted, CatalogRevision=plan.CatalogRevision, CatalogHashSha256=hash, SurfaceCount=plan.Surfaces.Count, InformationItemCount=plan.InformationItems.Count, StatePresentationCount=plan.StatePresentations.Count, ActionCandidateCount=plan.ActionCandidates.Count, RuleBindingCount=plan.RuleBindings.Count };
}

internal static class SimulationWorldUI기획Config
{
    public static void Root<TEntity>(EntityTypeBuilder<TEntity> b, string table) where TEntity:class { b.ToTable(table); b.HasKey("Id"); }
    public static void Child<TEntity>(EntityTypeBuilder<TEntity> b, string table) where TEntity:class { Root(b,table); b.HasOne<SimulationWorldUI기획CatalogEntity>().WithMany().HasForeignKey("CatalogId").OnDelete(DeleteBehavior.Cascade); }
    public static void Text(PropertyBuilder<string> p,string name,int length)=>p.HasColumnName(name).HasMaxLength(length).IsRequired(); public static void Optional(PropertyBuilder<string?> p,string name,int length)=>p.HasColumnName(name).HasMaxLength(length); public static void Value<T>(PropertyBuilder<T> p,string name)=>p.HasColumnName(name);
}

internal sealed class SimulationWorldUI기획CatalogConfiguration:IEntityTypeConfiguration<SimulationWorldUI기획CatalogEntity>{public void Configure(EntityTypeBuilder<SimulationWorldUI기획CatalogEntity>b){SimulationWorldUI기획Config.Root(b,"시뮬레이션월드_UI기획대장");b.HasIndex(x=>x.CatalogRevision).IsUnique();Map(b.Property(x=>x.Id),"식별번호");Map(b.Property(x=>x.SchemaVersion),"스키마버전");Txt(b.Property(x=>x.CatalogRevision),"UI기획개정번호",120);Txt(b.Property(x=>x.BusinessRuleCatalogRevision),"업무규칙대장개정번호",120);Txt(b.Property(x=>x.BusinessRuleCatalogHashSha256),"업무규칙대장SHA256",64);Txt(b.Property(x=>x.CatalogHashSha256),"UI기획SHA256",64);Map(b.Property(x=>x.CreatedAtUtc),"생성시각UTC");Map(b.Property(x=>x.StoredAtUtc),"저장시각UTC");}private static void Txt(PropertyBuilder<string>p,string n,int l)=>SimulationWorldUI기획Config.Text(p,n,l);private static void Map<T>(PropertyBuilder<T>p,string n)=>SimulationWorldUI기획Config.Value(p,n);}
internal abstract class UiChildConfig<TEntity>:IEntityTypeConfiguration<TEntity> where TEntity:class { protected abstract string Table{get;} public void Configure(EntityTypeBuilder<TEntity>b){SimulationWorldUI기획Config.Child(b,Table);ConfigureMore(b);}protected abstract void ConfigureMore(EntityTypeBuilder<TEntity>b);protected static void T(PropertyBuilder<string>p,string n,int l)=>SimulationWorldUI기획Config.Text(p,n,l);protected static void O(PropertyBuilder<string?>p,string n,int l)=>SimulationWorldUI기획Config.Optional(p,n,l);protected static void V<T>(PropertyBuilder<T>p,string n)=>SimulationWorldUI기획Config.Value(p,n);}
internal sealed class SimulationWorldUI설계근거Configuration:UiChildConfig<SimulationWorldUI설계근거Entity>{protected override string Table=>"시뮬레이션월드_UI설계근거";protected override void ConfigureMore(EntityTypeBuilder<SimulationWorldUI설계근거Entity>b){b.HasIndex(x=>new{x.CatalogId,x.StableId}).IsUnique();V(b.Property(x=>x.Id),"식별번호");V(b.Property(x=>x.CatalogId),"UI기획대장식별번호");T(b.Property(x=>x.StableId),"설계근거고유식별자",200);T(b.Property(x=>x.ProviderCode),"제공자코드",40);T(b.Property(x=>x.FileKey),"Figma파일키",120);T(b.Property(x=>x.NodeId),"FigmaNode식별자",80);T(b.Property(x=>x.KoreanTitle),"한글제목",240);T(b.Property(x=>x.ObservedStructureCode),"관측구조코드",160);V(b.Property(x=>x.ObservedAtUtc),"확인시각UTC");}}
internal sealed class SimulationWorldUI화면영역Configuration:UiChildConfig<SimulationWorldUI화면영역Entity>{protected override string Table=>"시뮬레이션월드_UI화면영역기획";protected override void ConfigureMore(EntityTypeBuilder<SimulationWorldUI화면영역Entity>b){b.HasIndex(x=>new{x.CatalogId,x.StableId}).IsUnique();V(b.Property(x=>x.Id),"식별번호");V(b.Property(x=>x.CatalogId),"UI기획대장식별번호");T(b.Property(x=>x.StableId),"화면영역고유식별자",240);T(b.Property(x=>x.FacilityStableId),"시설고유식별자",200);T(b.Property(x=>x.SurfaceKindCode),"화면종류코드",80);T(b.Property(x=>x.PerspectiveCode),"관점코드",80);T(b.Property(x=>x.RoleCode),"역할코드",80);T(b.Property(x=>x.WorkflowStageCode),"업무단계코드",120);T(b.Property(x=>x.KoreanTitle),"한글제목",200);T(b.Property(x=>x.AnchorSemanticCode),"공간Anchor의미코드",120);V(b.Property(x=>x.DisplayOrder),"표시순서");V(b.Property(x=>x.DefaultVisible),"기본표시여부");T(b.Property(x=>x.DesignEvidenceStableId),"설계근거고유식별자",200);}}
internal sealed class SimulationWorldUI정보항목Configuration:UiChildConfig<SimulationWorldUI정보항목Entity>{protected override string Table=>"시뮬레이션월드_UI정보항목기획";protected override void ConfigureMore(EntityTypeBuilder<SimulationWorldUI정보항목Entity>b){b.HasIndex(x=>new{x.CatalogId,x.StableId}).IsUnique();V(b.Property(x=>x.Id),"식별번호");V(b.Property(x=>x.CatalogId),"UI기획대장식별번호");T(b.Property(x=>x.StableId),"정보항목고유식별자",300);T(b.Property(x=>x.SurfaceStableId),"화면영역고유식별자",240);T(b.Property(x=>x.InformationKindCode),"정보종류코드",80);T(b.Property(x=>x.KoreanLabel),"한글표시명",160);T(b.Property(x=>x.ValueSemanticCode),"값의미코드",120);T(b.Property(x=>x.SourceContractKey),"원본계약키",160);T(b.Property(x=>x.FormatCode),"표시형식코드",80);O(b.Property(x=>x.UnitCode),"단위코드",40);V(b.Property(x=>x.Priority),"우선순위");V(b.Property(x=>x.ProvenanceRequired),"계보표시필수여부");}}
internal sealed class SimulationWorldUI상태표현Configuration:UiChildConfig<SimulationWorldUI상태표현Entity>{protected override string Table=>"시뮬레이션월드_UI상태표현기획";protected override void ConfigureMore(EntityTypeBuilder<SimulationWorldUI상태표현Entity>b){b.HasIndex(x=>new{x.CatalogId,x.StableId}).IsUnique();V(b.Property(x=>x.Id),"식별번호");V(b.Property(x=>x.CatalogId),"UI기획대장식별번호");T(b.Property(x=>x.StableId),"상태표현고유식별자",300);T(b.Property(x=>x.SurfaceStableId),"화면영역고유식별자",240);T(b.Property(x=>x.StateCode),"상태코드",80);T(b.Property(x=>x.KoreanLabel),"한글표시명",160);T(b.Property(x=>x.SeverityCode),"심각도코드",40);T(b.Property(x=>x.PresentationIntentCode),"표현의도코드",80);V(b.Property(x=>x.BlocksMutationActions),"변경행동차단여부");V(b.Property(x=>x.DisplayOrder),"표시순서");}}
internal sealed class SimulationWorldUI행동후보Configuration:UiChildConfig<SimulationWorldUI행동후보Entity>{protected override string Table=>"시뮬레이션월드_UI행동후보기획";protected override void ConfigureMore(EntityTypeBuilder<SimulationWorldUI행동후보Entity>b){b.HasIndex(x=>new{x.CatalogId,x.StableId}).IsUnique();V(b.Property(x=>x.Id),"식별번호");V(b.Property(x=>x.CatalogId),"UI기획대장식별번호");T(b.Property(x=>x.StableId),"행동후보고유식별자",300);T(b.Property(x=>x.SurfaceStableId),"화면영역고유식별자",240);T(b.Property(x=>x.ActionKindCode),"행동종류코드",80);T(b.Property(x=>x.KoreanLabel),"한글표시명",160);T(b.Property(x=>x.CapabilityKey),"기능키",160);O(b.Property(x=>x.ServerCommandKey),"서버Command키",160);V(b.Property(x=>x.RequiresPreview),"Preview필수여부");V(b.Property(x=>x.RequiresExplicitConfirmation),"명시적확인필수여부");V(b.Property(x=>x.RequiresExpectedRevision),"기대개정번호필수여부");V(b.Property(x=>x.SimulationOnly),"Simulation전용여부");V(b.Property(x=>x.DisplayOrder),"표시순서");}}
internal sealed class SimulationWorldUI업무규칙연결Configuration:UiChildConfig<SimulationWorldUI업무규칙연결Entity>{protected override string Table=>"시뮬레이션월드_UI업무규칙연결";protected override void ConfigureMore(EntityTypeBuilder<SimulationWorldUI업무규칙연결Entity>b){b.HasIndex(x=>new{x.CatalogId,x.StableId}).IsUnique();b.HasIndex(x=>new{x.CatalogId,x.BusinessRuleBindingStableId}).IsUnique();V(b.Property(x=>x.Id),"식별번호");V(b.Property(x=>x.CatalogId),"UI기획대장식별번호");T(b.Property(x=>x.StableId),"연결고유식별자",300);T(b.Property(x=>x.BusinessRuleBindingStableId),"원본객체업무규칙연결고유식별자",300);T(b.Property(x=>x.FacilityCapabilityCode),"시설기능코드",80);T(b.Property(x=>x.RuleStableId),"업무규칙고유식별자",200);T(b.Property(x=>x.RuleRevision),"업무규칙개정번호",80);T(b.Property(x=>x.SurfaceStableId),"화면영역고유식별자",240);T(b.Property(x=>x.PurposeCode),"연결목적코드",120);V(b.Property(x=>x.Priority),"우선순위");}}
