using Hongdal.Application.Driver.Transport;
using Hongdal.Application.Driver.Profile;
using Hongdal.Application.Driver.Notification;
using 홍달.Services.Dispatch.Engine;
using 홍달.Services.Dispatch.Coordination;
using 홍달.Services.Dispatch.Notification;
using 홍달.Services.Dispatch.Queue;
using 홍달.Services.Documents;
using 홍달.Services.External.Customs;
using 홍달.Services.External.PublicData;
using 홍달.Services.HIOPSAI;
using 홍달.Services.Images;
using 홍달.Services.Payments;
using 홍달.Services.Options;
using 홍달.Services.Sales;
using 홍달.Services.Versioning;
using Hongdal.Services.Auth;
using Hongdal.Services.CollectiveProcurement;
using Hongdal.Services.Community;
using Hongdal.Services.Content;
using Hongdal.Services.Food;
using Hongdal.Services.Education;
using Hongdal.Services.LogisticsProcessing.Warehouse;
using Hongdal.Services.LogisticsProcessing.VehicleLoading;
using Hongdal.Services.Orderer;
using Hongdal.Services.Notifications;
using Hongdal.Services.Speech;

namespace Hongdal.Extensions;

public static partial class ServiceCollectionExtensions
{
    public static IServiceCollection AddHongdalDomainServices(this IServiceCollection services)
    {
        services.AddSingleton<IHongdalExecutionModePolicy, HongdalExecutionModePolicy>();
        services.AddRoleAdvertisingIntegration();
        services.AddScoped<I결제Provider, Toss결제Provider>();
        services.AddScoped<I공통결제Service, 공통결제Service>();
        services.AddScoped<I콘텐츠혜택계산Service, 콘텐츠혜택계산Service>();
        services.AddScoped<I결제승인완료OutboxService, 결제승인완료OutboxService>();
        services.AddScoped<통관상태동기화Service>();
        services.AddSingleton<IPublicDataApiMetadataCatalog, PublicDataApiMetadataCatalog>();
        services.AddScoped<IHs공공데이터수집Service, Hs공공데이터수집Service>();
        services.AddScoped<IHs공공데이터수집기, Hs수입평균단가공공데이터수집기>();
        services.AddScoped<IHs공공데이터수집기>(sp =>
            sp.GetRequiredService<세관장확인대상물품공공데이터수집기>());
        services.AddScoped<IHs공공데이터수집기>(sp =>
            sp.GetRequiredService<관세환율공공데이터수집기>());
        services.AddSingleton<I주문자집단배송권조회Service, 주문자집단배송권조회Service>();
        services.AddSingleton<I주문자집단자동배정Service, 주문자집단자동배정Service>();
        services.AddSingleton<I공동구매물류워크플로우저장소, Mongo공동구매물류워크플로우저장소>();
        services.AddSingleton<I공동구매자동집단화저장소, Mongo공동구매자동집단화저장소>();
        services.AddScoped<I공동구매수령창고Service, 공동구매수령창고Service>();
        services.AddScoped<I공동구매개별주문원장Service, 공동구매개별주문원장Service>();
        services.AddSingleton<ICommunityGroupPurchaseDemandHandoff, CommunityVoteOrdererDemandHandoff>();
        services.AddSingleton<ICommunityProducerMemberDirectory, UnconnectedCommunityProducerMemberDirectory>();
        services.AddSingleton<ICommunityGroupPurchaseRepresentativeDirectory, UnconnectedCommunityGroupPurchaseRepresentativeDirectory>();
        services.AddSingleton<IDomesticProducerContactRequestDraftStore, MongoDomesticProducerContactRequestDraftStore>();
        services.AddSingleton<IDomesticProducerSupplyOfferDraftStore, MongoDomesticProducerSupplyOfferDraftStore>();
        services.AddScoped<IDomesticGroupPurchaseProducerConnectionService, DomesticGroupPurchaseProducerConnectionService>();
        services.AddSingleton<IDomesticGroupPurchaseFulfillmentOrderDraftStore, MongoDomesticGroupPurchaseFulfillmentOrderDraftStore>();
        services.AddScoped<IDomesticGroupPurchaseFulfillmentPlanService, DomesticGroupPurchaseFulfillmentPlanService>();
        services.AddScoped<IDomesticGroupPurchaseVehicleRecommendationService, DomesticGroupPurchaseVehicleRecommendationService>();
        services.AddSingleton<IDomesticGroupPurchaseNegotiationClock, SystemDomesticGroupPurchaseNegotiationClock>();
        services.AddSingleton<IDomesticGroupPurchaseNegotiationStore, MongoDomesticGroupPurchaseNegotiationStore>();
        services.AddScoped<IDomesticGroupPurchaseNegotiationService, DomesticGroupPurchaseNegotiationService>();
        services.AddSingleton<ICollectiveProcurementPlanningClock, SystemCollectiveProcurementPlanningClock>();
        services.AddSingleton<ICollectiveProcurementEconomicsEngine, CollectiveProcurementEconomicsEngine>();
        services.AddSingleton<ICollectiveProcurementPlanningStore, MongoCollectiveProcurementPlanningStore>();
        services.AddScoped<ICollectiveProcurementPlanningService, CollectiveProcurementPlanningService>();
        services.AddSingleton<I공동구매해외선적추적저장소, Mongo공동구매해외선적추적저장소>();
        services.AddSingleton<I공동구매커머스이행계획저장소, Mongo공동구매커머스이행계획저장소>();
        services.AddSingleton<I주문자집단운영주체저장소, Mongo주문자집단운영주체저장소>();
        services.AddSingleton<I판매페이지초안저장소, Mongo판매페이지초안저장소>();
        services.AddSingleton<Mongo커뮤니티원장저장소>();
        services.AddSingleton<I커뮤니티원장투영작업저장소>(sp => sp.GetRequiredService<Mongo커뮤니티원장저장소>());
        services.AddSingleton<I커뮤니티원장저장소, 이벤트발행커뮤니티원장저장소>();
        services.AddSingleton<I커뮤니티원장공유정책저장소, Mongo커뮤니티원장공유정책저장소>();
        services.AddScoped<I커뮤니티원장공유Service, 커뮤니티원장공유Service>();
        services.AddSingleton<ICommunityLedgerRoleAccessPolicyStore, MongoCommunityLedgerRoleAccessPolicyStore>();
        services.AddScoped<ICommunityCustomsBrokerDirectory, EfCommunityCustomsBrokerDirectory>();
        services.AddScoped<ICommunityLedgerRoleAccessService, CommunityLedgerRoleAccessService>();
        services.AddScoped<ICommunityLedgerBlockAssignmentService, CommunityLedgerBlockAssignmentService>();
        services.AddSingleton<I주문원장서명저장소, Mongo주문원장서명저장소>();
        services.AddSingleton<I주문원장공개요청저장소, Mongo주문원장공개요청저장소>();
        services.AddScoped<I주문원장통합UseCase, 주문원장통합UseCase>();
        services.AddScoped<I주문원장서명UseCase, 주문원장서명UseCase>();
        services.AddScoped<I주문원장역할별조회Service, 주문원장역할별조회Service>();
        services.AddScoped<I주문원장공개요청Service, 주문원장공개요청Service>();
        services.AddSingleton<I커뮤니티대화저장소, Mongo커뮤니티대화저장소>();
        services.AddScoped<I커뮤니티원장상태이벤트Service, 커뮤니티원장상태이벤트Service>();
        services.AddScoped<ICommunityLedgerCompletionPostStore, EfCommunityLedgerCompletionPostStore>();
        services.AddScoped<ICommunityLedgerCompletionPostService, CommunityLedgerCompletionPostService>();
        services.AddScoped<I공동수입원장관세사알림Service, 공동수입원장관세사알림Service>();
        services.AddScoped<I공동구매원장관계자알림Service, 공동구매원장관계자알림Service>();
        services.AddScoped<I게시글원장ContextService, 게시글원장ContextService>();
        services.AddSingleton<ICommunityPostOpportunityAnalyzer, CommunityPostOpportunityAnalyzer>();
        services.AddScoped<ICommunityPostOpportunityStore, EfCommunityPostOpportunityStore>();
        services.AddScoped<ICommunityProfessionalEligibilityService, CommunityProfessionalEligibilityService>();
        services.AddScoped<ICommunityPostProfessionalParticipationService, CommunityPostProfessionalParticipationService>();
        services.AddScoped<ICommunityPostOpportunityService, CommunityPostOpportunityService>();
        services.AddScoped<I원장다이어그램실시간알림Service, 원장다이어그램SignalR알림Service>();
        services.AddScoped<I커뮤니티원장업무투영동기화Service, 커뮤니티원장업무투영동기화Service>();
        services.AddScoped<I원장업무투영동기화Handler, 운송원장업무투영Handler>();
        services.AddScoped<I원장업무투영동기화Handler, 입출고원장업무투영Handler>();
        services.AddScoped<I원장업무투영동기화Handler, 음식주문원장업무투영Handler>();
        services.AddScoped<I운송원장Mongo동기화Service, 운송원장Mongo동기화Service>();
        services.AddScoped<I음식마트원장Mongo동기화Service, 음식마트원장Mongo동기화Service>();
        services.AddSingleton<I교육기관제출대기열, Mongo교육기관제출대기열>();
        services.AddScoped<I현장체험활동UseCase, 현장체험활동UseCase>();
        services.AddScoped<I교육과정정의Service, 교육과정정의Service>();
        services.AddScoped<I교육과정참여Service, 교육과정참여Service>();
        services.AddScoped<ITypecast음성카탈로그저장소, EfTypecast음성카탈로그저장소>();
        services.AddScoped<ITypecast음성카탈로그Service, Typecast음성카탈로그Service>();
        services.AddScoped<IYouTube채널감시저장소, EfYouTube채널감시저장소>();
        services.AddScoped<IYouTube채널감시Service, YouTube채널감시Service>();
        services.AddScoped<IYouTube음식상품발견저장소, EfYouTube음식상품발견저장소>();
        services.AddScoped<IYouTube음식상품발견Service, YouTube음식상품발견Service>();
        services.AddScoped<IYouTube영상재료인지Engine, YouTube영상재료인지Engine>();
        services.AddScoped<IYouTube영상재료자동인지Service, YouTube영상재료자동인지Service>();
        services.AddSingleton<IHongikHakdangCardPageParser, HongikHakdangCardPageParser>();
        services.AddSingleton<IHongikHakdangCardImageStore, HongikHakdangCardImageStore>();
        services.AddSingleton<IHongikHakdangCardVariantRenderer, HongikHakdangCardVariantRenderer>();
        services.AddSingleton<IHongikHakdangCardSelectionPolicy, HongikHakdangCardSelectionPolicy>();
        services.AddSingleton<IHongikHakdangCardMediaTokenService, HongikHakdangCardMediaTokenService>();
        services.AddScoped<IHongikHakdangCardRepository, EfHongikHakdangCardRepository>();
        services.AddScoped<IHongikHakdangCardService, HongikHakdangCardService>();
        services.AddScoped<IHongikHakdangCardVariantService, HongikHakdangCardVariantService>();
        services.AddScoped<IHongikHakdangCardDeliveryService, HongikHakdangCardDeliveryService>();
        services.AddScoped<IHongdalMobilePushInstallationService, HongdalMobilePushInstallationService>();
        services.AddSingleton<ICommunityKeywordMatcher, CommunityKeywordMatcher>();
        services.AddSingleton<ICommunityDriverAvailabilityClock, SystemCommunityDriverAvailabilityClock>();
        services.AddSingleton<ICommunityDriverAvailabilityService, CommunityDriverAvailabilityService>();
        services.AddSingleton<ICommunityKeywordNotificationQueue, CommunityKeywordNotificationQueue>();
        services.AddSingleton<ICommunityKeywordNotificationSignal, CommunityKeywordNotificationSignal>();
        services.AddScoped<ICommunityKeywordSubscriptionService, CommunityKeywordSubscriptionService>();
        services.AddScoped<ICommunityKeywordInboxService, CommunityKeywordInboxService>();
        services.AddScoped<ICommunityKeywordNotificationProcessor, CommunityKeywordNotificationProcessor>();
        services.AddSingleton<I커뮤니티게시글음성본문분할기, 커뮤니티게시글음성본문분할기>();
        services.AddSingleton<I커뮤니티게시글음성작업예약Service, 커뮤니티게시글음성작업예약Service>();
        services.AddSingleton<I커뮤니티게시글음성작업신호, 커뮤니티게시글음성작업신호>();
        services.AddScoped<I커뮤니티게시글음성작업Processor, 커뮤니티게시글음성작업Processor>();
        services.AddScoped<I커뮤니티게시글음성조회Service, 커뮤니티게시글음성조회Service>();
        services.AddHostedService<교육기관제출Worker>();
        services.AddHostedService<커뮤니티게시글음성Worker>();
        services.AddHostedService<CommunityKeywordNotificationWorker>();
        services.AddHostedService<커뮤니티원장투영Worker>();
        services.AddHostedService<CommunityGroupPurchaseDemandOutboxWorker>();
        services.AddScoped<I인증UseCase, 인증UseCase>();
        services.AddScoped<I커뮤니티대화UseCase, 커뮤니티대화UseCase>();
        services.AddScoped<I공동구매자동집단화UseCase, 공동구매자동집단화UseCase>();
        services.AddScoped<I공동구매커머스이행계획UseCase, 공동구매커머스이행계획UseCase>();
        services.AddScoped<I공동구매해외선적통관동기화Service, 공동구매해외선적통관동기화Service>();
        services.AddSingleton<I공동구매수입물류정규화Service, 공동구매수입물류정규화Service>();
        services.AddSingleton<IVersionFeatureFlagService, VersionFeatureFlagService>();
        services.AddScoped<IHongdalFoodOrderStore, EfHongdalFoodOrderStore>();
        services.AddSingleton<배차주소Store>();
        services.AddScoped<I음식점주문실시간알림Service, 음식점주문SignalR알림Service>();

        services.AddSingleton<IGoogleCloudStorageService, GoogleCloudStorageService>();
        services.AddSingleton<IDriverLocationStore, DriverLocationStore>();
        services.AddSingleton<IDriverWorkQueueStore, RedisDriverWorkQueueStore>();
        services.AddSingleton<I국내화물운송기사상태Store, Redis국내화물운송기사상태Store>();
        services.AddScoped<I국내화물운송기사상태Service, 국내화물운송기사상태Service>();
        services.AddSingleton<IDriverRejectedRequestStore, RedisDriverRejectedRequestStore>();
        services.AddSingleton<IDriverPushTokenStore, RedisDriverPushTokenStore>();
        services.AddSingleton<I사용자PushTokenStore, Redis사용자PushTokenStore>();
        services.AddSingleton<IDriverRecommendationPushStateStore, RedisDriverRecommendationPushStateStore>();
        services.AddSingleton<IDriverCallScopeStore, RedisDriverCallScopeStore>();
        services.AddSingleton<IDriverNotificationSettingsStore, RedisDriverNotificationSettingsStore>();
        services.AddSingleton<ICommandFileStoragePathResolver, CommandFileStoragePathResolver>();
        services.AddSingleton<IDispatchRecommendationLogStore, DispatchRecommendationLogStore>();
        services.AddSingleton<IDispatchAcceptanceLogStore, DispatchAcceptanceLogStore>();
        services.AddScoped<I배차대기원장전환Service, 배차대기원장전환Service>();
        services.AddScoped<I배차실행인덱스예열Service, 배차실행인덱스예열Service>();
        services.AddScoped<I피킹포장작업투영Service, 피킹포장작업투영Service>();
        services.AddScoped<I알뜰살뜰마트배차대기Service, 알뜰살뜰마트배차대기Service>();
        services.AddScoped<I배차추천알림Service, 배차추천알림Service>();
        services.AddScoped<I상차접근알림Service, 상차접근알림Service>();
        services.AddScoped<ICommand알림Outbox발송Service, Command알림Outbox발송Service>();
        services.AddSingleton<I탐색캠페인이벤트저장소, 탐색캠페인이벤트저장소>();
        services.AddSingleton<IAdminFilePodStore, AdminFilePodStore>();
        services.AddSingleton<I문서관리Store, 문서관리Store>();
        services.AddSingleton<I문서관리Service, 문서관리Service>();
        services.AddSingleton<IHIOPSAIUsageBudgetStore, FileHIOPSAIUsageBudgetStore>();
        services.AddSingleton<이미지프롬프트생성기Resolver, 기본이미지프롬프트생성기Resolver>();
        services.AddScoped<I샘플이미지대상ResolverResolver, 샘플이미지대상ResolverResolver>();
        services.AddSingleton<I이미지프롬프트생성기, 화주상품사진프롬프트생성기>();
        services.AddSingleton<I이미지프롬프트생성기, 기사상차인증사진프롬프트생성기>();
        services.AddSingleton<I이미지프롬프트생성기, 기사배차완료인증사진프롬프트생성기>();
        services.AddSingleton<I이미지프롬프트생성기, 음식상품썸네일프롬프트생성기>();
        services.AddSingleton<I이미지프롬프트생성기, 주문후기사진프롬프트생성기>();
        services.AddSingleton<I이미지프롬프트생성기, 상품상세페이지이미지프롬프트생성기>();
        services.AddScoped<I샘플이미지대상Resolver, 판매상품샘플이미지대상Resolver>();
        services.AddScoped<I샘플이미지대상Resolver, 상품상세이미지생성작업대상Resolver>();
        services.AddScoped<I샘플이미지생성Service, 샘플이미지생성Service>();
        services.AddScoped<I배차추천경로Service, 배차추천경로Service>();
        services.AddScoped<I용달기사프로필UseCase, 용달기사프로필UseCase>();
        services.AddScoped<I기사알림UseCase, 기사알림UseCase>();
        services.AddScoped<I기사운송일정구성Service, 기사운송일정구성Service>();
        services.AddScoped<I운송일정삽입평가Service, 운송일정삽입평가Service>();
        services.AddScoped<I픽업하차경로최적화Service, 픽업하차경로최적화Service>();
        services.AddScoped<I음식멀티배차조합AIService, 규칙기반음식멀티배차조합AIService>();
        services.AddScoped<I음식멀티배차조합Service, 음식멀티배차조합Service>();
        services.AddScoped<I배차추천판정Service, 배차추천판정Service>();
        services.AddScoped<I배차추천평가Service, 배차추천평가Service>();
        services.AddSingleton<I배달권실행공간Store, InMemory배달권실행공간Store>();
        services.AddScoped<I배달권기반배차조율계획Service, 배달권기반배차조율계획Service>();
        services.AddScoped<I배달권기반배차조율실행Service, 배달권기반배차조율실행Service>();
        services.AddScoped<I국내화물배차조율입력Factory, 국내화물배차조율입력Factory>();
        services.AddSingleton<File배차AI판단사례LedgerStore>();
        services.AddSingleton<I배차AI판단사례LedgerStore>(sp => sp.GetRequiredService<File배차AI판단사례LedgerStore>());
        services.AddSingleton<I배차AI판단근거Source>(sp => sp.GetRequiredService<File배차AI판단사례LedgerStore>());
        services.AddScoped<I배차AI판단근거조회Service, 규칙기반배차AI판단근거조회Service>();
        services.AddScoped<I운송의뢰수익묶음AIService, 규칙기반운송의뢰수익묶음AIService>();
        services.AddScoped<I운송의뢰수익묶음Service, 운송의뢰수익묶음Service>();
        services.AddScoped<I국내화물기사배정AIService, 규칙기반국내화물기사배정AIService>();
        services.AddScoped<I국내화물배차조율Service, 국내화물배차조율Service>();
        services.AddScoped<I국내화물배차조율적용Service, 국내화물배차조율적용Service>();
        services.AddScoped<I국내화물배차조율실행Service, 국내화물배차조율실행Service>();
        services.AddScoped<IDomesticCargoDispatchAIReviewService, DomesticCargoDispatchAIReviewService>();
        services.AddScoped<IFoodDeliveryDispatchAIReviewService, FoodDeliveryDispatchAIReviewService>();
        services.AddScoped<I배차업무정책, 용달운송배차업무정책>();
        services.AddScoped<I배차업무정책, 음식배달배차업무정책>();
        services.AddScoped<I운송의뢰배차원천분류Service, 운송의뢰배차원천분류Service>();
        services.AddScoped<I운송의뢰배차대기Service, 운송의뢰배차대기Service>();
        services.AddScoped<I화물용달배차흐름Resolver, 화물용달배차흐름Resolver>();
        services.AddScoped<I음식배달배차흐름Resolver, 음식배달배차흐름Resolver>();
        services.AddScoped<화물용달배차엔진>();
        services.AddScoped<음식배달배차엔진>();
        services.AddScoped<I운송의뢰배차엔진>(sp => sp.GetRequiredService<화물용달배차엔진>());
        services.AddScoped<I운송의뢰배차엔진>(sp => sp.GetRequiredService<음식배달배차엔진>());
        services.AddScoped<I배차추천후보선정Service, 배차추천후보선정Service>();
        services.AddScoped<I공개배차Service, 공개배차Service>();
        services.AddSingleton<차량적재추천Engine>();
        services.AddSingleton<차량혼적순서Engine>();
        services.AddScoped<I차량적재추천Service, 차량적재추천Service>();
        services.AddScoped<Hongdal.Application.Driver.Recommendation.I기사배차추천UseCase, Hongdal.Application.Driver.Recommendation.기사배차추천UseCase>();
        services.AddScoped<홍달.Services.Dispatch.Recommendation.I차량화물적합성Service, 홍달.Services.Dispatch.Recommendation.차량화물적합성Service>();
        services.AddScoped<Hongdal.Application.Shipper.Request.I차량추천Service, Hongdal.Application.Shipper.Request.차량추천Service>();
        services.AddScoped<Hongdal.Application.Shipper.Request.I화주운송의뢰추천Service, Hongdal.Application.Shipper.Request.화주운송의뢰추천Service>();
        services.AddScoped<Hongdal.Application.Shipper.Request.I화주운송의뢰일괄등록파서Service, Hongdal.Application.Shipper.Request.화주운송의뢰일괄등록파서Service>();
        services.AddScoped<Hongdal.Application.Shipper.Request.I화주운송기준운임Service, Hongdal.Application.Shipper.Request.화주운송기준운임Service>();
        services.AddScoped<Hongdal.Application.Shipper.Request.I화주운송요금정책검토Service, Hongdal.Application.Shipper.Request.화주운송요금정책검토Service>();
        services.AddScoped<Hongdal.Application.Shipper.Request.I화주운송의뢰UseCase, Hongdal.Application.Shipper.Request.화주운송의뢰UseCase>();
        services.AddScoped<I판매상품샘플시드Service, 판매상품샘플시드Service>();
        services.AddScoped<I배차추천Service, 화물배차추천Service>();
        services.AddScoped<I음식배차추천Service, 음식배차추천Service>();
        services.AddScoped<I음식배달기사업무Service, 음식배달기사업무Service>();
        services.AddScoped<I운행중배차추천Service, 운행중배차추천Service>();
        services.AddScoped<I비운행중배차추천Service, 비운행중배차추천Service>();
        services.AddScoped<I기사운송상태전이Service, 기사운송상태전이Service>();
        services.AddScoped<I탐색대상추천Service, 탐색대상추천Service>();
        services.AddScoped<I탐색캠페인상태전이Service, 탐색캠페인상태전이Service>();
        services.AddScoped<INationalDispatchRequestService, NationalDispatchRequestService>();
        services.AddScoped<I기사월정산Service, 기사월정산Service>();
        services.AddScoped<IPlatformProfitReturnService, PlatformProfitReturnService>();
        services.AddHostedService<배차실행인덱스예열HostedService>();
        services.AddHostedService<KieAiTaskPollingWorker>();

        return services;
    }
}
