<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
	<TargetFramework>net10.0</TargetFramework>
	<Nullable>enable</Nullable>
	<ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
	<ProjectReference Include="..\Hongdal.Contracts\Hongdal.Contracts.csproj" />
	<PackageReference Include="Microsoft.AspNetCore.OpenApi" />
	<PackageReference Include="Microsoft.OpenApi" />
	<PackageReference Include="Serilog.AspNetCore" />
	<PackageReference Include="Serilog.Sinks.Console" />
	<PackageReference Include="Serilog.Sinks.File" />
  </ItemGroup>

</Project>
