#!/bin/sh
set -eu

validate_sql_value() {
    value="$1"
    name="$2"
    case "$value" in
        ""|*[!A-Za-z0-9_.@%-]*)
            echo "$name must use only A-Z, a-z, 0-9, _, ., @, %, or -." >&2
            exit 1
            ;;
    esac
}

validate_sql_value "$SSALDDEL_SIMULATION_PUBLIC_DATA_USER" "SSALDDEL_SIMULATION_PUBLIC_DATA_USER"
validate_sql_value "$SSALDDEL_SIMULATION_PUBLIC_DATA_PASSWORD" "SSALDDEL_SIMULATION_PUBLIC_DATA_PASSWORD"
validate_sql_value "$SSALDDEL_SIMULATION_PUBLIC_DATA_DATABASE" "SSALDDEL_SIMULATION_PUBLIC_DATA_DATABASE"
validate_sql_value "$SSALDDEL_SIMULATION_WORLD_USER" "SSALDDEL_SIMULATION_WORLD_USER"
validate_sql_value "$SSALDDEL_SIMULATION_WORLD_PASSWORD" "SSALDDEL_SIMULATION_WORLD_PASSWORD"

case "$SSALDDEL_SIMULATION_PUBLIC_DATA_PASSWORD:$SSALDDEL_SIMULATION_WORLD_PASSWORD" in
    *YOUR_LOCAL_*|*replace-with-*)
        echo "Replace both Simulation database password placeholders before startup." >&2
        exit 1
        ;;
esac

mysql --protocol=tcp --host=mysql --user=root --password="$MYSQL_ROOT_PASSWORD" <<SQL
CREATE DATABASE IF NOT EXISTS \`ssalddel_simulation_world\`
  CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE USER IF NOT EXISTS '$SSALDDEL_SIMULATION_PUBLIC_DATA_USER'@'%'
  IDENTIFIED BY '$SSALDDEL_SIMULATION_PUBLIC_DATA_PASSWORD';
ALTER USER '$SSALDDEL_SIMULATION_PUBLIC_DATA_USER'@'%'
  IDENTIFIED BY '$SSALDDEL_SIMULATION_PUBLIC_DATA_PASSWORD';
REVOKE ALL PRIVILEGES, GRANT OPTION
  FROM '$SSALDDEL_SIMULATION_PUBLIC_DATA_USER'@'%';
GRANT SELECT ON \`$SSALDDEL_SIMULATION_PUBLIC_DATA_DATABASE\`.*
  TO '$SSALDDEL_SIMULATION_PUBLIC_DATA_USER'@'%';

CREATE USER IF NOT EXISTS '$SSALDDEL_SIMULATION_WORLD_USER'@'%'
  IDENTIFIED BY '$SSALDDEL_SIMULATION_WORLD_PASSWORD';
ALTER USER '$SSALDDEL_SIMULATION_WORLD_USER'@'%'
  IDENTIFIED BY '$SSALDDEL_SIMULATION_WORLD_PASSWORD';
REVOKE ALL PRIVILEGES, GRANT OPTION
  FROM '$SSALDDEL_SIMULATION_WORLD_USER'@'%';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, ALTER, INDEX, DROP, REFERENCES
  ON \`ssalddel_simulation_world\`.*
  TO '$SSALDDEL_SIMULATION_WORLD_USER'@'%';

FLUSH PRIVILEGES;
SQL

echo "Simulation public-data reader and world database grants are ready."
