<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	<TargetFramework>net10.0</TargetFramework>
	<Nullable>enable</Nullable>
	<ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
	<FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
	<ProjectReference Include="..\Ssalddel.Contracts\Ssalddel.Contracts.csproj" />
	<ProjectReference Include="..\Ssalddel.Domain\Ssalddel.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
	<PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" />
	<PackageReference Include="Microsoft.EntityFrameworkCore" />
	<PackageReference Include="Pomelo.EntityFrameworkCore.MySql" />
  </ItemGroup>

</Project>
