<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MudBlazor" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Hongdal.Contracts\Hongdal.Contracts.csproj" />
    <ProjectReference Include="..\Hongdal.BackOffice.Client\Hongdal.BackOffice.Client.csproj" />
    <ProjectReference Include="..\Hongdal.Ui.Common\Hongdal.Ui.Common.csproj" />
  </ItemGroup>

</Project>
