// <auto-generated />
using System;
using Ssalddel.Infrastructure.Persistence.TraditionalMarkets;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Ssalddel.Infrastructure.Persistence.TraditionalMarkets.Migrations
{
    [DbContext(typeof(TraditionalMarketDbContext))]
    [Migration("20260714124059_AddTraditionalMarketPublicDataModule")]
    partial class AddTraditionalMarketPublicDataModule
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Ssalddel.Domain.TraditionalMarkets.TraditionalMarket", b =>
                {
                    b.Property<string>("MarketCode")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("CityCounty")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("LastSyncedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LotNumberAddress")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("MarketType")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.Property<string>("RoadAddress")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("SourceDatasetKey")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<string>("SourceHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<DateOnly>("SourceReferenceDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.HasKey("MarketCode");

                    b.HasIndex("Name");

                    b.HasIndex("SourceDatasetKey", "SourceReferenceDate");

                    b.HasIndex("Province", "CityCounty", "IsActive");

                    b.ToTable("public_data_traditional_markets", (string)null);
                });

            modelBuilder.Entity("Ssalddel.Domain.TraditionalMarkets.TraditionalMarketSyncRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("DeactivatedCount")
                        .HasColumnType("int");

                    b.Property<string>("ErrorMessage")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<int>("FetchedCount")
                        .HasColumnType("int");

                    b.Property<int>("InsertedCount")
                        .HasColumnType("int");

                    b.Property<string>("SourceDatasetKey")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<DateOnly>("SourceReferenceDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<int>("UnchangedCount")
                        .HasColumnType("int");

                    b.Property<int>("UpdatedCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.HasIndex("SourceDatasetKey", "StartedAtUtc");

                    b.ToTable("public_data_traditional_market_sync_runs", (string)null);
                });

            modelBuilder.Entity("Ssalddel.Domain.TraditionalMarkets.TraditionalMarket", b =>
                {
                    b.OwnsOne("Ssalddel.Domain.TraditionalMarkets.TraditionalMarketFacilities", "Facilities", b1 =>
                        {
                            b1.Property<string>("TraditionalMarketMarketCode")
                                .HasColumnType("varchar(20)");

                            b1.Property<bool?>("HasAed")
                                .HasColumnType("tinyint(1)")
                                .HasColumnName("has_aed");

                            b1.Property<bool?>("HasArcade")
                                .HasColumnType("tinyint(1)")
                                .HasColumnName("has_arcade");

                            b1.Property<bool?>("HasBicycleStorage")
                                .HasColumnType("tinyint(1)")
                                .HasColumnName("has_bicycle_storage");

                            b1.Property<bool?>("HasBroadcastCenter")
                                .HasColumnType("tinyint(1)")
                                .HasColumnName("has_broadcast_center");

                            b1.Property<bool?>("HasCallCenter")
                                .HasColumnType("tinyint(1)")
                                .HasColumnName("has_call_center");

                            b1.Property<bool?>("HasChildrenPlayroom")
                                .HasColumnType("tinyint(1)")
                                .HasColumnName("has_children_playroom");

                            b1.Property<bool?>("HasCultureClassroom")
                                .HasColumnType("tinyint(1)")
                                .HasColumnName("has_culture_classroom");

                            b1.Property<bool?>("HasCustomerLounge")
                                .HasColumnType("tinyint(1)")
                                .HasColumnName("has_customer_lounge");

                            b1.Property<bool?>("HasCustomerPath")
                                .HasColumnType("tinyint(1)")
                                .HasColumnName("has_customer_path");

                            b1.Property<bool?>("HasCustomerSupportCenter")
                                .HasColumnType("tinyint(1)")
                                .HasColumnName("has_customer_support_center");

                            b1.Property<bool?>("HasDedicatedParking")
                                .HasColumnType("tinyint(1)")
                                .HasColumnName("has_dedicated_parking");

                            b1.Property<bool?>("HasElevatorOrEscalator")
                                .HasColumnType("tinyint(1)")
                                .HasColumnName("has_elevator_or_escalator");

                            b1.Property<bool?>("HasFireDetector")
                                .HasColumnType("tinyint(1)")
                                .HasColumnName("has_fire_detector");

                            b1.Property<bool?>("HasForeignVisitorCenter")
                                .HasColumnType("tinyint(1)")
                                .HasColumnName("has_foreign_visitor_center");

                            b1.Property<bool?>("HasLibrary")
                                .HasColumnType("tinyint(1)")
                                .HasColumnName("has_library");

                            b1.Property<bool?>("HasLocker")
                                .HasColumnType("tinyint(1)")
                                .HasColumnName("has_locker");

                            b1.Property<bool?>("HasMeetingRoom")
                                .HasColumnType("tinyint(1)")
                                .HasColumnName("has_meeting_room");

                            b1.Property<bool?>("HasNursingCenter")
                                .HasColumnType("tinyint(1)")
                                .HasColumnName("has_nursing_center");

                            b1.Property<bool?>("HasSharedLogisticsWarehouse")
                                .HasColumnType("tinyint(1)")
                                .HasColumnName("has_shared_logistics_warehouse");

                            b1.Property<bool?>("HasShoppingCart")
                                .HasColumnType("tinyint(1)")
                                .HasColumnName("has_shopping_cart");

                            b1.Property<bool?>("HasSportsFacility")
                                .HasColumnType("tinyint(1)")
                                .HasColumnName("has_sports_facility");

                            b1.Property<bool?>("HasSprinkler")
                                .HasColumnType("tinyint(1)")
                                .HasColumnName("has_sprinkler");

                            b1.Property<bool?>("HasTrainingRoom")
                                .HasColumnType("tinyint(1)")
                                .HasColumnName("has_training_room");

                            b1.HasKey("TraditionalMarketMarketCode");

                            b1.ToTable("public_data_traditional_markets");

                            b1.WithOwner()
                                .HasForeignKey("TraditionalMarketMarketCode");
                        });

                    b.Navigation("Facilities")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
