// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Ssalddel.Infrastructure.Persistence.TraditionalMarkets;

#nullable disable

namespace Ssalddel.Infrastructure.Persistence.TraditionalMarkets.Migrations
{
    [DbContext(typeof(TraditionalMarketDbContext))]
    [Migration("20260802074827_AddTraditionalMarketMapAnchors")]
    partial class AddTraditionalMarketMapAnchors
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Ssalddel.Domain.TraditionalMarkets.TraditionalMarket", b =>
                {
                    b.Property<string>("MarketCode")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("CityCounty")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("LastSyncedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LotNumberAddress")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("MarketType")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.Property<string>("RoadAddress")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("SourceDatasetKey")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<string>("SourceHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<DateOnly>("SourceReferenceDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.HasKey("MarketCode");

                    b.HasIndex("Name");

                    b.HasIndex("SourceDatasetKey", "SourceReferenceDate");

                    b.HasIndex("Province", "CityCounty", "IsActive");

                    b.ToTable("public_data_traditional_markets", (string)null);
                });

            modelBuilder.Entity("Ssalddel.Domain.TraditionalMarkets.TraditionalMarketLogisticsHub", b =>
                {
                    b.Property<string>("MarketCode")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("DailyGroupPurchaseCapacity")
                        .HasColumnType("int");

                    b.Property<bool>("HasOperatorConsent")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal?>("MapLatitude")
                        .HasPrecision(10, 7)
                        .HasColumnType("decimal(10,7)");

                    b.Property<string>("MapLocationPrecisionCode")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.Property<string>("MapLocationSourceHref")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("MapLocationSourceName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)");

                    b.Property<DateTime?>("MapLocationVerifiedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("MapLocationVerifiedByUserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("varchar(450)");

                    b.Property<decimal?>("MapLongitude")
                        .HasPrecision(10, 7)
                        .HasColumnType("decimal(10,7)");

                    b.Property<string>("OperatingNotes")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<DateTime?>("OperatorConsentedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("OperatorOrganizationName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)");

                    b.Property<string>("PickupWindow")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)");

                    b.Property<string>("ReceivingWindow")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.Property<decimal>("ServiceRadiusKm")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)");

                    b.Property<DateTime?>("SiteVerifiedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("SiteVerifiedByUserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("varchar(450)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<DateTime>("StatusChangedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("StatusReason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<bool>("SupportsBulkReceiving")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("SupportsFrozenStorage")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("SupportsLastMileDelivery")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("SupportsRefrigeratedStorage")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("SupportsResidentPickup")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("SupportsSorting")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedByUserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("varchar(450)");

                    b.HasKey("MarketCode");

                    b.HasIndex("Status");

                    b.HasIndex("Status", "MapLocationVerifiedAtUtc");

                    b.HasIndex("Status", "UpdatedAtUtc");

                    b.ToTable("traditional_market_logistics_hubs", (string)null);
                });

            modelBuilder.Entity("Ssalddel.Domain.TraditionalMarkets.TraditionalMarketSyncRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("DeactivatedCount")
                        .HasColumnType("int");

                    b.Property<string>("ErrorMessage")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<int>("FetchedCount")
                        .HasColumnType("int");

                    b.Property<int>("InsertedCount")
                        .HasColumnType("int");

                    b.Property<string>("SourceDatasetKey")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<DateOnly>("SourceReferenceDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<int>("UnchangedCount")
                        .HasColumnType("int");

                    b.Property<int>("UpdatedCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.HasIndex("SourceDatasetKey", "StartedAtUtc");

                    b.ToTable("public_data_traditional_market_sync_runs", (string)null);
                });

            modelBuilder.Entity("Ssalddel.Domain.TraditionalMarkets.전통시장교역안건", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("varchar(450)");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("교역방향")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("TradeDirection");

                    b.Property<string>("목적지국가")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("DestinationCountry");

                    b.Property<string>("물류조건")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)")
                        .HasColumnName("LogisticsTerms");

                    b.Property<string>("상인회측결정")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("MerchantDecision");

                    b.Property<DateTime?>("상인회측결정AtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("MerchantDecidedAtUtc");

                    b.Property<string>("상인회측의견")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)")
                        .HasColumnName("MerchantDecisionMemo");

                    b.Property<string>("상태")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("Status");

                    b.Property<string>("수량단위")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("QuantityUnit");

                    b.Property<string>("아파트측결정")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("ApartmentDecision");

                    b.Property<DateTime?>("아파트측결정AtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("ApartmentDecidedAtUtc");

                    b.Property<string>("아파트측의견")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)")
                        .HasColumnName("ApartmentDecisionMemo");

                    b.Property<decimal?>("예상금액")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("EstimatedAmount");

                    b.Property<string>("원산지국가")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("OriginCountry");

                    b.Property<string>("제안내용")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("varchar(4000)")
                        .HasColumnName("ProposalText");

                    b.Property<bool>("통관검토필요여부")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("RequiresCustomsReview");

                    b.Property<string>("통화Code")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("varchar(3)")
                        .HasColumnName("CurrencyCode");

                    b.Property<string>("품목명")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("ItemName");

                    b.Property<string>("품목설명")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)")
                        .HasColumnName("ItemDescription");

                    b.Property<Guid>("협의체Id")
                        .HasColumnType("char(36)")
                        .HasColumnName("CouncilId");

                    b.Property<decimal>("희망수량")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)")
                        .HasColumnName("RequestedQuantity");

                    b.Property<DateOnly?>("희망시작일")
                        .HasColumnType("date")
                        .HasColumnName("DesiredStartDate");

                    b.Property<DateOnly?>("희망종료일")
                        .HasColumnType("date")
                        .HasColumnName("DesiredEndDate");

                    b.HasKey("Id");

                    b.HasIndex("협의체Id", "상태", "UpdatedAtUtc");

                    b.ToTable("traditional_market_trade_agendas", (string)null);
                });

            modelBuilder.Entity("Ssalddel.Domain.TraditionalMarkets.전통시장생활권협의체", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)")
                        .HasColumnName("Id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("varchar(450)");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("상인회대표UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("varchar(450)")
                        .HasColumnName("MerchantRepresentativeUserId");

                    b.Property<string>("상인회대표명")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("MerchantRepresentativeName");

                    b.Property<DateTime?>("상인회대표수락AtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("MerchantRepresentativeAcceptedAtUtc");

                    b.Property<string>("상인회명")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)")
                        .HasColumnName("MerchantAssociationName");

                    b.Property<string>("상태")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("Status");

                    b.Property<string>("시장Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("MarketCode");

                    b.Property<string>("아파트단지명")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)")
                        .HasColumnName("ApartmentCommunityName");

                    b.Property<string>("아파트대표UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("varchar(450)")
                        .HasColumnName("ApartmentRepresentativeUserId");

                    b.Property<string>("아파트대표명")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("ApartmentRepresentativeName");

                    b.Property<DateTime?>("아파트대표수락AtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("ApartmentRepresentativeAcceptedAtUtc");

                    b.Property<string>("아파트주소")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("ApartmentAddress");

                    b.Property<string>("협의목적")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)")
                        .HasColumnName("Purpose");

                    b.Property<string>("협의체명")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)")
                        .HasColumnName("CouncilName");

                    b.HasKey("Id");

                    b.HasIndex("상인회대표UserId", "상태");

                    b.HasIndex("시장Code", "상태");

                    b.HasIndex("아파트대표UserId", "상태");

                    b.ToTable("traditional_market_neighborhood_councils", (string)null);
                });

            modelBuilder.Entity("Ssalddel.Domain.TraditionalMarkets.TraditionalMarket", b =>
                {
                    b.OwnsOne("Ssalddel.Domain.TraditionalMarkets.TraditionalMarketFacilities", "Facilities", b1 =>
                        {
                            b1.Property<string>("TraditionalMarketMarketCode")
                                .HasColumnType("varchar(20)");

                            b1.Property<bool?>("HasAed")
                                .HasColumnType("tinyint(1)")
                                .HasColumnName("has_aed");

                            b1.Property<bool?>("HasArcade")
                                .HasColumnType("tinyint(1)")
                                .HasColumnName("has_arcade");

                            b1.Property<bool?>("HasBicycleStorage")
                                .HasColumnType("tinyint(1)")
                                .HasColumnName("has_bicycle_storage");

                            b1.Property<bool?>("HasBroadcastCenter")
                                .HasColumnType("tinyint(1)")
                                .HasColumnName("has_broadcast_center");

                            b1.Property<bool?>("HasCallCenter")
                                .HasColumnType("tinyint(1)")
                                .HasColumnName("has_call_center");

                            b1.Property<bool?>("HasChildrenPlayroom")
                                .HasColumnType("tinyint(1)")
                                .HasColumnName("has_children_playroom");

                            b1.Property<bool?>("HasCultureClassroom")
                                .HasColumnType("tinyint(1)")
                                .HasColumnName("has_culture_classroom");

                            b1.Property<bool?>("HasCustomerLounge")
                                .HasColumnType("tinyint(1)")
                                .HasColumnName("has_customer_lounge");

                            b1.Property<bool?>("HasCustomerPath")
                                .HasColumnType("tinyint(1)")
                                .HasColumnName("has_customer_path");

                            b1.Property<bool?>("HasCustomerSupportCenter")
                                .HasColumnType("tinyint(1)")
                                .HasColumnName("has_customer_support_center");

                            b1.Property<bool?>("HasDedicatedParking")
                                .HasColumnType("tinyint(1)")
                                .HasColumnName("has_dedicated_parking");

                            b1.Property<bool?>("HasElevatorOrEscalator")
                                .HasColumnType("tinyint(1)")
                                .HasColumnName("has_elevator_or_escalator");

                            b1.Property<bool?>("HasFireDetector")
                                .HasColumnType("tinyint(1)")
                                .HasColumnName("has_fire_detector");

                            b1.Property<bool?>("HasForeignVisitorCenter")
                                .HasColumnType("tinyint(1)")
                                .HasColumnName("has_foreign_visitor_center");

                            b1.Property<bool?>("HasLibrary")
                                .HasColumnType("tinyint(1)")
                                .HasColumnName("has_library");

                            b1.Property<bool?>("HasLocker")
                                .HasColumnType("tinyint(1)")
                                .HasColumnName("has_locker");

                            b1.Property<bool?>("HasMeetingRoom")
                                .HasColumnType("tinyint(1)")
                                .HasColumnName("has_meeting_room");

                            b1.Property<bool?>("HasNursingCenter")
                                .HasColumnType("tinyint(1)")
                                .HasColumnName("has_nursing_center");

                            b1.Property<bool?>("HasSharedLogisticsWarehouse")
                                .HasColumnType("tinyint(1)")
                                .HasColumnName("has_shared_logistics_warehouse");

                            b1.Property<bool?>("HasShoppingCart")
                                .HasColumnType("tinyint(1)")
                                .HasColumnName("has_shopping_cart");

                            b1.Property<bool?>("HasSportsFacility")
                                .HasColumnType("tinyint(1)")
                                .HasColumnName("has_sports_facility");

                            b1.Property<bool?>("HasSprinkler")
                                .HasColumnType("tinyint(1)")
                                .HasColumnName("has_sprinkler");

                            b1.Property<bool?>("HasTrainingRoom")
                                .HasColumnType("tinyint(1)")
                                .HasColumnName("has_training_room");

                            b1.HasKey("TraditionalMarketMarketCode");

                            b1.ToTable("public_data_traditional_markets");

                            b1.WithOwner()
                                .HasForeignKey("TraditionalMarketMarketCode");
                        });

                    b.Navigation("Facilities")
                        .IsRequired();
                });

            modelBuilder.Entity("Ssalddel.Domain.TraditionalMarkets.TraditionalMarketLogisticsHub", b =>
                {
                    b.HasOne("Ssalddel.Domain.TraditionalMarkets.TraditionalMarket", null)
                        .WithOne()
                        .HasForeignKey("Ssalddel.Domain.TraditionalMarkets.TraditionalMarketLogisticsHub", "MarketCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Ssalddel.Domain.TraditionalMarkets.전통시장교역안건", b =>
                {
                    b.HasOne("Ssalddel.Domain.TraditionalMarkets.전통시장생활권협의체", "협의체")
                        .WithMany("안건")
                        .HasForeignKey("협의체Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("협의체");
                });

            modelBuilder.Entity("Ssalddel.Domain.TraditionalMarkets.전통시장생활권협의체", b =>
                {
                    b.HasOne("Ssalddel.Domain.TraditionalMarkets.TraditionalMarket", null)
                        .WithMany()
                        .HasForeignKey("시장Code")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Ssalddel.Domain.TraditionalMarkets.전통시장생활권협의체", b =>
                {
                    b.Navigation("안건");
                });
#pragma warning restore 612, 618
        }
    }
}
