// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Ssalddel.Simulation.Persistence;

#nullable disable

namespace Ssalddel.Simulation.Persistence.Migrations.WorldDerivation
{
    [DbContext(typeof(SimulationWorld파생DbContext))]
    [Migration("20260813020959_Unity공간변환타일산출물원장추가")]
    partial class Unity공간변환타일산출물원장추가
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Ssalddel.Simulation.Persistence.SimulationWorldUnity공간변환Entity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("식별번호");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AreaSetStableId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("영역묶음고유식별자");

                    b.Property<string>("AxisMappingCode")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("좌표축변환코드");

                    b.Property<decimal>("HorizontalScale")
                        .HasPrecision(12, 6)
                        .HasColumnType("decimal(12,6)")
                        .HasColumnName("수평축척률");

                    b.Property<decimal>("MetersPerUnityUnit")
                        .HasPrecision(12, 6)
                        .HasColumnType("decimal(12,6)")
                        .HasColumnName("Unity단위당미터");

                    b.Property<decimal?>("OriginEastingMeters")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("Unity원점동쪽좌표미터");

                    b.Property<decimal?>("OriginNorthingMeters")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("Unity원점북쪽좌표미터");

                    b.Property<string>("ProfileHashSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("변환ProfileSHA256");

                    b.Property<decimal?>("ReferenceElevationMeters")
                        .HasPrecision(12, 4)
                        .HasColumnType("decimal(12,4)")
                        .HasColumnName("기준표고미터");

                    b.Property<string>("RuleRevision")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("변환규칙개정번호");

                    b.Property<long>("RunId")
                        .HasColumnType("bigint")
                        .HasColumnName("파생실행식별번호");

                    b.Property<string>("SourceCrsCode")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("원본좌표계코드");

                    b.Property<string>("StableId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("공간변환고유식별자");

                    b.Property<string>("StatusCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("변환상태코드");

                    b.Property<decimal>("VerticalExaggeration")
                        .HasPrecision(12, 6)
                        .HasColumnType("decimal(12,6)")
                        .HasColumnName("높이과장률");

                    b.HasKey("Id");

                    b.HasIndex("RunId", "StableId")
                        .IsUnique();

                    b.ToTable("시뮬레이션월드_Unity공간변환Profile", (string)null);
                });

            modelBuilder.Entity("Ssalddel.Simulation.Persistence.SimulationWorldUnity산출물Entity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("식별번호");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ArtifactHashSha256")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("산출물SHA256");

                    b.Property<string>("ArtifactKindCode")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("산출물종류코드");

                    b.Property<string>("BoundaryVertexHashSha256")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("경계정점SHA256");

                    b.Property<int?>("EstimatedDrawCallCount")
                        .HasColumnType("int")
                        .HasColumnName("예상DrawCall수");

                    b.Property<string>("LodCode")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("세부표현단계코드");

                    b.Property<int?>("MaterialSlotCount")
                        .HasColumnType("int")
                        .HasColumnName("재질슬롯수");

                    b.Property<long>("RunId")
                        .HasColumnType("bigint")
                        .HasColumnName("파생실행식별번호");

                    b.Property<string>("StableId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("산출물고유식별자");

                    b.Property<string>("StatusCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("생성상태코드");

                    b.Property<string>("StorageObjectKey")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("산출물보관객체키");

                    b.Property<string>("TileManifestStableId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("타일Manifest고유식별자");

                    b.Property<long?>("TriangleCount")
                        .HasColumnType("bigint")
                        .HasColumnName("삼각형수");

                    b.Property<long?>("VertexCount")
                        .HasColumnType("bigint")
                        .HasColumnName("정점수");

                    b.HasKey("Id");

                    b.HasIndex("RunId", "StableId")
                        .IsUnique();

                    b.HasIndex("RunId", "TileManifestStableId");

                    b.ToTable("시뮬레이션월드_Unity산출물", (string)null);
                });

            modelBuilder.Entity("Ssalddel.Simulation.Persistence.SimulationWorldUnity타일ManifestEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("식별번호");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal>("HaloMeters")
                        .HasPrecision(12, 4)
                        .HasColumnType("decimal(12,4)")
                        .HasColumnName("여유영역미터");

                    b.Property<string>("InputFingerprintSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("입력지문SHA256");

                    b.Property<int>("Level")
                        .HasColumnType("int")
                        .HasColumnName("타일단계");

                    b.Property<string>("ManifestHashSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("ManifestSHA256");

                    b.Property<decimal>("MaxEastingMeters")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("최대동쪽좌표미터");

                    b.Property<decimal>("MaxNorthingMeters")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("최대북쪽좌표미터");

                    b.Property<decimal>("MinEastingMeters")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("최소동쪽좌표미터");

                    b.Property<decimal>("MinNorthingMeters")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("최소북쪽좌표미터");

                    b.Property<long>("RunId")
                        .HasColumnType("bigint")
                        .HasColumnName("파생실행식별번호");

                    b.Property<decimal>("SizeMeters")
                        .HasPrecision(12, 4)
                        .HasColumnType("decimal(12,4)")
                        .HasColumnName("타일크기미터");

                    b.Property<string>("StableId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("타일Manifest고유식별자");

                    b.Property<string>("StatusCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("생성상태코드");

                    b.Property<string>("TileKey")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("타일키");

                    b.Property<string>("TransformProfileStableId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("공간변환고유식별자");

                    b.HasKey("Id");

                    b.HasIndex("RunId", "StableId")
                        .IsUnique();

                    b.HasIndex("RunId", "TileKey");

                    b.ToTable("시뮬레이션월드_Unity타일Manifest", (string)null);
                });

            modelBuilder.Entity("Ssalddel.Simulation.Persistence.SimulationWorld건물배치Entity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("식별번호");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AreaNodeStableId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("영역노드고유식별자");

                    b.Property<string>("BuildingCategoryCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("건물분류코드");

                    b.Property<string>("BuildingNodeStableId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("건물노드고유식별자");

                    b.Property<string>("EvidenceKindCode")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("근거종류코드");

                    b.Property<int>("FloorCount")
                        .HasColumnType("int")
                        .HasColumnName("표현층수");

                    b.Property<decimal?>("FootprintAreaSquareMeters")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("건물바닥면적제곱미터");

                    b.Property<decimal?>("HeightMeters")
                        .HasPrecision(12, 4)
                        .HasColumnType("decimal(12,4)")
                        .HasColumnName("높이미터");

                    b.Property<string>("PlacementBasisCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("배치근거코드");

                    b.Property<decimal>("PositionX")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("위치X");

                    b.Property<decimal>("PositionY")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("위치Y");

                    b.Property<decimal>("PositionZ")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("위치Z");

                    b.Property<bool>("PresentationOnly")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("표현전용여부");

                    b.Property<decimal>("RotationY")
                        .HasPrecision(9, 4)
                        .HasColumnType("decimal(9,4)")
                        .HasColumnName("Y축회전");

                    b.Property<long>("RunId")
                        .HasColumnType("bigint")
                        .HasColumnName("파생실행식별번호");

                    b.Property<string>("StableId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("건물배치고유식별자");

                    b.Property<string>("VisualFamilyCode")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("시각Family코드");

                    b.HasKey("Id");

                    b.HasIndex("RunId", "StableId")
                        .IsUnique();

                    b.ToTable("시뮬레이션월드_건물배치계획", (string)null);
                });

            modelBuilder.Entity("Ssalddel.Simulation.Persistence.SimulationWorld그래픽표현Entity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("식별번호");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal>("AmbientOcclusionStrength")
                        .HasPrecision(5, 4)
                        .HasColumnType("decimal(5,4)")
                        .HasColumnName("주변광차폐강도");

                    b.Property<string>("BackgroundProfileKey")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)")
                        .HasColumnName("배경Profile키");

                    b.Property<bool>("CastShadows")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("그림자투사여부");

                    b.Property<string>("ColorPaletteKey")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("색조팔레트키");

                    b.Property<decimal>("ContactShadowStrength")
                        .HasPrecision(5, 4)
                        .HasColumnType("decimal(5,4)")
                        .HasColumnName("접지그림자강도");

                    b.Property<string>("LightingProfileKey")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)")
                        .HasColumnName("조명Profile키");

                    b.Property<string>("LodCode")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("세부표현단계코드");

                    b.Property<string>("MaterialVariantKey")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)")
                        .HasColumnName("재질변형키");

                    b.Property<bool>("PresentationOnly")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("표현전용여부");

                    b.Property<string>("PresentationScopeCode")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("표현범위코드");

                    b.Property<string>("QualityTierCode")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("품질단계코드");

                    b.Property<bool>("ReceiveShadows")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("그림자수신여부");

                    b.Property<long>("RunId")
                        .HasColumnType("bigint")
                        .HasColumnName("파생실행식별번호");

                    b.Property<decimal?>("ShadowDistanceMeters")
                        .HasPrecision(12, 4)
                        .HasColumnType("decimal(12,4)")
                        .HasColumnName("그림자거리미터");

                    b.Property<string>("ShadowPolicyCode")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("그림자정책코드");

                    b.Property<string>("StableId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("그래픽표현고유식별자");

                    b.Property<string>("TargetNodeStableId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("대상노드고유식별자");

                    b.Property<string>("TextureSetKey")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)")
                        .HasColumnName("질감세트키");

                    b.Property<string>("TimeOfDayProfileKey")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)")
                        .HasColumnName("시간대Profile키");

                    b.HasKey("Id");

                    b.HasIndex("RunId", "StableId")
                        .IsUnique();

                    b.ToTable("시뮬레이션월드_그래픽표현계획", (string)null);
                });

            modelBuilder.Entity("Ssalddel.Simulation.Persistence.SimulationWorld시각배치Entity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("식별번호");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("LodCode")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("세부표현단계코드");

                    b.Property<decimal>("PositionX")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("위치X");

                    b.Property<decimal>("PositionY")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("위치Y");

                    b.Property<decimal>("PositionZ")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("위치Z");

                    b.Property<bool>("PresentationOnly")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("표현전용여부");

                    b.Property<decimal>("RotationY")
                        .HasPrecision(9, 4)
                        .HasColumnType("decimal(9,4)")
                        .HasColumnName("Y축회전");

                    b.Property<long>("RunId")
                        .HasColumnType("bigint")
                        .HasColumnName("파생실행식별번호");

                    b.Property<string>("StableId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("시각배치고유식별자");

                    b.Property<string>("TargetNodeStableId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("대상노드고유식별자");

                    b.Property<decimal>("UniformScale")
                        .HasPrecision(9, 4)
                        .HasColumnType("decimal(9,4)")
                        .HasColumnName("균일축척");

                    b.Property<string>("VisualKey")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)")
                        .HasColumnName("시각키");

                    b.HasKey("Id");

                    b.HasIndex("RunId", "StableId")
                        .IsUnique();

                    b.ToTable("시뮬레이션월드_시각배치계획", (string)null);
                });

            modelBuilder.Entity("Ssalddel.Simulation.Persistence.SimulationWorld원본계보Entity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("식별번호");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("DatasetCode")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)")
                        .HasColumnName("자료코드");

                    b.Property<DateTimeOffset?>("ReferenceTimeUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("자료기준시각UTC");

                    b.Property<long>("RunId")
                        .HasColumnType("bigint")
                        .HasColumnName("파생실행식별번호");

                    b.Property<string>("SourceDatabaseCode")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("원본DB코드");

                    b.Property<string>("SourceHashSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("원본SHA256");

                    b.Property<string>("SourceRevision")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)")
                        .HasColumnName("원본개정번호");

                    b.Property<string>("SourceStableId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("원본계보고유식별자");

                    b.HasKey("Id");

                    b.HasIndex("RunId", "SourceStableId")
                        .IsUnique();

                    b.ToTable("시뮬레이션월드_원본계보", (string)null);
                });

            modelBuilder.Entity("Ssalddel.Simulation.Persistence.SimulationWorld파생NodeEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("식별번호");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AreaStableId")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("영역고유식별자");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(240)
                        .HasColumnType("varchar(240)")
                        .HasColumnName("표시이름");

                    b.Property<string>("EvidenceKindCode")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("근거종류코드");

                    b.Property<string>("NodeKindCode")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("노드종류코드");

                    b.Property<string>("RegionCode")
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("행정구역코드");

                    b.Property<long>("RunId")
                        .HasColumnType("bigint")
                        .HasColumnName("파생실행식별번호");

                    b.Property<string>("SourceRecordStableId")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("원본레코드고유식별자");

                    b.Property<string>("SourceStableId")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("원본계보고유식별자");

                    b.Property<string>("StableId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("노드고유식별자");

                    b.Property<string>("TileKey")
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("타일키");

                    b.HasKey("Id");

                    b.HasIndex("RunId", "StableId")
                        .IsUnique();

                    b.ToTable("시뮬레이션월드_파생노드", (string)null);
                });

            modelBuilder.Entity("Ssalddel.Simulation.Persistence.SimulationWorld파생RelationEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("식별번호");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Confidence")
                        .HasPrecision(6, 5)
                        .HasColumnType("decimal(6,5)")
                        .HasColumnName("신뢰도");

                    b.Property<string>("EvidenceKindCode")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("근거종류코드");

                    b.Property<string>("FromNodeStableId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("시작노드고유식별자");

                    b.Property<string>("RelationCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("관계코드");

                    b.Property<long>("RunId")
                        .HasColumnType("bigint")
                        .HasColumnName("파생실행식별번호");

                    b.Property<string>("SourceStableId")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("원본계보고유식별자");

                    b.Property<string>("StableId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("관계고유식별자");

                    b.Property<string>("ToNodeStableId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("도착노드고유식별자");

                    b.HasKey("Id");

                    b.HasIndex("RunId", "StableId")
                        .IsUnique();

                    b.ToTable("시뮬레이션월드_파생관계", (string)null);
                });

            modelBuilder.Entity("Ssalddel.Simulation.Persistence.SimulationWorld파생RunEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("식별번호");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AreaSetStableId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("영역묶음고유식별자");

                    b.Property<string>("BuildStableId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("파생실행고유식별자");

                    b.Property<DateTimeOffset>("GeneratedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("생성시각UTC");

                    b.Property<string>("InputFingerprintSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("입력지문SHA256");

                    b.Property<string>("OutputHashSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("출력해시SHA256");

                    b.Property<string>("RecipeRevision")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("생성조리법개정번호");

                    b.Property<string>("RuleRevision")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("관계규칙개정번호");

                    b.Property<int>("SchemaVersion")
                        .HasColumnType("int")
                        .HasColumnName("스키마버전");

                    b.Property<int>("Seed")
                        .HasColumnType("int")
                        .HasColumnName("배치시드");

                    b.Property<DateTimeOffset>("StoredAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("저장시각UTC");

                    b.Property<string>("VisualCatalogRevision")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("시각자산대장개정번호");

                    b.HasKey("Id");

                    b.HasIndex("BuildStableId")
                        .IsUnique();

                    b.ToTable("시뮬레이션월드_파생실행", (string)null);
                });

            modelBuilder.Entity("Ssalddel.Simulation.Persistence.SimulationWorldUnity공간변환Entity", b =>
                {
                    b.HasOne("Ssalddel.Simulation.Persistence.SimulationWorld파생RunEntity", "Run")
                        .WithMany()
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Run");
                });

            modelBuilder.Entity("Ssalddel.Simulation.Persistence.SimulationWorldUnity산출물Entity", b =>
                {
                    b.HasOne("Ssalddel.Simulation.Persistence.SimulationWorld파생RunEntity", "Run")
                        .WithMany()
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Run");
                });

            modelBuilder.Entity("Ssalddel.Simulation.Persistence.SimulationWorldUnity타일ManifestEntity", b =>
                {
                    b.HasOne("Ssalddel.Simulation.Persistence.SimulationWorld파생RunEntity", "Run")
                        .WithMany()
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Run");
                });

            modelBuilder.Entity("Ssalddel.Simulation.Persistence.SimulationWorld건물배치Entity", b =>
                {
                    b.HasOne("Ssalddel.Simulation.Persistence.SimulationWorld파생RunEntity", "Run")
                        .WithMany()
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Run");
                });

            modelBuilder.Entity("Ssalddel.Simulation.Persistence.SimulationWorld그래픽표현Entity", b =>
                {
                    b.HasOne("Ssalddel.Simulation.Persistence.SimulationWorld파생RunEntity", "Run")
                        .WithMany()
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Run");
                });

            modelBuilder.Entity("Ssalddel.Simulation.Persistence.SimulationWorld시각배치Entity", b =>
                {
                    b.HasOne("Ssalddel.Simulation.Persistence.SimulationWorld파생RunEntity", "Run")
                        .WithMany()
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Run");
                });

            modelBuilder.Entity("Ssalddel.Simulation.Persistence.SimulationWorld원본계보Entity", b =>
                {
                    b.HasOne("Ssalddel.Simulation.Persistence.SimulationWorld파생RunEntity", "Run")
                        .WithMany()
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Run");
                });

            modelBuilder.Entity("Ssalddel.Simulation.Persistence.SimulationWorld파생NodeEntity", b =>
                {
                    b.HasOne("Ssalddel.Simulation.Persistence.SimulationWorld파생RunEntity", "Run")
                        .WithMany()
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Run");
                });

            modelBuilder.Entity("Ssalddel.Simulation.Persistence.SimulationWorld파생RelationEntity", b =>
                {
                    b.HasOne("Ssalddel.Simulation.Persistence.SimulationWorld파생RunEntity", "Run")
                        .WithMany()
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Run");
                });
#pragma warning restore 612, 618
        }
    }
}
