// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Ssalddel.Simulation.Persistence;

#nullable disable

namespace Ssalddel.Simulation.Persistence.Migrations.WorldDerivation
{
    [DbContext(typeof(SimulationWorld파생DbContext))]
    partial class SimulationWorld파생DbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Ssalddel.Simulation.Persistence.SimulationWorldScenario규칙묶음Entity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("식별번호");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AreaSetStableId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("AreaSet고유식별자");

                    b.Property<long>("CatalogId")
                        .HasColumnType("bigint")
                        .HasColumnName("규칙대장식별번호");

                    b.Property<string>("Revision")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("규칙묶음개정번호");

                    b.Property<string>("StableId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("Scenario규칙묶음고유식별자");

                    b.HasKey("Id");

                    b.HasIndex("CatalogId", "StableId", "Revision")
                        .IsUnique();

                    b.ToTable("시뮬레이션월드_Scenario규칙묶음", (string)null);
                });

            modelBuilder.Entity("Ssalddel.Simulation.Persistence.SimulationWorldScenario규칙항목Entity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("식별번호");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("ApplyOrder")
                        .HasColumnType("int")
                        .HasColumnName("적용순서");

                    b.Property<long>("CatalogId")
                        .HasColumnType("bigint")
                        .HasColumnName("규칙대장식별번호");

                    b.Property<bool>("Required")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("필수여부");

                    b.Property<string>("RuleRevision")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("규칙개정번호");

                    b.Property<string>("RuleSetRevision")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("규칙묶음개정번호");

                    b.Property<string>("RuleSetStableId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("Scenario규칙묶음고유식별자");

                    b.Property<string>("RuleStableId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("규칙고유식별자");

                    b.HasKey("Id");

                    b.HasIndex("CatalogId", "RuleSetStableId", "RuleSetRevision", "RuleStableId", "RuleRevision")
                        .IsUnique();

                    b.ToTable("시뮬레이션월드_Scenario규칙항목", (string)null);
                });

            modelBuilder.Entity("Ssalddel.Simulation.Persistence.SimulationWorldSimulation규칙MetadataEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("식별번호");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CatalogId")
                        .HasColumnType("bigint")
                        .HasColumnName("규칙대장식별번호");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("규칙설명");

                    b.Property<string>("ExpectedStateCode")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)")
                        .HasColumnName("기대상태코드");

                    b.Property<string>("Revision")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Simulation규칙개정번호");

                    b.Property<string>("StableId")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)")
                        .HasColumnName("Simulation규칙고유식별자");

                    b.Property<string>("StateTypeCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("상태종류코드");

                    b.Property<string>("StatusCode")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("규칙상태코드");

                    b.HasKey("Id");

                    b.HasIndex("CatalogId", "StableId", "Revision")
                        .IsUnique();

                    b.ToTable("시뮬레이션월드_Simulation규칙Metadata", (string)null);
                });

            modelBuilder.Entity("Ssalddel.Simulation.Persistence.SimulationWorldSynty경관RunEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("식별번호");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AreaSetStableId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("영역묶음고유식별자");

                    b.Property<DateTimeOffset>("GeneratedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("생성시각UTC");

                    b.Property<string>("InputFingerprintSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("입력지문SHA256");

                    b.Property<string>("JobStableId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("작업고유식별자");

                    b.Property<string>("LandscapeRuleRevision")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("경관규칙개정번호");

                    b.Property<string>("OutputHashSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("출력해시SHA256");

                    b.Property<string>("QualityTierCode")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("품질단계코드");

                    b.Property<int>("SchemaVersion")
                        .HasColumnType("int")
                        .HasColumnName("스키마버전");

                    b.Property<string>("ScopeKindCode")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("작업범위종류코드");

                    b.Property<string>("ScopeStableId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("작업범위고유식별자");

                    b.Property<int>("Seed")
                        .HasColumnType("int")
                        .HasColumnName("배치시드");

                    b.Property<string>("SpatialBuildStableId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("공간실행고유식별자");

                    b.Property<string>("SpatialOutputHashSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("공간출력SHA256");

                    b.Property<string>("StatusCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("작업상태코드");

                    b.Property<DateTimeOffset>("StoredAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("저장시각UTC");

                    b.Property<string>("TargetPlatformCode")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("대상플랫폼코드");

                    b.Property<string>("UrpProfileCatalogRevision")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("URP표현대장개정번호");

                    b.Property<string>("VisualBuildStableId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("시각실행고유식별자");

                    b.Property<string>("VisualCatalogRevision")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("Synty구성대장개정번호");

                    b.HasKey("Id");

                    b.HasIndex("JobStableId");

                    b.HasIndex("SpatialBuildStableId");

                    b.HasIndex("VisualBuildStableId")
                        .IsUnique();

                    b.ToTable("시뮬레이션월드_Synty경관실행", (string)null);
                });

            modelBuilder.Entity("Ssalddel.Simulation.Persistence.SimulationWorldSynty그래픽표현Entity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("식별번호");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal>("AmbientOcclusionStrength")
                        .HasPrecision(5, 4)
                        .HasColumnType("decimal(5,4)")
                        .HasColumnName("주변광차폐강도");

                    b.Property<string>("BackgroundProfileKey")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)")
                        .HasColumnName("배경Profile키");

                    b.Property<bool>("CastShadows")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("그림자투사여부");

                    b.Property<string>("ColorPaletteKey")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("색조팔레트키");

                    b.Property<decimal>("ContactShadowStrength")
                        .HasPrecision(5, 4)
                        .HasColumnType("decimal(5,4)")
                        .HasColumnName("접지그림자강도");

                    b.Property<string>("LightingProfileKey")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)")
                        .HasColumnName("조명Profile키");

                    b.Property<string>("LodCode")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("세부표현단계코드");

                    b.Property<string>("MaterialVariantKey")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)")
                        .HasColumnName("재질변형키");

                    b.Property<bool>("PresentationOnly")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("표현전용여부");

                    b.Property<string>("PresentationScopeCode")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("표현범위코드");

                    b.Property<string>("QualityTierCode")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("품질단계코드");

                    b.Property<bool>("ReceiveShadows")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("그림자수신여부");

                    b.Property<decimal?>("ShadowDistanceMeters")
                        .HasPrecision(12, 4)
                        .HasColumnType("decimal(12,4)")
                        .HasColumnName("그림자거리미터");

                    b.Property<string>("ShadowPolicyCode")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("그림자정책코드");

                    b.Property<string>("StableId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("그래픽표현고유식별자");

                    b.Property<string>("TargetNodeStableId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("대상노드고유식별자");

                    b.Property<string>("TextureSetKey")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)")
                        .HasColumnName("질감세트키");

                    b.Property<string>("TimeOfDayProfileKey")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)")
                        .HasColumnName("시간대Profile키");

                    b.Property<long>("VisualRunId")
                        .HasColumnType("bigint")
                        .HasColumnName("Synty경관실행식별번호");

                    b.HasKey("Id");

                    b.HasIndex("VisualRunId", "StableId")
                        .IsUnique();

                    b.ToTable("시뮬레이션월드_Synty그래픽표현계획", (string)null);
                });

            modelBuilder.Entity("Ssalddel.Simulation.Persistence.SimulationWorldSynty배치거부Entity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("식별번호");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Detail")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("거부상세");

                    b.Property<string>("ReasonCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("거부사유코드");

                    b.Property<string>("StableId")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("varchar(240)")
                        .HasColumnName("배치거부고유식별자");

                    b.Property<string>("TargetNodeStableId")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("대상노드고유식별자");

                    b.Property<long>("VisualRunId")
                        .HasColumnType("bigint")
                        .HasColumnName("Synty경관실행식별번호");

                    b.HasKey("Id");

                    b.HasIndex("VisualRunId", "StableId")
                        .IsUnique();

                    b.ToTable("시뮬레이션월드_Synty배치거부", (string)null);
                });

            modelBuilder.Entity("Ssalddel.Simulation.Persistence.SimulationWorldSynty시각배치Entity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("식별번호");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("LodCode")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("세부표현단계코드");

                    b.Property<decimal>("PositionX")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("위치X");

                    b.Property<decimal>("PositionY")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("위치Y");

                    b.Property<decimal>("PositionZ")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("위치Z");

                    b.Property<bool>("PresentationOnly")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("표현전용여부");

                    b.Property<decimal>("RotationY")
                        .HasPrecision(9, 4)
                        .HasColumnType("decimal(9,4)")
                        .HasColumnName("Y축회전");

                    b.Property<string>("StableId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("시각배치고유식별자");

                    b.Property<string>("TargetNodeStableId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("대상노드고유식별자");

                    b.Property<decimal>("UniformScale")
                        .HasPrecision(9, 4)
                        .HasColumnType("decimal(9,4)")
                        .HasColumnName("균일축척");

                    b.Property<string>("VisualKey")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)")
                        .HasColumnName("시각키");

                    b.Property<long>("VisualRunId")
                        .HasColumnType("bigint")
                        .HasColumnName("Synty경관실행식별번호");

                    b.HasKey("Id");

                    b.HasIndex("VisualRunId", "StableId")
                        .IsUnique();

                    b.ToTable("시뮬레이션월드_Synty시각배치계획", (string)null);
                });

            modelBuilder.Entity("Ssalddel.Simulation.Persistence.SimulationWorldUnity공간변환Entity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("식별번호");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AreaSetStableId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("영역묶음고유식별자");

                    b.Property<string>("AxisMappingCode")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("좌표축변환코드");

                    b.Property<decimal>("HorizontalScale")
                        .HasPrecision(12, 6)
                        .HasColumnType("decimal(12,6)")
                        .HasColumnName("수평축척률");

                    b.Property<decimal>("MetersPerUnityUnit")
                        .HasPrecision(12, 6)
                        .HasColumnType("decimal(12,6)")
                        .HasColumnName("Unity단위당미터");

                    b.Property<decimal?>("OriginEastingMeters")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("Unity원점동쪽좌표미터");

                    b.Property<decimal?>("OriginNorthingMeters")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("Unity원점북쪽좌표미터");

                    b.Property<string>("ProfileHashSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("변환ProfileSHA256");

                    b.Property<decimal?>("ReferenceElevationMeters")
                        .HasPrecision(12, 4)
                        .HasColumnType("decimal(12,4)")
                        .HasColumnName("기준표고미터");

                    b.Property<string>("RuleRevision")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("변환규칙개정번호");

                    b.Property<long>("RunId")
                        .HasColumnType("bigint")
                        .HasColumnName("파생실행식별번호");

                    b.Property<string>("SourceCrsCode")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("원본좌표계코드");

                    b.Property<string>("StableId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("공간변환고유식별자");

                    b.Property<string>("StatusCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("변환상태코드");

                    b.Property<decimal>("VerticalExaggeration")
                        .HasPrecision(12, 6)
                        .HasColumnType("decimal(12,6)")
                        .HasColumnName("높이과장률");

                    b.HasKey("Id");

                    b.HasIndex("RunId", "StableId")
                        .IsUnique();

                    b.ToTable("시뮬레이션월드_Unity공간변환Profile", (string)null);
                });

            modelBuilder.Entity("Ssalddel.Simulation.Persistence.SimulationWorldUnity산출물Entity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("식별번호");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ArtifactHashSha256")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("산출물SHA256");

                    b.Property<string>("ArtifactKindCode")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("산출물종류코드");

                    b.Property<string>("BoundaryVertexHashSha256")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("경계정점SHA256");

                    b.Property<int?>("EstimatedDrawCallCount")
                        .HasColumnType("int")
                        .HasColumnName("예상DrawCall수");

                    b.Property<string>("LodCode")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("세부표현단계코드");

                    b.Property<int?>("MaterialSlotCount")
                        .HasColumnType("int")
                        .HasColumnName("재질슬롯수");

                    b.Property<long>("RunId")
                        .HasColumnType("bigint")
                        .HasColumnName("파생실행식별번호");

                    b.Property<string>("StableId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("산출물고유식별자");

                    b.Property<string>("StatusCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("생성상태코드");

                    b.Property<string>("StorageObjectKey")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("산출물보관객체키");

                    b.Property<string>("TileManifestStableId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("타일Manifest고유식별자");

                    b.Property<long?>("TriangleCount")
                        .HasColumnType("bigint")
                        .HasColumnName("삼각형수");

                    b.Property<long?>("VertexCount")
                        .HasColumnType("bigint")
                        .HasColumnName("정점수");

                    b.HasKey("Id");

                    b.HasIndex("RunId", "StableId")
                        .IsUnique();

                    b.HasIndex("RunId", "TileManifestStableId");

                    b.ToTable("시뮬레이션월드_Unity산출물", (string)null);
                });

            modelBuilder.Entity("Ssalddel.Simulation.Persistence.SimulationWorldUnity타일ManifestEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("식별번호");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal>("HaloMeters")
                        .HasPrecision(12, 4)
                        .HasColumnType("decimal(12,4)")
                        .HasColumnName("여유영역미터");

                    b.Property<string>("InputFingerprintSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("입력지문SHA256");

                    b.Property<int>("Level")
                        .HasColumnType("int")
                        .HasColumnName("타일단계");

                    b.Property<string>("ManifestHashSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("ManifestSHA256");

                    b.Property<decimal>("MaxEastingMeters")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("최대동쪽좌표미터");

                    b.Property<decimal>("MaxNorthingMeters")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("최대북쪽좌표미터");

                    b.Property<decimal>("MinEastingMeters")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("최소동쪽좌표미터");

                    b.Property<decimal>("MinNorthingMeters")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("최소북쪽좌표미터");

                    b.Property<long>("RunId")
                        .HasColumnType("bigint")
                        .HasColumnName("파생실행식별번호");

                    b.Property<decimal>("SizeMeters")
                        .HasPrecision(12, 4)
                        .HasColumnType("decimal(12,4)")
                        .HasColumnName("타일크기미터");

                    b.Property<string>("StableId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("타일Manifest고유식별자");

                    b.Property<string>("StatusCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("생성상태코드");

                    b.Property<string>("TileKey")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("타일키");

                    b.Property<string>("TransformProfileStableId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("공간변환고유식별자");

                    b.HasKey("Id");

                    b.HasIndex("RunId", "StableId")
                        .IsUnique();

                    b.HasIndex("RunId", "TileKey");

                    b.ToTable("시뮬레이션월드_Unity타일Manifest", (string)null);
                });

            modelBuilder.Entity("Ssalddel.Simulation.Persistence.SimulationWorld객체업무규칙연결Entity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("식별번호");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("활성여부");

                    b.Property<string>("CapabilityCode")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("기능코드");

                    b.Property<long>("CatalogId")
                        .HasColumnType("bigint")
                        .HasColumnName("규칙대장식별번호");

                    b.Property<string>("EvidenceKindCode")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("근거종류코드");

                    b.Property<string>("FacilityStableId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("시설고유식별자");

                    b.Property<int>("Priority")
                        .HasColumnType("int")
                        .HasColumnName("우선순위");

                    b.Property<string>("RuleRevision")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("규칙개정번호");

                    b.Property<string>("RuleStableId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("규칙고유식별자");

                    b.Property<string>("ScopeCode")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("적용범위코드");

                    b.Property<string>("StableId")
                        .IsRequired()
                        .HasMaxLength(360)
                        .HasColumnType("varchar(360)")
                        .HasColumnName("연결고유식별자");

                    b.HasKey("Id");

                    b.HasIndex("CatalogId", "StableId")
                        .IsUnique();

                    b.ToTable("시뮬레이션월드_객체업무규칙연결", (string)null);
                });

            modelBuilder.Entity("Ssalddel.Simulation.Persistence.SimulationWorld객체표현결합규칙Entity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("식별번호");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CatalogId")
                        .HasColumnType("bigint")
                        .HasColumnName("규칙대장식별번호");

                    b.Property<string>("DefaultCompositionKey")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("varchar(180)")
                        .HasColumnName("기본구성키");

                    b.Property<string>("DynamicIntentBundleKey")
                        .HasMaxLength(180)
                        .HasColumnType("varchar(180)")
                        .HasColumnName("동적표현의도묶음키");

                    b.Property<string>("MinimumEvidenceKindCode")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("최소근거종류코드");

                    b.Property<string>("ObjectSemanticCode")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("객체의미코드");

                    b.Property<bool>("PresentationOnly")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("표현전용여부");

                    b.Property<int>("Priority")
                        .HasColumnType("int")
                        .HasColumnName("우선순위");

                    b.Property<string>("Revision")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("결합규칙개정번호");

                    b.Property<string>("ScopeCode")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("적용범위코드");

                    b.Property<bool>("SimulationRuleRequired")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("Simulation규칙필수여부");

                    b.Property<string>("SimulationRuleRevision")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Simulation규칙개정번호");

                    b.Property<string>("SimulationRuleStableId")
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)")
                        .HasColumnName("Simulation규칙고유식별자");

                    b.Property<string>("SpatialRuleRevision")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("공간규칙개정번호");

                    b.Property<string>("SpatialRuleStableId")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)")
                        .HasColumnName("공간규칙고유식별자");

                    b.Property<string>("StableId")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("varchar(180)")
                        .HasColumnName("결합규칙고유식별자");

                    b.Property<string>("StatusCode")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("규칙상태코드");

                    b.Property<string>("UnmetRuleHandlingCode")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("규칙미충족처리코드");

                    b.HasKey("Id");

                    b.HasIndex("CatalogId", "StableId", "Revision")
                        .IsUnique();

                    b.ToTable("시뮬레이션월드_객체표현결합규칙", (string)null);
                });

            modelBuilder.Entity("Ssalddel.Simulation.Persistence.SimulationWorld객체표현규칙CatalogEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("식별번호");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("CatalogHashSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("규칙대장SHA256");

                    b.Property<string>("CatalogRevision")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("규칙대장개정번호");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("생성시각UTC");

                    b.Property<int>("SchemaVersion")
                        .HasColumnType("int")
                        .HasColumnName("스키마버전");

                    b.Property<DateTimeOffset>("StoredAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("저장시각UTC");

                    b.HasKey("Id");

                    b.HasIndex("CatalogRevision")
                        .IsUnique();

                    b.ToTable("시뮬레이션월드_객체표현규칙대장", (string)null);
                });

            modelBuilder.Entity("Ssalddel.Simulation.Persistence.SimulationWorld객체표현해석ResultEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("식별번호");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AppliedBindingRuleRevision")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("적용결합규칙개정번호");

                    b.Property<string>("AppliedBindingRuleStableId")
                        .HasMaxLength(180)
                        .HasColumnType("varchar(180)")
                        .HasColumnName("적용결합규칙고유식별자");

                    b.Property<string>("AppliedSimulationRuleStableId")
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)")
                        .HasColumnName("적용Simulation규칙고유식별자");

                    b.Property<string>("AppliedSpatialRuleStableId")
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)")
                        .HasColumnName("적용공간규칙고유식별자");

                    b.Property<string>("DefaultCompositionKey")
                        .HasMaxLength(180)
                        .HasColumnType("varchar(180)")
                        .HasColumnName("기본구성키");

                    b.Property<string>("DynamicIntentBundleKey")
                        .HasMaxLength(180)
                        .HasColumnType("varchar(180)")
                        .HasColumnName("동적표현의도묶음키");

                    b.Property<string>("EvidenceKindCode")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("근거종류코드");

                    b.Property<long>("InterpretationRunId")
                        .HasColumnType("bigint")
                        .HasColumnName("해석실행식별번호");

                    b.Property<string>("ObjectSemanticCode")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("객체의미코드");

                    b.Property<bool>("PresentationOnly")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("표현전용여부");

                    b.Property<string>("ResolutionCode")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("해석결과코드");

                    b.Property<string>("ScopeCode")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("적용범위코드");

                    b.Property<string>("StableId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("해석결과고유식별자");

                    b.Property<string>("TargetNodeStableId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("대상노드고유식별자");

                    b.Property<string>("UnmetRuleHandlingCode")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("규칙미충족처리코드");

                    b.HasKey("Id");

                    b.HasIndex("InterpretationRunId", "StableId")
                        .IsUnique();

                    b.ToTable("시뮬레이션월드_객체표현해석결과", (string)null);
                });

            modelBuilder.Entity("Ssalddel.Simulation.Persistence.SimulationWorld객체표현해석RunEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("식별번호");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("InputFingerprintSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("입력FingerprintSHA256");

                    b.Property<string>("InterpretationStableId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("해석실행고유식별자");

                    b.Property<DateTimeOffset>("InterpretedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("해석시각UTC");

                    b.Property<string>("OutputHashSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("출력SHA256");

                    b.Property<string>("RuleCatalogRevision")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("규칙대장개정번호");

                    b.Property<int>("SchemaVersion")
                        .HasColumnType("int")
                        .HasColumnName("스키마버전");

                    b.Property<long?>("SimulationSessionRevision")
                        .HasColumnType("bigint")
                        .HasColumnName("Simulation세션개정번호");

                    b.Property<string>("SimulationSessionStableId")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("Simulation세션고유식별자");

                    b.Property<string>("SpatialBuildStableId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("공간실행고유식별자");

                    b.Property<string>("SpatialOutputHashSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("공간출력SHA256");

                    b.Property<DateTimeOffset>("StoredAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("저장시각UTC");

                    b.Property<long?>("WorldTick")
                        .HasColumnType("bigint")
                        .HasColumnName("WorldTick");

                    b.HasKey("Id");

                    b.HasIndex("InterpretationStableId")
                        .IsUnique();

                    b.ToTable("시뮬레이션월드_객체표현해석실행", (string)null);
                });

            modelBuilder.Entity("Ssalddel.Simulation.Persistence.SimulationWorld건물배치Entity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("식별번호");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AreaNodeStableId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("영역노드고유식별자");

                    b.Property<string>("BuildingCategoryCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("건물분류코드");

                    b.Property<string>("BuildingNodeStableId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("건물노드고유식별자");

                    b.Property<string>("EvidenceKindCode")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("근거종류코드");

                    b.Property<int>("FloorCount")
                        .HasColumnType("int")
                        .HasColumnName("표현층수");

                    b.Property<decimal?>("FootprintAreaSquareMeters")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("건물바닥면적제곱미터");

                    b.Property<decimal?>("HeightMeters")
                        .HasPrecision(12, 4)
                        .HasColumnType("decimal(12,4)")
                        .HasColumnName("높이미터");

                    b.Property<string>("PlacementBasisCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("배치근거코드");

                    b.Property<decimal>("PositionX")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("위치X");

                    b.Property<decimal>("PositionY")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("위치Y");

                    b.Property<decimal>("PositionZ")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("위치Z");

                    b.Property<bool>("PresentationOnly")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("표현전용여부");

                    b.Property<decimal>("RotationY")
                        .HasPrecision(9, 4)
                        .HasColumnType("decimal(9,4)")
                        .HasColumnName("Y축회전");

                    b.Property<long>("RunId")
                        .HasColumnType("bigint")
                        .HasColumnName("파생실행식별번호");

                    b.Property<string>("StableId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("건물배치고유식별자");

                    b.Property<string>("VisualFamilyCode")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("시각Family코드");

                    b.HasKey("Id");

                    b.HasIndex("RunId", "StableId")
                        .IsUnique();

                    b.ToTable("시뮬레이션월드_건물배치계획", (string)null);
                });

            modelBuilder.Entity("Ssalddel.Simulation.Persistence.SimulationWorld공간규칙MetadataEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("식별번호");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CatalogId")
                        .HasColumnType("bigint")
                        .HasColumnName("규칙대장식별번호");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("규칙설명");

                    b.Property<string>("ExpectedValueCode")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)")
                        .HasColumnName("기대값코드");

                    b.Property<string>("OperatorCode")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("연산자코드");

                    b.Property<string>("RequiredEvidenceKindCode")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("필수근거종류코드");

                    b.Property<string>("Revision")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("공간규칙개정번호");

                    b.Property<string>("SpatialFactKindCode")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("공간사실종류코드");

                    b.Property<string>("StableId")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)")
                        .HasColumnName("공간규칙고유식별자");

                    b.Property<string>("StatusCode")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("규칙상태코드");

                    b.HasKey("Id");

                    b.HasIndex("CatalogId", "StableId", "Revision")
                        .IsUnique();

                    b.ToTable("시뮬레이션월드_공간규칙Metadata", (string)null);
                });

            modelBuilder.Entity("Ssalddel.Simulation.Persistence.SimulationWorld그래픽표현Entity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("식별번호");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal>("AmbientOcclusionStrength")
                        .HasPrecision(5, 4)
                        .HasColumnType("decimal(5,4)")
                        .HasColumnName("주변광차폐강도");

                    b.Property<string>("BackgroundProfileKey")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)")
                        .HasColumnName("배경Profile키");

                    b.Property<bool>("CastShadows")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("그림자투사여부");

                    b.Property<string>("ColorPaletteKey")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("색조팔레트키");

                    b.Property<decimal>("ContactShadowStrength")
                        .HasPrecision(5, 4)
                        .HasColumnType("decimal(5,4)")
                        .HasColumnName("접지그림자강도");

                    b.Property<string>("LightingProfileKey")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)")
                        .HasColumnName("조명Profile키");

                    b.Property<string>("LodCode")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("세부표현단계코드");

                    b.Property<string>("MaterialVariantKey")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)")
                        .HasColumnName("재질변형키");

                    b.Property<bool>("PresentationOnly")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("표현전용여부");

                    b.Property<string>("PresentationScopeCode")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("표현범위코드");

                    b.Property<string>("QualityTierCode")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("품질단계코드");

                    b.Property<bool>("ReceiveShadows")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("그림자수신여부");

                    b.Property<long>("RunId")
                        .HasColumnType("bigint")
                        .HasColumnName("파생실행식별번호");

                    b.Property<decimal?>("ShadowDistanceMeters")
                        .HasPrecision(12, 4)
                        .HasColumnType("decimal(12,4)")
                        .HasColumnName("그림자거리미터");

                    b.Property<string>("ShadowPolicyCode")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("그림자정책코드");

                    b.Property<string>("StableId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("그래픽표현고유식별자");

                    b.Property<string>("TargetNodeStableId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("대상노드고유식별자");

                    b.Property<string>("TextureSetKey")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)")
                        .HasColumnName("질감세트키");

                    b.Property<string>("TimeOfDayProfileKey")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)")
                        .HasColumnName("시간대Profile키");

                    b.HasKey("Id");

                    b.HasIndex("RunId", "StableId")
                        .IsUnique();

                    b.ToTable("시뮬레이션월드_그래픽표현계획", (string)null);
                });

            modelBuilder.Entity("Ssalddel.Simulation.Persistence.SimulationWorld시각배치Entity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("식별번호");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("LodCode")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("세부표현단계코드");

                    b.Property<decimal>("PositionX")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("위치X");

                    b.Property<decimal>("PositionY")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("위치Y");

                    b.Property<decimal>("PositionZ")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("위치Z");

                    b.Property<bool>("PresentationOnly")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("표현전용여부");

                    b.Property<decimal>("RotationY")
                        .HasPrecision(9, 4)
                        .HasColumnType("decimal(9,4)")
                        .HasColumnName("Y축회전");

                    b.Property<long>("RunId")
                        .HasColumnType("bigint")
                        .HasColumnName("파생실행식별번호");

                    b.Property<string>("StableId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("시각배치고유식별자");

                    b.Property<string>("TargetNodeStableId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("대상노드고유식별자");

                    b.Property<decimal>("UniformScale")
                        .HasPrecision(9, 4)
                        .HasColumnType("decimal(9,4)")
                        .HasColumnName("균일축척");

                    b.Property<string>("VisualKey")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)")
                        .HasColumnName("시각키");

                    b.HasKey("Id");

                    b.HasIndex("RunId", "StableId")
                        .IsUnique();

                    b.ToTable("시뮬레이션월드_시각배치계획", (string)null);
                });

            modelBuilder.Entity("Ssalddel.Simulation.Persistence.SimulationWorld시설기능Entity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("식별번호");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("CapabilityCode")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("기능코드");

                    b.Property<long>("CatalogId")
                        .HasColumnType("bigint")
                        .HasColumnName("규칙대장식별번호");

                    b.Property<string>("EvidenceKindCode")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("근거종류코드");

                    b.Property<string>("FacilityStableId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("시설고유식별자");

                    b.Property<string>("StableId")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("시설기능고유식별자");

                    b.HasKey("Id");

                    b.HasIndex("CatalogId", "StableId")
                        .IsUnique();

                    b.ToTable("시뮬레이션월드_시설기능대장", (string)null);
                });

            modelBuilder.Entity("Ssalddel.Simulation.Persistence.SimulationWorld시설의미Entity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("식별번호");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CatalogId")
                        .HasColumnType("bigint")
                        .HasColumnName("규칙대장식별번호");

                    b.Property<string>("ConfidenceCode")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("분류신뢰수준코드");

                    b.Property<string>("EvidenceKindCode")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("근거종류코드");

                    b.Property<string>("EvidenceSourceStableId")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("varchar(240)")
                        .HasColumnName("근거원본고유식별자");

                    b.Property<string>("FacilityTypeCode")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("시설종류코드");

                    b.Property<bool>("ScenarioAssigned")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("Scenario지정여부");

                    b.Property<string>("SpatialNodeStableId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("공간노드고유식별자");

                    b.Property<string>("StableId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("시설고유식별자");

                    b.HasKey("Id");

                    b.HasIndex("CatalogId", "StableId")
                        .IsUnique();

                    b.ToTable("시뮬레이션월드_시설의미대장", (string)null);
                });

            modelBuilder.Entity("Ssalddel.Simulation.Persistence.SimulationWorld업무Simulation규칙Entity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("식별번호");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CatalogId")
                        .HasColumnType("bigint")
                        .HasColumnName("규칙대장식별번호");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("규칙설명");

                    b.Property<bool>("Deterministic")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("결정적실행여부");

                    b.Property<string>("DomainCode")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("규칙영역코드");

                    b.Property<string>("EngineKey")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("varchar(180)")
                        .HasColumnName("규칙Engine키");

                    b.Property<string>("InputContractKey")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("varchar(180)")
                        .HasColumnName("입력계약키");

                    b.Property<string>("OutputContractKey")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("varchar(180)")
                        .HasColumnName("출력계약키");

                    b.Property<string>("Revision")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("규칙개정번호");

                    b.Property<string>("RuleTypeCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("규칙종류코드");

                    b.Property<bool>("SimulationOnly")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("Simulation전용여부");

                    b.Property<string>("StableId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("규칙고유식별자");

                    b.Property<string>("StatusCode")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("규칙상태코드");

                    b.HasKey("Id");

                    b.HasIndex("CatalogId", "StableId", "Revision")
                        .IsUnique();

                    b.ToTable("시뮬레이션월드_업무Simulation규칙", (string)null);
                });

            modelBuilder.Entity("Ssalddel.Simulation.Persistence.SimulationWorld업무Simulation규칙ParameterEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("식별번호");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CatalogId")
                        .HasColumnType("bigint")
                        .HasColumnName("규칙대장식별번호");

                    b.Property<string>("EvidenceKindCode")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("근거종류코드");

                    b.Property<string>("ParameterCode")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("Parameter코드");

                    b.Property<string>("RuleRevision")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("규칙개정번호");

                    b.Property<string>("RuleStableId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("규칙고유식별자");

                    b.Property<string>("UnitCode")
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("단위코드");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("값");

                    b.Property<string>("ValueTypeCode")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("값종류코드");

                    b.HasKey("Id");

                    b.HasIndex("CatalogId", "RuleStableId", "RuleRevision", "ParameterCode")
                        .IsUnique();

                    b.ToTable("시뮬레이션월드_업무Simulation규칙Parameter", (string)null);
                });

            modelBuilder.Entity("Ssalddel.Simulation.Persistence.SimulationWorld업무규칙CatalogEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("식별번호");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("CatalogHashSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("규칙대장SHA256");

                    b.Property<string>("CatalogRevision")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("규칙대장개정번호");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("생성시각UTC");

                    b.Property<int>("SchemaVersion")
                        .HasColumnType("int")
                        .HasColumnName("스키마버전");

                    b.Property<string>("SpatialBuildStableId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("공간실행고유식별자");

                    b.Property<string>("SpatialOutputHashSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("공간출력SHA256");

                    b.Property<DateTimeOffset>("StoredAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("저장시각UTC");

                    b.HasKey("Id");

                    b.HasIndex("CatalogRevision")
                        .IsUnique();

                    b.ToTable("시뮬레이션월드_업무Simulation규칙대장", (string)null);
                });

            modelBuilder.Entity("Ssalddel.Simulation.Persistence.SimulationWorld원본계보Entity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("식별번호");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("DatasetCode")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)")
                        .HasColumnName("자료코드");

                    b.Property<DateTimeOffset?>("ReferenceTimeUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("자료기준시각UTC");

                    b.Property<long>("RunId")
                        .HasColumnType("bigint")
                        .HasColumnName("파생실행식별번호");

                    b.Property<string>("SourceDatabaseCode")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("원본DB코드");

                    b.Property<string>("SourceHashSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("원본SHA256");

                    b.Property<string>("SourceRevision")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)")
                        .HasColumnName("원본개정번호");

                    b.Property<string>("SourceStableId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("원본계보고유식별자");

                    b.HasKey("Id");

                    b.HasIndex("RunId", "SourceStableId")
                        .IsUnique();

                    b.ToTable("시뮬레이션월드_원본계보", (string)null);
                });

            modelBuilder.Entity("Ssalddel.Simulation.Persistence.SimulationWorld파생NodeEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("식별번호");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AreaStableId")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("영역고유식별자");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(240)
                        .HasColumnType("varchar(240)")
                        .HasColumnName("표시이름");

                    b.Property<string>("EvidenceKindCode")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("근거종류코드");

                    b.Property<string>("NodeKindCode")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("노드종류코드");

                    b.Property<string>("RegionCode")
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("행정구역코드");

                    b.Property<string>("RepresentativeGroupCode")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("대표군코드");

                    b.Property<int?>("RepresentativeRank")
                        .HasColumnType("int")
                        .HasColumnName("대표순위");

                    b.Property<int?>("RepresentedRecordCount")
                        .HasColumnType("int")
                        .HasColumnName("대표원본건수");

                    b.Property<long>("RunId")
                        .HasColumnType("bigint")
                        .HasColumnName("파생실행식별번호");

                    b.Property<string>("SourceRecordStableId")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("원본레코드고유식별자");

                    b.Property<string>("SourceStableId")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("원본계보고유식별자");

                    b.Property<string>("StableId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("노드고유식별자");

                    b.Property<string>("TileKey")
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("타일키");

                    b.HasKey("Id");

                    b.HasIndex("RunId", "StableId")
                        .IsUnique();

                    b.ToTable("시뮬레이션월드_파생노드", (string)null);
                });

            modelBuilder.Entity("Ssalddel.Simulation.Persistence.SimulationWorld파생RelationEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("식별번호");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Confidence")
                        .HasPrecision(6, 5)
                        .HasColumnType("decimal(6,5)")
                        .HasColumnName("신뢰도");

                    b.Property<string>("EvidenceKindCode")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("근거종류코드");

                    b.Property<string>("FromNodeStableId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("시작노드고유식별자");

                    b.Property<string>("RelationCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("관계코드");

                    b.Property<long>("RunId")
                        .HasColumnType("bigint")
                        .HasColumnName("파생실행식별번호");

                    b.Property<string>("SourceStableId")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("원본계보고유식별자");

                    b.Property<string>("StableId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("관계고유식별자");

                    b.Property<string>("ToNodeStableId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("도착노드고유식별자");

                    b.HasKey("Id");

                    b.HasIndex("RunId", "StableId")
                        .IsUnique();

                    b.ToTable("시뮬레이션월드_파생관계", (string)null);
                });

            modelBuilder.Entity("Ssalddel.Simulation.Persistence.SimulationWorld파생RunEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("식별번호");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AreaSetStableId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("영역묶음고유식별자");

                    b.Property<string>("BuildStableId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("파생실행고유식별자");

                    b.Property<DateTimeOffset>("GeneratedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("생성시각UTC");

                    b.Property<string>("InputFingerprintSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("입력지문SHA256");

                    b.Property<string>("OutputHashSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("출력해시SHA256");

                    b.Property<string>("RecipeRevision")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("생성조리법개정번호");

                    b.Property<string>("RuleRevision")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("관계규칙개정번호");

                    b.Property<int>("SchemaVersion")
                        .HasColumnType("int")
                        .HasColumnName("스키마버전");

                    b.Property<int>("Seed")
                        .HasColumnType("int")
                        .HasColumnName("배치시드");

                    b.Property<DateTimeOffset>("StoredAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("저장시각UTC");

                    b.Property<string>("VisualCatalogRevision")
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("시각자산대장개정번호");

                    b.HasKey("Id");

                    b.HasIndex("BuildStableId")
                        .IsUnique();

                    b.ToTable("시뮬레이션월드_파생실행", (string)null);
                });

            modelBuilder.Entity("Ssalddel.Simulation.Persistence.SimulationWorldScenario규칙묶음Entity", b =>
                {
                    b.HasOne("Ssalddel.Simulation.Persistence.SimulationWorld업무규칙CatalogEntity", null)
                        .WithMany()
                        .HasForeignKey("CatalogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ssalddel.Simulation.Persistence.SimulationWorldScenario규칙항목Entity", b =>
                {
                    b.HasOne("Ssalddel.Simulation.Persistence.SimulationWorld업무규칙CatalogEntity", null)
                        .WithMany()
                        .HasForeignKey("CatalogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ssalddel.Simulation.Persistence.SimulationWorldSimulation규칙MetadataEntity", b =>
                {
                    b.HasOne("Ssalddel.Simulation.Persistence.SimulationWorld객체표현규칙CatalogEntity", "Catalog")
                        .WithMany()
                        .HasForeignKey("CatalogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Catalog");
                });

            modelBuilder.Entity("Ssalddel.Simulation.Persistence.SimulationWorldSynty그래픽표현Entity", b =>
                {
                    b.HasOne("Ssalddel.Simulation.Persistence.SimulationWorldSynty경관RunEntity", "VisualRun")
                        .WithMany()
                        .HasForeignKey("VisualRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VisualRun");
                });

            modelBuilder.Entity("Ssalddel.Simulation.Persistence.SimulationWorldSynty배치거부Entity", b =>
                {
                    b.HasOne("Ssalddel.Simulation.Persistence.SimulationWorldSynty경관RunEntity", "VisualRun")
                        .WithMany()
                        .HasForeignKey("VisualRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VisualRun");
                });

            modelBuilder.Entity("Ssalddel.Simulation.Persistence.SimulationWorldSynty시각배치Entity", b =>
                {
                    b.HasOne("Ssalddel.Simulation.Persistence.SimulationWorldSynty경관RunEntity", "VisualRun")
                        .WithMany()
                        .HasForeignKey("VisualRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VisualRun");
                });

            modelBuilder.Entity("Ssalddel.Simulation.Persistence.SimulationWorldUnity공간변환Entity", b =>
                {
                    b.HasOne("Ssalddel.Simulation.Persistence.SimulationWorld파생RunEntity", "Run")
                        .WithMany()
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Run");
                });

            modelBuilder.Entity("Ssalddel.Simulation.Persistence.SimulationWorldUnity산출물Entity", b =>
                {
                    b.HasOne("Ssalddel.Simulation.Persistence.SimulationWorld파생RunEntity", "Run")
                        .WithMany()
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Run");
                });

            modelBuilder.Entity("Ssalddel.Simulation.Persistence.SimulationWorldUnity타일ManifestEntity", b =>
                {
                    b.HasOne("Ssalddel.Simulation.Persistence.SimulationWorld파생RunEntity", "Run")
                        .WithMany()
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Run");
                });

            modelBuilder.Entity("Ssalddel.Simulation.Persistence.SimulationWorld객체업무규칙연결Entity", b =>
                {
                    b.HasOne("Ssalddel.Simulation.Persistence.SimulationWorld업무규칙CatalogEntity", null)
                        .WithMany()
                        .HasForeignKey("CatalogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ssalddel.Simulation.Persistence.SimulationWorld객체표현결합규칙Entity", b =>
                {
                    b.HasOne("Ssalddel.Simulation.Persistence.SimulationWorld객체표현규칙CatalogEntity", "Catalog")
                        .WithMany()
                        .HasForeignKey("CatalogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Catalog");
                });

            modelBuilder.Entity("Ssalddel.Simulation.Persistence.SimulationWorld객체표현해석ResultEntity", b =>
                {
                    b.HasOne("Ssalddel.Simulation.Persistence.SimulationWorld객체표현해석RunEntity", "InterpretationRun")
                        .WithMany()
                        .HasForeignKey("InterpretationRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InterpretationRun");
                });

            modelBuilder.Entity("Ssalddel.Simulation.Persistence.SimulationWorld건물배치Entity", b =>
                {
                    b.HasOne("Ssalddel.Simulation.Persistence.SimulationWorld파생RunEntity", "Run")
                        .WithMany()
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Run");
                });

            modelBuilder.Entity("Ssalddel.Simulation.Persistence.SimulationWorld공간규칙MetadataEntity", b =>
                {
                    b.HasOne("Ssalddel.Simulation.Persistence.SimulationWorld객체표현규칙CatalogEntity", "Catalog")
                        .WithMany()
                        .HasForeignKey("CatalogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Catalog");
                });

            modelBuilder.Entity("Ssalddel.Simulation.Persistence.SimulationWorld그래픽표현Entity", b =>
                {
                    b.HasOne("Ssalddel.Simulation.Persistence.SimulationWorld파생RunEntity", "Run")
                        .WithMany()
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Run");
                });

            modelBuilder.Entity("Ssalddel.Simulation.Persistence.SimulationWorld시각배치Entity", b =>
                {
                    b.HasOne("Ssalddel.Simulation.Persistence.SimulationWorld파생RunEntity", "Run")
                        .WithMany()
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Run");
                });

            modelBuilder.Entity("Ssalddel.Simulation.Persistence.SimulationWorld시설기능Entity", b =>
                {
                    b.HasOne("Ssalddel.Simulation.Persistence.SimulationWorld업무규칙CatalogEntity", null)
                        .WithMany()
                        .HasForeignKey("CatalogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ssalddel.Simulation.Persistence.SimulationWorld시설의미Entity", b =>
                {
                    b.HasOne("Ssalddel.Simulation.Persistence.SimulationWorld업무규칙CatalogEntity", null)
                        .WithMany()
                        .HasForeignKey("CatalogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ssalddel.Simulation.Persistence.SimulationWorld업무Simulation규칙Entity", b =>
                {
                    b.HasOne("Ssalddel.Simulation.Persistence.SimulationWorld업무규칙CatalogEntity", null)
                        .WithMany()
                        .HasForeignKey("CatalogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ssalddel.Simulation.Persistence.SimulationWorld업무Simulation규칙ParameterEntity", b =>
                {
                    b.HasOne("Ssalddel.Simulation.Persistence.SimulationWorld업무규칙CatalogEntity", null)
                        .WithMany()
                        .HasForeignKey("CatalogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ssalddel.Simulation.Persistence.SimulationWorld원본계보Entity", b =>
                {
                    b.HasOne("Ssalddel.Simulation.Persistence.SimulationWorld파생RunEntity", "Run")
                        .WithMany()
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Run");
                });

            modelBuilder.Entity("Ssalddel.Simulation.Persistence.SimulationWorld파생NodeEntity", b =>
                {
                    b.HasOne("Ssalddel.Simulation.Persistence.SimulationWorld파생RunEntity", "Run")
                        .WithMany()
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Run");
                });

            modelBuilder.Entity("Ssalddel.Simulation.Persistence.SimulationWorld파생RelationEntity", b =>
                {
                    b.HasOne("Ssalddel.Simulation.Persistence.SimulationWorld파생RunEntity", "Run")
                        .WithMany()
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Run");
                });
#pragma warning restore 612, 618
        }
    }
}
