using FluentResults;

namespace Hongdal.Application.Shipper.Request;

public sealed record 의뢰수정Command(
    string RequestId,
    string? 운송방식,
    string? 차량종류,
    string? 결제수단,
    int? 결제예정금액,
    string? 화물종류,
    string? 화물설명,
    int? 화물수량,
    decimal? 화물중량Kg,
    decimal? 화물부피Cbm,
    bool? 화물파손주의여부,
    string? 화물온도조건,
    string? 픽업도로명주소,
    string? 픽업상세주소,
    decimal? 픽업위도,
    decimal? 픽업경도,
    string? 픽업연락처이름,
    string? 픽업연락처전화번호,
    DateTime? 픽업시간창시작일시,
    DateTime? 픽업시간창종료일시,
    string? 하차도로명주소,
    string? 하차상세주소,
    decimal? 하차위도,
    decimal? 하차경도,
    string? 하차연락처이름,
    string? 하차연락처전화번호,
    DateTime? 하차시간창시작일시,
    DateTime? 하차시간창종료일시,
    string? 서비스레벨,
    string? 요청사항,
    decimal? 대기료,
    decimal? 수작업비,
    decimal? 할증,
    string? 결제상태,
    string? 상태,
    string? 배차상태) : IRequest<Result<Hongdal.Contracts.Shipper.Request.화주운송의뢰응답>>;
