<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <LangVersion>9.0</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <RootNamespace>Ssalddel.Unity.Data</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Samples~\**\*.cs" />
  </ItemGroup>

</Project>
