@Ssalddel.FoodApi_HostAddress = http://localhost:5187

GET {{Ssalddel.FoodApi_HostAddress}}/api/v1/restaurants/nearby
Accept: application/json

###

GET {{Ssalddel.FoodApi_HostAddress}}/api/v1/food-orders
Accept: application/json
