using Microsoft.EntityFrameworkCore;
using Ssalddel.Domain.Content;

namespace Ssalddel.Infrastructure.Persistence.WorldProjection;

/// <summary>대응/감사/자산판본만 소유한다. 원천 Context의 전체 마이그레이션과 분리한다.</summary>
public sealed class 개체시각대응DbContext(DbContextOptions<개체시각대응DbContext> options) : DbContext(options)
{
    public DbSet<개체시각대응> Bindings => Set<개체시각대응>();
    public DbSet<개체시각대응이력> History => Set<개체시각대응이력>();
    public DbSet<개체시각자산판본> Assets => Set<개체시각자산판본>();
    public DbSet<게임객체시각정의> Definitions => Set<게임객체시각정의>();
    public DbSet<게임객체시각구성판본> Compositions => Set<게임객체시각구성판본>();
    public DbSet<게임객체시각구성항목> CompositionItems => Set<게임객체시각구성항목>();
    public DbSet<게임객체시각구성이력> CompositionHistory => Set<게임객체시각구성이력>();
    public DbSet<게임객체WI추출묶음> WiBatches => Set<게임객체WI추출묶음>();
    public DbSet<게임객체WI참여> WiUses => Set<게임객체WI참여>();
    public DbSet<보유시각자산사본> InventorySnapshots => Set<보유시각자산사본>();
    public DbSet<보유시각자산후보연결> InventoryLinks => Set<보유시각자산후보연결>();
    public DbSet<보유시각분류주석> InventoryClassifications => Set<보유시각분류주석>();

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        var classification = modelBuilder.Entity<보유시각분류주석>();
        classification.ToTable("world_visual_inventory_classifications"); classification.HasKey(x => x.AnnotationId);
        foreach (var name in new[] { "AnnotationId", "SnapshotId", "ContentVersionId", "TaxonomyHash", "InputHash" }) classification.Property<string>(name).HasMaxLength(64);
        classification.Property(x => x.TaxonomyPath).HasMaxLength(320).IsRequired();
        classification.Property(x => x.State).HasMaxLength(40).IsRequired();
        classification.Property(x => x.Traits).HasMaxLength(1000).IsRequired();
        classification.Property(x => x.InputJson).IsRequired();
        classification.Property(x => x.RegisteredBy).HasMaxLength(450).IsRequired();
        classification.HasIndex(x => new { x.SnapshotId, x.TaxonomyHash, x.TaxonomyPath }).IsUnique();
        classification.HasOne<보유시각자산사본>().WithMany().HasForeignKey(x => x.SnapshotId).OnDelete(DeleteBehavior.Restrict);
        var inventory = modelBuilder.Entity<보유시각자산사본>();
        inventory.ToTable("world_visual_inventory_snapshots"); inventory.HasKey(x => x.SnapshotId);
        foreach (var name in new[] { "SnapshotId", "ContentVersionId", "MetadataHash", "EvidenceHash" }) inventory.Property<string>(name).HasMaxLength(64);
        inventory.Property(x => x.Guid).HasMaxLength(32).IsRequired();
        inventory.Property(x => x.SurveyRevision).HasMaxLength(160).IsRequired();
        inventory.Property(x => x.SourceGroup).HasMaxLength(160).IsRequired();
        inventory.Property(x => x.PackCode).HasMaxLength(160);
        inventory.Property(x => x.AssetKind).HasMaxLength(80).IsRequired();
        inventory.Property(x => x.Name).HasMaxLength(256).IsRequired();
        inventory.Property(x => x.RelativePath).HasMaxLength(512).IsRequired();
        inventory.Property(x => x.EvidenceRef).HasMaxLength(512).IsRequired();
        inventory.Property(x => x.MetadataJson).IsRequired();
        inventory.Property(x => x.RegisteredBy).HasMaxLength(450).IsRequired();
        inventory.HasIndex(x => new { x.Guid, x.SurveyRevision }).IsUnique();
        inventory.HasIndex(x => new { x.SourceGroup, x.AssetKind });
        inventory.HasIndex(x => x.PackCode);
        var inventoryLink = modelBuilder.Entity<보유시각자산후보연결>();
        inventoryLink.ToTable("world_visual_inventory_candidate_links");
        inventoryLink.HasKey(x => new { x.SnapshotId, x.AssetVersionId });
        inventoryLink.Property(x => x.SnapshotId).HasMaxLength(64); inventoryLink.Property(x => x.AssetVersionId).HasMaxLength(64);
        inventoryLink.HasOne<보유시각자산사본>().WithMany().HasForeignKey(x => x.SnapshotId).OnDelete(DeleteBehavior.Restrict);
        inventoryLink.HasOne<개체시각자산판본>().WithMany().HasForeignKey(x => x.AssetVersionId).OnDelete(DeleteBehavior.Restrict);
        var wb = modelBuilder.Entity<게임객체WI추출묶음>();
        wb.ToTable("world_visual_object_wi_batches");
        wb.HasKey(x => x.BatchId);
        foreach (var name in new[] { "BatchId", "RequestHash", "SourceHash" }) wb.Property<string>(name).HasMaxLength(64);
        wb.Property(x => x.SourceRevision).HasMaxLength(160).IsRequired();
        wb.Property(x => x.ReviewerId).HasMaxLength(450).IsRequired();
        var wu = modelBuilder.Entity<게임객체WI참여>();
        wu.ToTable("world_visual_object_wi_uses");
        wu.HasKey(x => new { x.SourceHash, x.UseId });
        foreach (var name in new[] { "SourceHash", "UseId", "BatchId", "InputHash" }) wu.Property<string>(name).HasMaxLength(64);
        wu.Property(x => x.DefinitionId).HasMaxLength(120);
        wu.Property(x => x.DefinitionCompositionId).HasMaxLength(64);
        wu.Property(x => x.WorldInteractionId).HasMaxLength(80).IsRequired();
        wu.Property(x => x.Role).HasMaxLength(80).IsRequired();
        wu.Property(x => x.InputJson).IsRequired();
        wu.HasIndex(x => new { x.WorldInteractionId, x.DefinitionId });
        wu.HasOne<게임객체WI추출묶음>().WithMany().HasForeignKey(x => x.BatchId).OnDelete(DeleteBehavior.Restrict);
        wu.HasOne<게임객체시각정의>().WithMany().HasForeignKey(x => x.DefinitionId).OnDelete(DeleteBehavior.ClientNoAction);
        wu.HasOne<게임객체시각구성판본>().WithMany().HasForeignKey(x => x.DefinitionCompositionId).OnDelete(DeleteBehavior.ClientNoAction);
        var d = modelBuilder.Entity<게임객체시각정의>();
        d.ToTable("world_visual_object_definitions");
        d.HasKey(x => x.DefinitionId);
        d.Property(x => x.DefinitionId).HasMaxLength(120);
        d.Property(x => x.Revision).IsConcurrencyToken();
        var c = modelBuilder.Entity<게임객체시각구성판본>();
        c.ToTable("world_visual_object_compositions");
        c.HasKey(x => x.CompositionId);
        c.Property(x => x.CompositionId).HasMaxLength(64);
        c.Property(x => x.DefinitionId).HasMaxLength(120).IsRequired();
        c.HasOne<게임객체시각정의>().WithMany().HasForeignKey(x => x.DefinitionId).OnDelete(DeleteBehavior.Restrict);
        c.HasIndex(x => new { x.DefinitionId, x.Revision }).IsUnique();
        c.Property(x => x.SnapshotJson).IsRequired();
        c.Property(x => x.SnapshotHash).HasMaxLength(64).IsRequired();
        c.Property(x => x.ReviewerId).HasMaxLength(450).IsRequired();
        var i = modelBuilder.Entity<게임객체시각구성항목>();
        i.ToTable("world_visual_object_composition_items");
        i.HasKey(x => new { x.CompositionId, x.ItemId });
        i.Property(x => x.CompositionId).HasMaxLength(64);
        i.Property(x => x.ItemId).HasMaxLength(80);
        i.Property(x => x.Role).HasMaxLength(80).IsRequired();
        i.Property(x => x.SlotKey).HasMaxLength(80).IsRequired();
        i.Property(x => x.AssetVersionId).HasMaxLength(64);
        i.Property(x => x.AnchorIntent).HasMaxLength(160);
        i.Property(x => x.InventorySnapshotId).HasMaxLength(64);
        i.Property(x => x.SelectionEvidenceJson);
        i.HasOne<보유시각자산사본>().WithMany().HasForeignKey(x => x.InventorySnapshotId).OnDelete(DeleteBehavior.ClientNoAction);
        i.HasOne<게임객체시각구성판본>().WithMany().HasForeignKey(x => x.CompositionId).OnDelete(DeleteBehavior.Restrict);
        // nullable은 미선정을 뜻한다. 추적 중 자산 삭제 시 EF가 FK를 null로 바꾸지 못하게 한다.
        i.HasOne<개체시각자산판본>().WithMany().HasForeignKey(x => x.AssetVersionId).OnDelete(DeleteBehavior.ClientNoAction);
        i.HasIndex(x => new { x.CompositionId, x.Role, x.SlotKey }).IsUnique();
        var j = modelBuilder.Entity<게임객체시각구성이력>();
        j.ToTable("world_visual_object_composition_history");
        j.HasKey(x => x.RequestKeyHash);
        j.Property(x => x.RequestKeyHash).HasMaxLength(64);
        j.Property(x => x.RequestHash).HasMaxLength(64).IsRequired();
        j.Property(x => x.CompositionId).HasMaxLength(64).IsRequired();
        j.HasIndex(x => x.CompositionId).IsUnique();
        j.HasOne<게임객체시각구성판본>().WithMany().HasForeignKey(x => x.CompositionId).OnDelete(DeleteBehavior.Restrict);
        var a = modelBuilder.Entity<개체시각자산판본>();
        a.ToTable("world_visual_asset_versions");
        a.HasKey(x => x.AssetVersionId);
        a.Property(x => x.AssetVersionId).HasMaxLength(64);
        a.Property(x => x.VisualKey).HasMaxLength(160).IsRequired();
        a.Property(x => x.CatalogRevision).HasMaxLength(160).IsRequired();
        a.HasIndex(x => new { x.VisualKey, x.CatalogRevision }).IsUnique();
        a.Property(x => x.PrefabGuid).HasMaxLength(32).IsRequired();
        a.HasIndex(x => x.PrefabGuid);
        a.Property(x => x.MetadataHash).HasMaxLength(64).IsRequired();
        a.Property(x => x.MetadataJson).IsRequired();
        a.Property(x => x.VerificationState).HasMaxLength(48).IsRequired();
        a.Property(x => x.RegisteredBy).HasMaxLength(450).IsRequired();
        var b = modelBuilder.Entity<개체시각대응>();
        b.ToTable("world_entity_visual_bindings");
        b.HasKey(x => x.BindingId);
        b.Property(x => x.BindingId).HasMaxLength(120);
        b.Property(x => x.ContextHash).HasMaxLength(64).IsRequired();
        b.HasIndex(x => x.ContextHash).IsUnique();
        b.Property(x => x.Revision).IsConcurrencyToken();
        b.Property(x => x.Kind).HasMaxLength(80).IsRequired();
        b.Property(x => x.AccessScope).HasMaxLength(160).IsRequired();
        b.Property(x => x.ReviewState).HasMaxLength(32).IsRequired();
        b.Property(x => x.StateJson).IsRequired();
        b.HasIndex(x => new { x.Kind, x.AccessScope, x.ReviewState });
        b.Property(x => x.AssetVersionId).HasMaxLength(64);
        b.HasOne<개체시각자산판본>().WithMany().HasForeignKey(x => x.AssetVersionId).OnDelete(DeleteBehavior.Restrict);
        foreach (var name in new[] { nameof(개체시각대응.SourceKey), nameof(개체시각대응.SourceStableId),
            nameof(개체시각대응.SourceRevision), nameof(개체시각대응.StateCode), nameof(개체시각대응.Purpose), nameof(개체시각대응.Representation) })
            b.Property<string?>(name).HasMaxLength(160);
        b.HasIndex(x => new { x.Kind, x.SourceStableId, x.Purpose });

        var h = modelBuilder.Entity<개체시각대응이력>();
        h.ToTable("world_entity_visual_binding_history");
        h.HasKey(x => x.RequestKeyHash);
        h.Property(x => x.RequestKeyHash).HasMaxLength(64);
        h.Property(x => x.BindingId).HasMaxLength(120).IsRequired();
        h.HasIndex(x => new { x.BindingId, x.Revision }).IsUnique();
        h.HasOne<개체시각대응>().WithMany().HasForeignKey(x => x.BindingId).OnDelete(DeleteBehavior.Restrict);
        h.Property(x => x.RequestHash).HasMaxLength(64).IsRequired();
        h.Property(x => x.ReviewerId).HasMaxLength(450).IsRequired();
        h.Property(x => x.Action).HasMaxLength(32).IsRequired();
        h.Property(x => x.Note).HasMaxLength(1000).IsRequired();
        h.Property(x => x.StateJson).IsRequired();
    }
}
